powsybl/powsybl-core

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TerminalBuilder.java
It's not necessary to specify bus and connectableBus in BusBreakerTopology. If the two values are specified we have to check if both are equals.
=> Bus and ConnectableBus can also be exclusive

distribution-core/pom.xml, pom.xml
- generate individual jacoco reports suffixed by the artifactId of each module
- copy all the jacoco files to target/jacoco of the aggregator module
- merge the reports to target/jacoco-merge.exec of the parent module
- use the merge report in sonar analysis
Hack: due to the two levels of hierarchy, we have to specify to different path to the merged report in sonar.jacoco.reportPaths property
=> Fix sonarcloud.io code coverage score

action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/RunningContext.java, afs/afs-ext-base/src/main/java/com/powsybl/afs/ext/base/LocalNetworkService.java, commons/src/main/java/com/powsybl/commons/config/ModuleConfig.java, commons/src/main/java/com/powsybl/commons/config/PlatformConfig.java, commons/src/main/java/com/powsybl/commons/config/PropertiesPlatformConfig.java, commons/src/main/java/com/powsybl/commons/config/XmlPlatformConfig.java, commons/src/main/java/com/powsybl/commons/datasource/GzMemDataSource.java, commons/src/main/java/com/powsybl/commons/util/StringAnonymizer.java, computation-mpi/src/main/java/com/powsybl/computation/mpi/CsvMpiStatistics.java, computation/src/main/java/com/powsybl/computation/AbstractExecutionHandler.java, computation/src/main/java/com/powsybl/computation/CommandExecutor.java, computation/src/main/java/com/powsybl/computation/ComputationManager.java, computation/src/main/java/com/powsybl/computation/DefaultExecutionHandler.java, computation/src/main/java/com/powsybl/computation/ExecutionHandler.java, computation/src/main/java/com/powsybl/computation/InputFile.java, contingency-api/src/main/java/com/powsybl/contingency/tasks/ModificationTask.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/AbstractTopologyVisitor.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ConnectedComponent.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/SingleTerminalConnectable.java, iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ValidationUtil.java, security-analysis/src/main/java/com/powsybl/security/PostContingencyResult.java, security-analysis/src/main/java/com/powsybl/security/PreContingencyResult.java, tools/src/main/java/com/powsybl/tools/CommandLineTools.java, tools/src/main/java/com/powsybl/tools/Tool.java, ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java, ucte/ucte-network/src/main/java/com/powsybl/ucte/network/io/UcteRecordWriter.java
- Format specifiers should be used instead of string concatenation.
- Use already-defined constant 'TYPE_DESCRIPTION' instead of duplicating its value here.
- Rename "xxx" which hides the field declared at line XX.
- Replace this "Map.get()" and condition with a call to "Map.computeIfAbsent()".
- Add the "@Override" annotation above this method signature
- Put single-quotes around '.' to use the faster "lastIndexOf(char)" method.
- Use the built-in formatting to construct this argument.
- Add the missing @deprecated Javadoc tag.
=> Fix sonar issues

action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulator.java, action/action-simulator/src/test/java/com/powsybl/action/simulator/AbstractLoadFlowRulesEngineTest.java, action/action-util/src/main/java/com/powsybl/action/util/LoadFlowBasedPhaseShifterOptimizer.java, loadflow/loadflow-api/src/main/groovy/com/powsybl/loadflow/LoadFlowGroovyScriptExtension.groovy, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/tools/RunLoadFlowTool.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowExtensionGroovyScriptTest.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowParametersTest.java
- Extensions may be defined in platform config and loaded
through an instance of LoadFlowParameters.ConfigLoader.
- Deprecate the run() method of the LoadFlow interface
=> Add extension mechanism for loadflow parameters.

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Line.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LineCharacteristics.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
Rename the LineCharasteristics interface to LineCharacteristics
Fix the type of oldValue in ShuntCompensatorImpl::setMaximumSectionCount
=> Small fixes in IIDM implementation

commons/src/main/java/com/powsybl/commons/config/ModuleConfig.java, computation/src/main/java/com/powsybl/computation/CommandExecutor.java, computation/src/main/java/com/powsybl/computation/ComputationManager.java, computation/src/main/java/com/powsybl/computation/ExecutionHandler.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java, security-analysis/src/main/java/com/powsybl/security/SecurityAnalysis.java
Add a default implementation to all deprecated methods to be able to safely remove these methods (without compilation issue or synchronization)
=> Add a default implementation to all deprecated methods

action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/ExpressionEvaluator.java, action/action-dsl/src/test/java/com/powsybl/action/dsl/ConditionDslLoaderTest.java
=> Check if branches exist in the network to avoid NullPointerException later

pom.xml
Fix release generation by generating a javadoc jar also for cim1-model module
=> Generate javadoc also for cim1-model module

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
Use EnumSet for the countries of a network, in particular to respect a constant order
from call to call to "getCountries".
=> Constant countries ordering

afs/afs-core/src/main/java/com/powsybl/afs/AppFileSystemTool.java, scripting/src/main/groovy/com/powsybl/scripting/groovy/AfsGroovyFacade.groovy, scripting/src/test/java/com/powsybl/scripting/groovy/AfsGroovyScriptTest.java, tools/src/main/java/com/powsybl/tools/CommandLineTools.java
- print the usage instead of throwing an exception if the sub command is not pass
- rename listFs function to getFileSystemNames
=> AFS command line tool improvements

loadflow/loadflow-validation/pom.xml, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/CandidateComputation.java, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/CandidateComputations.java, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/LoadFlowComputation.java, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationTool.java, loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/CandidateComputationsTest.java
- Add "CandidateComputation" interface for validation.
- Add a command line option "--run-computation <COMPUTATION>" to select which
"CandidateComputation" to run.
- Add loadflow based implementation
=> Add arbitrary "CandidateComputation" for loadflow validation

ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java, ucte/ucte-converter/src/test/resources/sameId.uct
- In UCTE importer, leave possibility to have transformers and lines with same IDs.
This is allowed by the format. A more accurate solution should still forbid 2 lines
to have the same ID, or 2 transformers to have the same ID, and maybe have a
custom ID in that case.
- Add corresponding unit test.
=> Ability to import UCTE files with line and transformer with same ID

ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplConstants.java, ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java, ampl-converter/src/test/resources/inputs/svc-test-case.txt
Export of B min and max for SVCs was not consistent with other equipments.
=> Fix AMPL export for SVCs (per-unit instead of S).

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/CalculatedTopologyTest.java
For a given identifier that corresponds to a configured bus or a busbar section, obtain the merged bus in the calculated topology.
This method is used in CGMES to compare the given topology in the TP file with the topology computed by powsybl after import.
=> Obtain the merged bus in the calculated topology

cim1/cim1-converter/pom.xml, cim1/cim1-converter/src/main/java/com/powsybl/cim1/converter/CIM1Converter.java, cim1/cim1-converter/src/test/java/com/powsybl/cim1/converter/CIM1ConverterRatioTapChangerSide2FixTest.java, cim1/cim1-converter/src/test/java/com/powsybl/cim1/converter/CIM1ImporterTest.java, cim1/cim1-converter/src/test/resources/tx-from-microBE-adapted_EQ.xml, cim1/cim1-converter/src/test/resources/tx-from-microBE-adapted_SV.xml, cim1/cim1-converter/src/test/resources/tx-from-microBE-adapted_TP.xml
The deviations have to be applied because we are moving ratio tap changer from side 2 to side 1.
The unit test case uses a transformer from ENTSO-E Conformity Assessment test configuration: transformer _e482b89a-fa84-4ea9-8e70-a83d44790957 from TestConfigurations_packageCASv2.0 MicroGrid test configuration, assembled base case. 
The power transformer and its ratio tap changer have been adapted from CGMES to CIM Profile 1. The P, Q values for the generator and the load that represents the rest of the network in the adapted CIM1 case have been taken from the case documentation: Documentation/MicroGrid.xls. The expected active/reactive power flows at side 1 of the transformer must match the injection from the generator. The expected active/reactive power flows at side 2 must match the …
=> Fix CIM1 converter to consider deviations in impedance/admittance

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/BranchData.java, loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/LoadFlowResultsCompletion.java, loadflow/loadflow-results-completion/src/test/java/com/powsybl/loadflow/BranchDataTest.java, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/BusesValidation.java, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/FlowsValidation.java, loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/FlowsValidationTest.java
Unified duplicated code for power flow computation: it was present in `BranchData.java` (in `loadflow-results-completion` module) and in `FlowsValidation.java` (in `loadflow-validation` module). 
Moved the `BranchData.java` module to iidm-api module (inside `util` package) and used it from `loadflow-validation`.
Thought it was convenient to move the code to `iidm-api`, conceptually it is at a similar level of already existing `SV.java` code. Also, it helps to get rid of potential cyclic dependencies between loadflow results completion and loadflow validation.
=> Unify duplicated code for power flow computation

action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulator.java
otherwise, there is an important performance penalty for all action simulator executions which do not use the test actions.
=> Test actions: only clone network if it is actually needed

action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulator.java, action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/ParallelLoadFlowActionSimulator.java, action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/SecurityAnalysisResultHandler.java, action/action-simulator/src/main/java/com/powsybl/action/simulator/tools/ActionSimulatorTool.java, action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/ParallelLoadFlowActionSimulatorTest.java, computation/src/main/java/com/powsybl/computation/SimpleCommandBuilder.java, computation/src/test/java/com/powsybl/computation/SimpleCommandTest.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisResultMerger.java
* Only use one working directory for all subtasks, copying only once input files
* Try to use business objects instead of command line arguments for the parallel implementation
=> Parallel action-simulator: copy once

computation/src/main/java/com/powsybl/computation/LazyCreatedComputationManager.java
the delegate was systematically created and closed
when closing the lazy implementation.
=> Fix closing of lazily created computation managers:

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/Substations.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java
**Bug Fix** : 
* Substations.*filter* used to exclude substation with same country : **CORRECTED**
* the method getSubstations(Country country, String tso, String... geographicalTags) is tested in NetworkTest
=> Fix bug in getSubstations(Country country, String tso, String... geographicalTags)

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/ExternalSecurityAnalysis.java
extensions delimiter should be only "comma" not "comma space"
=> extensions delimiter for ExternalSecurityAnalysis bug fixing

loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletion.java, loadflow/loadflow-results-completion/src/test/java/com/powsybl/loadflow/resultscompletion/AbstractLoadFlowResultsCompletionTest.java
Compute reactive flow for the shunt compensators from current B and voltage of the connected bus,  when the data is not available at the shunt terminal.
=> Shunts load flow results completion

cgmes/cgmes-model/src/main/resources/CIM16.sparql
`ACDCTerminal.sequenceNumber` is not a required property. ENTSO-E node-breaker test configurations use it, but sample test cases from FINGRID do not.
=> Do not use ACDCTerminal.sequenceNumber to identify the switch terminals

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NodeBreakerViewInternalConnectionXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java, iidm/iidm-xml-converter/src/main/resources/xsd/iidm.xsd, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NodeBreakerInternalConnectionsTest.java, iidm/iidm-xml-converter/src/test/resources/internalConnections.xiidm
CGMES node-breaker models will be mapped to IIDM node-breaker topologies using internal connections.
Internal connections will be used to support CGMES ability to support multiple conducting equipment directly connected to a single Connectivity Node (in IIDM a node in the node-breaker topology can have only one element attached). Internal connections are preferred against fictitious switches, to avoid creation of unneeded objects.
=> IIDM-XML converter: read/write internal connections for node breaker topologies

ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
Solve issue in UCTE importer causing tie lines' current limits absence in IIDM network
=> Solve issue in UCTE importer causing tie lines' current limits absence in IIDM network

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1Catalog.java, cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java, cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1Test.java, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_BD_v2/MicroGridTestConfiguration_EQ_BD.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_BD_v2/MicroGridTestConfiguration_TP_BD.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_T4_BE_BB_Complete_v2/MicroGridTestConfiguration_T4_BE_DL_V2.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_T4_BE_BB_Complete_v2/MicroGridTestConfiguration_T4_BE_DY_V2.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_T4_BE_BB_Complete_v2/MicroGridTestConfiguration_T4_BE_EQ_V2.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_T4_BE_BB_Complete_v2/MicroGridTestConfiguration_T4_BE_GL_V2.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_T4_BE_BB_Complete_v2/MicroGridTestConfiguration_T4_BE_SSH_V2.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_T4_BE_BB_Complete_v2/MicroGridTestConfiguration_T4_BE_SV_V2.xml, cgmes/cgmes-conformity/src/test/resources/conformity/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/CGMES_v2.4.15_MicroGridTestConfiguration_T4_BE_BB_Complete_v2/MicroGridTestConfiguration_T4_BE_TP_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractBranchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentBranchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SeriesCompensatorConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Convert CGMES Nonlinear Shunt Compensators (multiple sections with different admittance) to IIDM Shunt Compensators with a single section for the total susceptance (b) of sections in service.
As for Linear Shunt Compensators, conductance (g) is ignored. IIDM shunt compensators only have susceptance.
=> CGMES Nonlinear Shunt Compensators

iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NodeBreakerInternalConnectionsTest.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java, iidm/iidm-xml-converter/src/test/resources/internalConnections.xiidm
Added unit test in IIDM implementation to show the difference between the original and fixed traversal of node breaker topology.
=> fix traversal of node breaker topology for XML export of internal connections

afs/afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java
to return an ordered list from getDependencies() method we use a LinkedHashSet instead of HashSet
=> return a LinkedHashSet from method getDependencies

distribution-core/pom.xml
Added by mistake in 2de6618ccd and 0778ac6596.
maven logs:
[WARNING] Some problems were encountered while building the effective model for com.powsybl:powsybl-distribution-core:pom:2.4.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: ${project.groupId}:powsybl-iidm-reducer:jar -> duplicate declaration of version ${project.version} @ com.powsybl:powsybl-distribution-core:[unknown-version], /home/harperjon/powsybl/powsybl-core/distribution-core/pom.xml, line 252, column 21
=> distribution-core/pom.xml: cleanup duplicate dependency

pom.xml
* The behavior with a normal setup (a real git checkout, and having git in the path) doesn't change.
* The behavior with a zip source export and having git in path changes
Before:
```super("powsybl-core", "2.4.0-SNAPSHOT", "${buildNumber}", "UNKNOWN_BRANCH", Long.parseLong("1549457054776"));```
After:
```super("powsybl-core", "2.4.0-SNAPSHOT", "UNKNOWN_BUILD", "UNKNOWN_BRANCH", Long.parseLong("1549457164750"));```
* The behavior without git in path goes from a build error to the same output as using a zip export and having git in the path.
Documentation: http://www.mojohaus.org/buildnumber-maven-plugin/create-mojo.html#revisionOnScmFailure
=> pom.xml: fix builds when git is not in path. fixes #596

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/VoltageLevelConversion.java
Instead of providing a default value computed from low/high voltage limits, throw an exception if nominal voltage is not found for base voltage.
It is probably the result of boundary data not being loaded.
=> cgmes - throw exception if nominalVoltage is missing

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql, cim1/cim1-converter/src/test/java/com/powsybl/cim1/converter/CIM1ConverterRatioTapChangerSide2FixTest.java, loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletion.java, loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletionParameters.java
Observed in the same test case that contains switches between different voltage levels that are converted to IIDM low impedance lines. 
The voltage levels at the ends of these switches are simply separate containers: they have the same base voltage and are in the same substation (they could be "merged" in IIDM to avoid creating a low impedance line).
In addition, end buses of these switches do not have exactly the same voltage and angle. The difference between voltages is < 3e-7 kV and the diff between angles is < 9e-8 degrees.
To take into account this situation and complete flows through these switches, a threshold for the check of zero impedance lines has been added.
=> CGMES Rotating Machine ratedS is optional

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java
if terminal node is in the boundary and the boundary has not been loaded
=> substation id may be null 

time-series/time-series-api/src/main/java/com/powsybl/timeseries/RegularTimeSeriesIndex.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/RegularTimeSeriesIndexTest.java
getPointCount was wrong for huge values. I added tests for normal and huge values. I added a check that pointCount fits in a int in the constructor. I stored the computed value instead of recomputing it everytime.
For the fix for the huge values error, we could have used:
```
return (int) ((endTime - startTime + (spacing / 2)) / spacing) + 1;
```
This works for values upto 2^63ms ie ~300 million years.
But I went for code that is more similar to what was existing, using a double instead of a float to do the computation (works for values upto 2^53 ie ~300 thousands years)
=> Regulartimeseries pointcount

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Some data sources may miss the EQ file. 
Throw an error if we can not find EQ data inside the current CGMES model.
=> At least one set of data with EquipmentCore profile in the CGMES model

loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/z0flows/Z0BusGroup.java
Consider that a z0 bus group is valid if it contains more than one bus or any number of loops.
=> In z0 results completion, consider all loops

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java
Refine initial value for shunt sections:
First take number of sections given in the SV (State Variables). If that information is not available, use value from SSH (Steady State Hypothesis). If the property is not defined in SSH, use normal sections defined in the EQ profile (Equipment).
=> Initial value for shunt sections

triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreRDF4J.java
Allow identifiers containing spaces or beginning with a #. 
Some TSOs may produce RDF XML files with identifiers that do not pass strict XML syntax rules for names.
Jena triple store was logging the errors without failing. The configuration of the RDF4J XML parser has been updated to follow the same strategy.
=> CGMES using RDF4J triple store engine: non-fatal errors on invalid identifiers

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractIdentifiedObjectConversion.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
Consider name an optional attribute for connectivity nodes.
Although the attribute is required for all objects (defined in IdentifiedObject class), some TSOs may produce models that do not have names for some connectivity nodes.
=> CGMES: allow unnamed connectivity nodes

time-series/time-series-api/src/main/java/com/powsybl/timeseries/BigDoubleBuffer.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/BigStringBuffer.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/CalculatedTimeSeries.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/CompactStringBuffer.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/CompressedDoubleDataChunk.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/CompressedStringDataChunk.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/DoubleDataChunk.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/DoubleTimeSeries.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/StoredDoubleTimeSeries.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/StringDataChunk.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/StringTimeSeries.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeriesTable.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/UncompressedDoubleDataChunk.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/UncompressedStringDataChunk.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/BigDoubleBufferTest.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/BigStringBufferTest.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTableTest.java
I still want to test a little more when using MemoryMappedBuffer.
time-series: TimeSeriesTable, allow to have more than 2gb of data
To do this, we use 1 giga (2^30) *bytes* segment into the table. This allows to use
memory mapped buffer for these segments (it would not have been possible if
we had use buffers of 2^30 *elements*) and to use bitshifts and masks to compute indices
(2^30 is the largest power of two no greater than Integer.MAX_VALUE (2^31-1))
Each timeseries is still constrained on its own to have a number of elements that fits in
an array (~2 billions). We keep the previous fillBuffer implementations because they allow to return a
single array without extra copying (and that's up to 16 gb for doubles; unbounded for strings)
We copypaste part of the previous fillBuffer …
=> time-series: TimeSeriesTable, allow to have more than 2gb of data

afs/afs-storage-api/src/main/java/com/powsybl/afs/storage/DefaultListenableAppStorage.java, afs/afs-storage-api/src/main/java/com/powsybl/afs/storage/ListenableAppStorage.java, afs/afs-storage-api/src/test/java/com/powsybl/afs/storage/DefaultListenableAppStorageTest.java
* data updated events are now now created on close of the writing stream, not on creation of the stream
* Add a warning about weak references for app storage listeners in javadoc
=> Fix listenable app storage data updated events

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
Bug fix
When the terminal of an `EnergyConsumer` is not mapped, the power flow returns a `NaN ` value for
constant active and reactive power which is forbidden. This caused standard `MicroGrid` files of CIMDesk to fail.
`pfixed` and  `qfixed` are used if present as constant active and reactive power. Else, p and q of mapped terminal are used if present. Else, p and q of SSH graph linked to the `EnergyConsumer` equipment are used.
* **Does this PR introduce a breaking change?** (What changes might users need to …
=> Fix Bug in setP0 and setQ0 of EnergyConsumer for CGMES conversion

time-series/time-series-api/src/main/java/com/powsybl/timeseries/CompressedStringDataChunk.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/StringTimeSeriesLostColumnsIssue.java
Fix bug #690 
When string compressed time series are added to time series table, time series offset in the buffer is not taken into account and consequently data are always written at first time series offset (zero).
Time series offset is now correctly used for string compressed time series like it is for string uncompressed time series.
N/A
=> Fix buffer filling issue with string compressed time series

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1Catalog.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java, triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStoreFactory.java
This PR adds a unit test to check conversion bug fixed in #685
A variant of Conformity test configuration MicroGrid has been created, using only EQ, TP and SSH files. 
In The `EnergyConsumerConversion`, `containsKey` has been used to replace `getId` when checking if a property exists.
Additionally, a `PowsyblException` is now thrown if no implementation is found for the required triple store engine, instead of returning `null`.
=> Add unit test to CGMES conversion using only EQ, TP, SSH

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModelFactory.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java, commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
Default boundary files can be specified for CGMES conversion.
Currently CGMES conversion expects boundary files to be included in the main data source received for the import.
With this change, the user can specify location of boundary files using a new parameter for the import: `iidm.import.cgmes.boundary-location`. The default value for this parameter is `PlatformConfig.defaultConfig().getConfigDir().resolve("CGMES").resolve("boundary")`, that corresponds to: `~/.itools/CGMES/boundary`.
The boundary files will be read only if the main data source of the import DOES NOT contain boundary data. A CGMES data source contains boundary data if the profiles `EquipmentBoundary` and `TopologyBoundary` are referenced in the models.
Boundary data will be read using a `GenericReadOnlyDataSource`, …
=> CGMES default boundary files

triple-store/triple-store-impl-rdf4j/pom.xml
Remove a spurious dependency to logback classic. A library should not force the user to use a specific slf4j implementation
Logback classic is put on the classpath and used (randomly) by slf4j to log. Since it has a default log level of DEBUG and is not configured because the user didn't choose it, a huge amount of log is output on the console.
The user controls the logs. For example, for a lot of unit tests we use slf4j-simple with a default log level of INFO which outputs reasonable amounts of logs
* **Does …
=> triple-store-impl-rdf4j: exclude dependency to logback-classic

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBus.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConfiguredBusImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BusTest.java
Bug fix during creation of a bus
When a bus is created, `bus.getName()` returns the value entered with `setId` in the busAdder.
When a bus is created, `bus.getName()` returns the value entered with `setName` in the busAdder if it exists, the bus ID if it does not.
No
Fixes #697
=> Fix bug in setting of bus name (issue #697)

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NodeMapping.java
* **Please check if the PR fulfills these requirements** (please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)
* **Does this PR already have an issue describing the problem ?** If so, link to this issue using `'#XXX'` and skip the rest
No
Bug fix
Some CGMES unit test throw a ConcurrentModificationException  coming from HashMap implementation because of an additional check added in JDK9. In the actual code a put(...) in done inside computeIfAbsent method which can lead to Map internal structure corruption.
see [https://stackoverflow.com/questions/54824656/since-java-9-hashmap-computeifabsen …
=> Fix ConcurrentModificationException in Java >= 9

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
Bug fix
If there is a query in the catalog for model profiles which returns non null results but there is not EQ core profile, no error is returned before trying to convert the CGMES file.
If there is a query in the catalog for model profiles which returns non null results but there is not EQ core profile, an explicit error is returned before trying to convert the CGMES file.
No
* …
=> hasEquipmentCore returns false when there are results for model_profiles query but no EQ core profile

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Branch.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/DefaultLimitViolationDetector.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisChecksTest.java
Fix limit violation detection based on current value
This fixes the limit violation detection based on current values (not on Branch objects).
At the same time, it adds :
- unit tests and fix current limits in eurostag example 1 network (add last current limit)
- javadoc on Overload
* **Please check if the PR fulfills these requirements** (please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)
A bug.
The current value reported in limit violations by the default violation detector is wrong, when underlying network is not consistent with the checked current value. This is an important bug, …
=> Fix limit violation detection based on current value

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CountryConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractIdentifiedObjectConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractObjectConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SubstationConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/BusesValidation.java
This change uses the country ISO codes available at boundary nodes (Connectivity or Topological nodes) in ENTSO-E extensions for CGMES when the CGMES import is configured to convert boundaries to the IIDM model.
Currently the country set in the Substations created in IIDM for the boundary nodes is a default value.
With this change, the Country for Substations related to the boundary will be set based on attributes of the CGMES nodes. The attributes `fromEndIsoCode` / `toEndIsoCode` are used to exchange the ISO code of the region to which the "From" /  "To" side of the Boundary point belongs to or it is connected to. Not enough information is present in the model to determine which "side" should be used, so the country will be assigned from the first code that can be mapped to a valid IIDM …
=> Use ISO codes available at boundary nodes in ENTSO-E extensions

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/MultiVariantObject.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VariantManagerImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
This pull-request fixes #675 : extensions should be able to handle variants properly
IIDM Extensions cannot handle variants.
When a variant is added, removed or cloned, we iterator over all multi-variant extensions.
The following interfaces have been moved from `powsybl-iidm-impl` to `powsybl-iidm-api`:
- MultiVariantObject
- VariantManagerHolder
The …
=> Extensions should be able to handle variants properly

iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportersTest.java
Small fix for a test added in #653.
Since `ArrayList` is not thread safe, the test `importAll` sometimes fails.
With `Collections.synchronizedList` there should not be a problem anymore.
No.
=> Make ImportersTest.importAllParallel thread-safe (small correction)

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CurrentLimitsMapping.java
Add a feature: make the CGMES importer resilient to bad current limits
When current limits without permanent limit (PATL) exist, they are imported causing an error while trying to pass a loadflow.
Now, current limits are ignored when there is no PATL exported.
No.
=> Ignore current limit if there is no PATL

commons/src/main/java/com/powsybl/commons/extensions/ExtensionProviders.java, commons/src/main/java/com/powsybl/commons/json/JsonUtil.java, commons/src/test/java/com/powsybl/commons/extensions/BarExtSerializer.java, commons/src/test/java/com/powsybl/commons/extensions/ExtensionTest.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java
Features to prepare JSON conversion
N/A
- `ExtensionProvider` can be created with a set of extensions' names as filter
- `JsonUtil.writeExtensions` returns a set of not found extensions
- small correction in `XMLExporter`
No, some methods which didn't return anything now return something but it shouldn't break anything.
=> Small modifications to prepare for JSON conversion

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TopologyVisitor.java
In the PR #673, we add a new method to the interface TopologyVisitor that breaks the API compatibility.
This PR add a default behavior to the TopologyVisitor interface to avoid API breaks
The compilation breaks
The compilation success
**Does this PR introduce a breaking change?** *(What changes …
=> Fix TopologyVisitor implementation: add a default behavior to visitBattery

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryImpl.java
No
Bug fix
p0 and q0 are not dependent on the variant for BatteryImpl as specified by the documentation
p0 and q0 are dependent on the variant
No
=> make p0 and q0 dependent of the variant for Batteries

iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java, iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportersTest.java
Feature
When no importer is found while trying to load a network, `null` is returned.
When no importer is found while trying to load a network, an exception indicating that either the file format is unsupported or the file is invalid is thrown.
**Does this PR introduce a breaking change?**
Not really a breaking change but the exception must be handled in some ways when using `Importers.loadNetwork` if you don't want it to be thrown.
=> Throw an explicit exception when the loadNetwork methods do not find any appropriate importer

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
Fixes #756 
**Other information:**
The "new" behaviour of `Networks.printBalanceSummary(String, Network, Logger)` is not exactly the same as before but it is quite equivalent.
=> PrintBalanceSummary with a Writer as parameter (the other is deprecated)

contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingenciesProviderFactory.java
API fix.
The generic return type in `ContingenciesProviderFactory` does not seem to bring anything really useful,
while on the other side it prevents (or makes clumsy) the use of most
fluent APIS which rely on a known return type (streams, optionals ...).
It also causes "unchecked" warnings in implementations.
It seems very unlikely that this change actually breaks some client code.
**What is the new behavior (if this is a feature …
=> Remove generics from ContingenciesProviderFactory interface.

math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java, math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java, math/src/test/java/com/powsybl/math/matrix/SparseMatrixTest.java
No
Bug fix
Iteration over non zero of sparse matrice is wrong when it contains an empty column.
Iteration over non zero of sparse matrice is correct when it contains an empty column. …
=> Fix issue with empty column in sparse matrix

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisResultBuilder.java
Feature.
The result builder subclasses cannot access the underlying running context, which prevents them to add some implementation specific behaviour (adding specific "notifications" to interceptors).
The result builder subclasses may access the running context through the protected getter.
=> Security analysis result builder: allow access to underlying context

cgmes/cgmes-conformity/pom.xml, pom.xml, triple-store/triple-store-impl-jena/pom.xml
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
Bug fix / regression.
Install powsybl-core through an execution of `install.sh`, and run the command `itools` with a `config.xml` file as the source of configuration.
The command should issues a `NoClassDefFoundError` exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
```
The command correctly reads the XML configuration.
The jar `xercesImpl-2.11.0.jar` was introduced by the Jena implementation of the triple store.
That jar uses the class `org/w3c/dom/ElementTraversal` …
=> Fix regression : XML platform config does not work anymore

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/GeneratorAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ValidationUtil.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BatteryTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/GeneratorTest.java
No
update the checks done on the power values associated with the Generator objects
The PR : https://github.com/powsybl/powsybl-core/pull/817
introduced a some tests that are not valid for a generator : minP <= targetP <= maxP.
the targetP value can be outside of this bounds
targetP is allowed to …
=> Fix checks for generator

pom.xml
#816 
upgrade mapdb from 3.0.3 to 3.0.6 : http://www.mapdb.org/changelog/
This doesn't introduce many changes except for bugfixes and the guava dependency range improvement.
If you forget to choose a version for guava in your dependencyManagement (or other more complicated means of choosing, such as using exclusions), then when you make a maven project …
=> upgrade to mapdb 3.0.6. This removes the bounded [,19.20) guava dependency

iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/TerminalMockExt.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TerminalRefXml.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadZipModelXmlSerializer.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TerminalMockXmlSerializer.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterExporterBaseExtensionsTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterBaseExtensionsTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterBaseOneExtensionPerFileTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterImporterBaseOneExtensionPerFileTest.java, iidm/iidm-xml-converter/src/test/resources/eurostag-tutorial-example1-terminalMock.xml, iidm/iidm-xml-converter/src/test/resources/eurostag-tutorial-example1-with-terminalMock-ext.xml, iidm/iidm-xml-converter/src/test/resources/xsd/terminalMock.xsd
Feature
Terminals don't have the writer passed as a parameter and thus, can only be written in the main XIIDM file.
A writer can be passed as a parameter and allows terminals to be written in other files than in the main XIIDM file. This is useful when they are written in extensions and that we are in `ONE_EXTENSION_PER_FILE` mode for example.
No
=> TerminalRefXml with writer param

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RatioTapChangerConversion.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
Improvement CGMES import
For RTC and PTC, CGMES `ltcFlag` attribute is never considered.
For RTC, `loadTapChangingCapabilities` is set from CGMES `ltcFlag` attribute.
For PTC, if CGMES `ltcFlag` attribute is set to `false`, the PTC is `FIXED_TAP`.
No.
=> Take ltcFlag into account during conversion

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
Bug fix
Even when it is possible (when the tap changer is not regulating and/or when the tap changer is fixed), a null regulation terminal cannot be set on a `RatioTapChangerImpl` or `PhaseTapChangerImpl` object whereas it is **allowed** in these conditions in adders.
It is allowed to set a null regulation terminal on a tap changer if the latter is not regulating and/or it is fixed. …
=> Does not automatically throw an exception when setting a null regulation terminal for a tap changer

iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/BatteryNetworkFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/DanglingLineNetworkFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/FictitiousSwitchFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/HvdcTestNetwork.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/MultipleExtensionsTestNetworkFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/NetworkTest1Factory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/NoEquipmentNetworkFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/PhaseShifterTestCaseFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/ReactiveLimitsTestNetworkFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/SvcTestCaseFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/ThreeWindingsTransformerNetworkFactory.java
No
Feature
iidm-test module contains numbers of test network, mainly used for unit testing. In a recent PR (#814), we have changed import API to allow an alternative network factory. There is no way with actual code to use test network with an alternative network factory.
**What is …
=> Allow test networks to be created using an alternative network factory

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CalculatedBusImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MainConnectedComponentWithSwitchTest.java
#490 
When a `CalculatedBus` is empty (i.e. contains no NodeTerminal), we traverse the graph to try finding a NodeTerminal connected to this bus. We use this NodeTerminal to retrieve voltage, angle, connected and synchronous component number
When a `CalculatedBus` is empty, it's impossible to retrieve voltage, angle connected and synchronous component …
=> Find a NodeTerminal for empty CalculatedBus

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CalculatedBusImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/EmptyCalculatedBusBugTest.java
N/A
Bug fix
If a Node/Breaker voltage level contains internal connections, a NullPointerException can be thrown when we try to get a Bus. The bug appears only if the CalculatedBusImpl doesn't contain a NodeTerminal.
The bug is fixed …
=> Fix traverser in CalculatedBusImpl to handle properly internal connections

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMapping.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/PhaseTapChangerAdder.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/RatioTapChangerAdder.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TapChanger.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TapChangerTest.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/PhaseShifterTestCaseFactory.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java, iidm/iidm-xml-converter/src/main/resources/xsd/iidm.xsd, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/PhaseShifterXmlTest.java, iidm/iidm-xml-converter/src/test/resources/phaseShifterRoundTripRef.xml
New feature: introduction of an optional attribute  `targetDeadband` for tap changers. It corresponds to the deadband used with discrete control to avoid excessive update of controls while regulating.
The  XML schema for IIDM has been updated: ratio tap changers and phase tap changers have now an optional attribute `targetDeadband`. 
This attribute is only considered for IIDM networks and CGMES networks. AMPL and UCTE networks do not consider this `targetDeadband`. …
=> Add targetDeadband for IIDM tap changers

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DefaultNetworkListener.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkListener.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkListenerList.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VariantManagerImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/LoadTest.java
No
New feature added into NetworkListener to notify changes with variant index
The feature does not exist
A new method is available into NetworkListener in order to notify variant changes.
Only applied on file LoadImpl.java …
=> Add change notification for variant on LoadImpl

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractIdentifiableXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/PropertiesXml.java, iidm/iidm-xml-converter/src/main/resources/xsd/iidm.xsd, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/PropertiesXmlTest.java, iidm/iidm-xml-converter/src/test/resources/eurostag-tutorial-example1-properties.xml
This PR is link to this [topic](https://spectrum.chat/powsybl/issues/properties-to-a-network~f964caca-2a63-457d-9798-66f16c4c341a)
Bug fix?
If a network has properties, when exporting to XML, these properties are lost.
The properties are read/write by the XML formatter. …
=> Export Network properties in XML

iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControl.java
N/A
Arguable
When inheriting the `ActivePowerControl` class, when calling `super()`, compilation fails because there is an ambiguity between two constructors:
```
public ActivePowerControl(Generator, boolean, float);
protected ActivePowerControl(Injection, boolean, float);
```
In the derived class, we need to explicitly cast the injection instance to a …
=> Change the visibility of ActivePowerControl constructor to solve ambiguity

itools-packager/pom.xml
N/A
This PR fix a compilation issue in itools-packager module, with some environments
Sometimes the compilation failed with the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.6.0:descriptor (default-descriptor) on project powsybl-itools-packager-maven-plugin: Error extracting plugin descriptor: 'No mojo …
```
=> Fix maven-plugin-plugin configuration

iidm/iidm-extensions/pom.xml, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/CoordinatedReactiveControl.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/CoordinatedReactiveControlXmlSerializer.java, iidm/iidm-extensions/src/main/resources/xsd/coordinatedReactiveControl.xsd, iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/ActivePowerControlXmlTest.java, iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/CoordinatedReactiveControlTest.java, iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/CoordinatedReactiveControlXmlSerializerTest.java, iidm/iidm-extensions/src/test/resources/coordinatedReactiveControl.xml
N/A
Feature
N/A
There is an extension to control coordinately the reactive power. This extension could be used in load-flows to find the reactive power setpoints of generators with the same regulating terminal.  …
=> Publish CoordinatedReactiveControl extension

commons/src/main/java/com/powsybl/commons/xml/XmlUtil.java, commons/src/test/java/com/powsybl/commons/xml/XmlUtilTest.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/EntsoeAreaXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
No
2 bug fixes
In case of multiple IIDM extensions for one equipment, XML reader has an issue.
For instance with the following iidm xml sample:
```xml
<extension id="G1">
<foo />
<bar />        
</extension>
```
If xml serializer is missing (not found in the classpath) for extension foo, …
=> Fix IIDM extensions read bug in case of partial missing xml serializer

distribution-core/pom.xml, pom.xml
Remove dependency convergence rule for maven enforcer to reduce verbosity of logs
7000 out of the 12000 lines of logs of a build are trees of dependency conflicts
no dependency convergence checks. No logs but also no checks.
No …
=>  pom.xml: move enforcer's dependencyConvergence from top pom to distribution-core pom.

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RatioTapChangerConversion.java, cgmes/cgmes-conversion/src/test/resources/cim14/7buses.xiidm
Bug fix
`rho` and `alpha` of phase tap changers are imported from CGMES files respecting the CGMES convention where `rho = ratedU1/ratedU2` and `angle1 = angle2 + alpha` when the phase tap changer is side 1. 
`rho` and `alpha` of phase tap changers are imported from CGMES files respecting the IIDM convention which is the contrary of the CGMES convention.
**Other information:**
It also fixes #880
=> Correct CGMES import of PTC

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BusTerminalTest.java
N/A
Bug fix
If you set the connectable bus of a terminal through its BusBreakerView to an invalid bus, the terminal is in an inconsistent state after the exception is catched. It's then impossible to put it back in a valid state because the terminal is detached. A NullPointerException is thrown because voltageLevel is null.
**What is the new behavior (if …
=> Fix BusTerminal::BusBreakerView::setConnectableBus()

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java
Methods for completing results (flows) in a network and validating bus balances defined in the CGMES conversion tester are made public
=> cgmes: make public some conversion tester tools

distribution-core/pom.xml
NO
CI Bug Fix
Code Coverage isn't tracked for the following files in coveralls:
jacoco-powsybl-cgmes-conformity.exec
jacoco-powsybl-cgmes-model-alternatives.exec
jacoco-powsybl-cim-anonymiser.exec
Code coverage is tracked.
Note: the coveralls setup is as follow:
each maven module generates a .exec …
=> distribution-core: add missing modules to dependencies to get coverage report

time-series/time-series-api/pom.xml, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/BigDecimalNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/BinaryOperation.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/DefaultNodeCalcVisitor.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/DoubleNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/FloatNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/IntegerNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/MaxNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/MinNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcCloner.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcEvaluator.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcModifier.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcPrinter.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcResolver.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcSimplifier.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcVisitor.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcVisitors.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/TimeNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/TimeSeriesNameNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/TimeSeriesNames.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/TimeSeriesNumNodeCalc.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/UnaryOperation.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/NodeCalcTooManyRecursionExceptionTest.java
This is a proof of concept PR. Let's discuss. Is it the good direction ? This change is quite verbose because the visitor pattern is verbose. It adds a new method "iterate" for each NodeCalc in the visitor interface, and it adds the corresponding accept method in all the nodecalc classes (double dispatch).
Things I don't like:
- evaluated children in the visit method are given in a list that has the corresponding values as the list return by iterate. But ideally visit(BinaryOperation, ...) should receive left and right as direct arguments, and visit(UnaryOperation) should receive child as a direct argument, instead of lists of size 2 and 1 respectively. Not sure if it's doable.
Things that can be improved if this is the good direction:
- The previous implementation …
=> time-series-api: implement nonrecursive ast visitors

cgmes/cgmes-conversion/pom.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
No
Feature
CGMES `qPercent` attribute for synchronous machines is not taken into account during import.
It is taken into account
No
=> Import qPercent (coordinated reactive control) for synchronous machines

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ImportExportPerformanceTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
NO
Bug Fix
5 tests use Jimfs.newFileSystem(). This returns a FS dependent on the host OS and makes the tests non reproducible (54 uses of Jimfs.newFileSystem(Configuration.unix()))
Use Jimfs.newFileSystem(Configuration.unix())
**Does this PR …
=> Fix non reproducible tests: use jimfs in unix mode like everywhere else

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_ptc_side_2/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
=> CGMES correction: rho and alpha of PTC depend on the side where the PTC is

loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletion.java
Bug fix.
Before checking if it belongs to the main connected component, check that there is a bus for the terminal in the busView.
In certain topologies, there could be equipment connected to configured bus for which no corresponding bus has been created in the busView.
Observed analyzing IOP June data for REE bus-branch test case: shunt connected to a configured bus (24 kV) that contains no other equipment and is connected to a 1 kV bus through an out-of-service transformer.
=> In loadflow results completion, check that there is a bus in the busView 

distribution-core/pom.xml, pom.xml
Fix coverage report on sonarcloud
- sonar.jacoco.reportPath (merged exec) was deprecated and replaced with sonar.jacoco.reportPaths (multiple execs)
- sonar.jacoco.reportPaths (multiple execs) is deprecated and replaced with sonar.coverage.jacoco.xmlReportPaths (xml reports)
The coverage report dropped 10% after https://github.com/powsybl/powsybl-core/pull/893 .
This may be because we use a doubly deprecated jacoco-merge.exec …
=> Remove deprecated sonar conf. Try to use the default conf.

.travis.yml
it is used:
- after a merge to master. This is what allows us to have badges (and the general state of master)
- in short lived branches. This is not used much because the PR view is nicer (it gives a 'diff'), but could be useful.
No
Bug fix
The badge on https://github.com/powsybl/powsybl-core is no longer updated
badge updated …
=> travis: restore sonar on push events

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcConverterStation.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcLine.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStation.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/LccTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VscTest.java
N/A
Feature
It's impossible to easily retrieve the HVDC line from the converter station
It's now possible thanks to a new getter. …
=> Add methods to retrieve the HVDCLine from the converter stations

math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java, math/src/test/java/com/powsybl/math/matrix/SparseMatrixTest.java, pom.xml
N/A
Feature
MacOS is not supported by powsybl-math (SparseMatrix)
MacOS is now supported by powsybl-math (SparseMatrix) and it still work on Linux and Windows
(if any of the …
=> Update powsybl-math-native version to 1.0.1 (MacOS support)

iidm/iidm-extensions/pom.xml
No.
Fix an oversight: automatic module name of iidm-extensions is added
No
=> Add automatic module name in iidm-extensions

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TopologyTester.java, iidm/iidm-api/src/main/groovy/com/powsybl/iidm/network/IdentifiableExtension.groovy, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java, iidm/iidm-impl/src/test/groovy/com/powsybl/iidm/network/impl/IdentifiableExtensionGroovyTest.groovy, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/PropertiesXml.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java, loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/ShuntCompensatorsValidationTest.java, ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java, ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
No
Change access to properties fields of Identifiable class
Identifiable.getProperties is used to set new properties
Identifiable.getProperties method is no longer accessible, replaced by getProperty & setProperty …
=> Replace Identifiable.getProperties by getProperty & setProperty

iidm/iidm-api/src/main/groovy/com/powsybl/iidm/network/IdentifiableExtension.groovy, iidm/iidm-impl/src/test/groovy/com/powsybl/iidm/network/impl/IdentifiableExtensionGroovyTest.groovy
No
A regression fix in PR #911
It is not possible anymore to set a non `java.lang.String` property using Groovy syntax:
```groovy
s.ok = true
```
It only works with `java.lang.String`
It works for any Java type.
**Does this …
=> Fix IIDM Groovy property access

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
N/A
Refactoring
The setProperty method return an `Object` as `java.util.properties` did
The setProperty method now return an `String`
(if any of the questions/checkboxes don't …
=> Fix setProperty return type

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/tools/SecurityAnalysisTool.java
Bug fix.
Security analysis uses short time computation manager, while sub-tasks use the long time computation manager. This is a regression introduced with security analysis preprocessors feature.
The tool now uses the correct computation manager again.
=> Regression fix : long task computation manager is used for security analysis sub-tasks

config-classic/src/main/java/com/powsybl/config/classic/ClassicPlatformConfigProvider.java, config-classic/src/test/java/com/powsybl/config/classic/ClassicPlatformConfigProviderTest.java
Add tests for other edge cases
The empty string used to mean the current working directory. It is error prone for 2 reasons:
- if you decide to add another config dir before the working directory, your string becomes "other:" but this is parsed as just other.
Note that ":other" would have parsed as current directory and then other.
- some users might want to remove a property by setting it to the empty string, expecting the default to be used
To use the current working directory, you now have to use "." which removes all the surprising cases described before
**Does this PR already have an …
=> ClassicPlatformConfigProvider: use user.home when powsybl-config-dir is the empty string. 

distribution-core/pom.xml, pom.xml
#940
Here's how it behaves:
$ mvn package # runs the checks like before
$ mvn package -P'!checks' # doesn't run the checks like before
$ mvn package -Dpowsyblchecks=false # doesn't run the checks
$ mvn package -Dpowsyblchecks=AnythingForExampleTrue # runs the checks
We don't have to use the 2 new forms using -Dpowsyblchecks. Using properties instead of specifying the profiles directly generally allows more flexibility (like activate a profile if A and B, or allow to …
=> pom.xml: restore checks on java11 normal maven executions

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NodeBreakerTest.java
No
Bug fix
There are several issues with calculated bus branch topology from a node breaker network:
- `connectableBus` of an injection can be `null` (which is **contrary** to specification)
- for an unconnected injection, `connectableBus` depends on the swiches' traversing order in a voltage level since it is reinitialized at each iteration in switch even if a `connectableBus` is found
- for an unconnected …
=> Bug fix in getConnectableBus() in calculated BBranch topology from NB network

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBus.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/MergedBus.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BusTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/CalculatedTopologyTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
No
Adding following method into Identifiable interface:
Network getNetwork()
Identifiable interface do not offer getter on Network used
Identifiable interface offer getter on Network used …
=> Implementation of Identifiable::getNetwork()

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkListener.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkListenerList.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SubstationTest.java
No
Change container changes notification
Container notification use NetworkListener::onUpdate method with following parameters: old container content copy and new container 
Adding new notifications methods in NetworkListener:
onElementAdded …
=> Adding container notification implementation

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RatioTapChangerConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java
Bug fix
RTC in three windings transformers is considered at side two of the leg (star bus side)
RTC in three windings transformers is considered at side one of the leg (network bus side)
**Other …
=> RTC always at side one in three windings transformers

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java
Bug fix
There is an error in conversion (formulas) of inductive and capacitive ratings of a SVC in CGMES into bMin and bMax in IIDM.
No
=> Correct SVC import from CGMES

computation/src/main/java/com/powsybl/computation/ComputationExceptionBuilder.java, computation/src/test/java/com/powsybl/computation/ComputationExceptionBuilderTest.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
feature
Only `Path` could be added into `ComputationException`
`Byte[]` could be also added into ComputationException.
(if any …
=> Add bytes into ComputationException

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/HvdcLineXml.java
No
This PR fix an anonymization bug when IIDM network contains an HVDC line
Converter stations on side 1 and 2 of HVDC lines are not anonymized. So network is not consistent anymore because converter stations have been anonymized but not link to converter station in HVDC line. 
**What …
=> Fix HVDC line XML export anonymization bug

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/TerminalMapping.java
Bit of bug fix and feature.
When searching for a CGMES terminal without connected equipment (not imported in IIDM), we take the first terminal associated to its topological node, connected or not, if it exists else we take null.
When searching for a CGMES terminal without connected equipment (not imported in IIDM), we take the first **connected** …
=> CGMES remote regulating terminal is connected if a connected terminal exists on the topological node

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
Change the R and X reference values to import a line as a low impedance line.
Signed-off-by: Anne Tilloy <atilloy@gmail.com>
No. The R and X reference values used in the CGMES conversion where set to 0.05. These values are to high and should be closer to zero, but not set to zero. The aim of low impedance line is to "aggregate" 2 terminals and to consider that there have the same values of voltage and tension. This was not the case with 0.05.
**What kind of change does this PR introduce?** *(Bug fix, feature, docs …
=> Change the R and X reference values to import a line as a low impedance line

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/IssuesTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/NetworkMapping.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/TestIssues.java
Bug fix in Network comparison used inside cgmes conversion tests. 
Regulating terminals may not have a bus (regulation is defined and active but terminal is disconnected). Comparing the buses from generators regulating terminals expected that buses always exists. 
Comparison has been fixed to consider two Identifiables equivalent if both are null.
=> Network comparison: two Identifiables are equivalent if both are null

distribution-core/pom.xml, iidm/iidm-mergingview/pom.xml, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingNetworkListener.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewIndex.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/SubstationAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/SubstationAdderAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ValidationUtil.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdderAdapter.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/MergingNetworkTest.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/SubstationAdapterTest.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/SubstationExtensionTest.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/TestUtil.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/VoltageLevelTest.java, iidm/pom.xml
No
Implementation of new module : IIDM Merging View
Merging network is destructive.
The Merging View is a class that encapsulates one or more IIDM networks to form one unique model.
The Merging View is implementation of the Network API. The …
=> No destructive merging network implementation

distribution-core/pom.xml, triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreRDF4J.java
Bug fix
- `rdf4j` and the other triplestore implementations do not have an iso behaviour with duplicate `rdf:ID`
- via the powsybl distribution generated by distribution-core, only `rdf4j` implementation can be used
The points above are corrected.
=> Ignore duplicate rdf:ID with rdf4j + all triplestore impl are in runtime scope in distribution-core

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RatioTapChangerConversion.java
fix #1004.
The log message about ratio tap changer being moved only applies to two windings transformers. 
If the transformer related to the ratio tap changer is a three windings transformer the log message does not apply.
=> fix #1004; log message only should be shown for two windings transformer

afs/afs-ext-base/pom.xml, entsoe-util/pom.xml, ucte/ucte-converter/pom.xml
After this change, jimfs is no longer included in distribution-core
Note that in config-test, jimfs is still scope compile because it's not used
for the tests of the project, but for the project itself.
NO
Bug fix
jimfs is included in distribution-core
**What is the new behavior (if this is a feature …
=> afs-ext-base, enstoe-util: fix missing scope=test for jimfs

iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/CoordinatedReactiveControlXmlSerializer.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/TwoWindingsTransformerPhaseAngleClockXmlSerializer.java
Refactoring of `CoordinatedReactiveControlXmlSerializer`, `TwoWindingsTransformerPhaseAngleClockXmlSerializer` and `ThreeWindingsTransformerPhaseAngleClockXmlSerializer` by using `AbstractExtensionXmlSerializer`
=> Refactoring of XML extensions

afs/afs-mapdb-storage/pom.xml, afs/afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java, afs/afs-mapdb-storage/src/test/java/com/powsybl/afs/mapdb/storage/MapDbAppStorageTest.java, afs/afs-storage-api/pom.xml, afs/afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorage.java, afs/afs-storage-api/src/main/java/com/powsybl/afs/storage/DefaultListenableAppStorage.java, afs/afs-storage-api/src/main/java/com/powsybl/afs/storage/ForwardingAppStorage.java, afs/afs-storage-api/src/main/java/com/powsybl/afs/storage/events/NodeMetadataUpdated.java, afs/afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java, afs/afs-ws/afs-ws-server/pom.xml, afs/afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java, afs/afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/RemoteAppStorage.java
Signed-off-by: Paul Bui-Quang <paul.buiquang@rte-france.com>
feature
Once a node is created, its metadata can't be updated
Node's metadata can be updated
This has been added to reuse the generic metadata already implemented concepts in order to implement features like file tagging, or executions dates history, ...
=> Add setMetadata to AppStorage interface

ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java, ucte/ucte-converter/src/test/resources/lastCharacterIssue.uct, ucte/ucte-network/src/main/java/com/powsybl/ucte/network/io/UcteRecordParser.java
No
Bug fix
Currently, when a line is filled by empty space except last character in a UCTE file, an exception is thrown at file import.
No more exception thrown.
=> Fix a bug during UCTE import when it only lacked the final character of a node line

entsoe-util/src/main/java/com/powsybl/entsoe/util/EntsoeArea.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/EntsoeAreaXmlSerializer.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/MergedXnode.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/MergedXnodeXmlSerializer.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/Xnode.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/XnodeXmlSerializer.java
- [X ] The commit message follows our guidelines
N/A
Refactor the ENTSO-E extension to use correctly the base class. Fix an issue in XML serializer also.
The extendable is stored twice for entso-e extensions
The writer used during XML serialization is not the good one if we want to export them in a separate file.
**What is the new behavior (if this is a …
=> Ext writer

dsl/pom.xml
"docs update"
missing license to dsl/pom.xml
license added. the file dates from 2018 Sylvain Leclerc an RTE employee assigning copyright to RTE
=> Add missing license to dsl/pom.xml

iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingNetworkListener.java
No
Remove a lot of stacktrace printing from mergingview tests logs
A lot of stacktrace is printed during mergingview tests logs
All stacktrace are removed from mergingview tests logs
**Does this PR introduce a breaking change or deprecate an API?** *If …
=> Merging view : remove useless stacktrace

action/action-util/src/main/java/com/powsybl/action/util/ProportionalScalable.java, action/action-util/src/test/java/com/powsybl/action/util/ScalableTest.java
Bug fix
Currently, iterative scaling algorithm on proportional scalable does not work as expected and can even throw assertion errors or consider non saturated scalables as saturated
Iterative scaling algorithm works as expected
=> Fix two issues in iterative proportional scalable scaling algorithm.

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractObjectConversion.java
No.
Bug fix
`fromContinuous` method truncates float value (from SSH or SV files) to int during CGMES import.
`fromContinuous` method rounds float value (from SSH or SV files) to int during CGMES import.
No
=> fromContinuous method rounds value (from SSH or SV) in CGMES import

commons/src/main/java/com/powsybl/commons/extensions/ExtensionProviders.java
NO
Bug Fix
Other constructors all require that the clazz argument is not null, but ExtensionProviders(clazz) doesn't
add missing requireNotNull
NO
=> ExtensionProviders, add missing requireNonNull

iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/export/ExportOptions.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractConnectableXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractIdentifiableXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractNetworkXmlContext.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/DanglingLineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/IidmXmlConstants.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/IidmXmlVersion.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlReaderContext.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlWriterContext.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NodeBreakerViewInternalConnectionXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/PropertiesXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ReactiveLimitsXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/StaticVarCompensatorXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TerminalRefXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TwoWindingsTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/AbstractXmlConverterTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/StaticVarCompensatorXmlTest.java
No
Feature
IIDM-XML files can only be written in current IIDM-XML version (i.e. 1.1)
IIDM-XML files can now be written in current and previous IIDM-XML versions (i.e. 1.0 and 1.1)
No
**Other information:**
:warning: Network extensions **cannot** for the moment be written in previous versions, it will be implemented in another PR
=> Allow to write IIDM-XML files in previous versions

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-tck/src/main/java/com/powsybl/iidm/network/tck/AbstractEmptyCalculatedBusBugTest.java
No
Bug fix
InternalConnectionAdder inherit from IdentifiableAdder while InternalConnection does not inherit from Identifiable.
InternalConnectionAdder does not inherit IdentifiableAdder anymore …
=> InternalConnectionAdder should not inherit from IdentifiableAdder

.gitignore, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SvInjectionConversion.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModelFactory.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
An equipment may belong to different voltage levels depending on the node used to find its container. Using the equipment `Terminal` node-breaker information (`ConnectivityNode`) we may find a voltage level different than the one found using bus-branch information (`TopologicalNode`).
When querying the CGMES model for the container of a given terminal, the client must specify the …
=> Obtain voltage level from terminal through node-breaker or bus-branch node

ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteElementId.java
N/A
Bug fix
0 is not allowed as an order code since #1128. Before this commit, 0 was allowed but a warning was displayed because it's valid regarding the UCTE-DEF format specification.
We now follow the ENTSO-E rules defined in [150420_quality_of_datasets_and_calculations_3rd_edition.pdf](https://docstore.entsoe.eu/Documents/Publications/SOC/Continental_Euro …
=> Fix Ucte element order code rule

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java
No
Bug fix
Equipment container for switch is required to decide if switch should be converted to a low impedance line during CGMES conversion. If equipment container referenced object does not exist in the CGMES model a null pointer exception is raised.
Switches are converted to low impedance lines when …
=> Handle switches missing equipment container in CGMES conversion

loadflow/loadflow-scripting/pom.xml
N/A
Plugin configuration
The loadflow-scripting module contains only groovy code, so the maven-javadoc-plugin doesn't generate a javadoc jar, required by sonatype.
We fix this in a previous PR, but the documentation was not clear enough and I set two useless properties.
The two properties have been …
=> Remove useless properties

commons/src/main/java/com/powsybl/commons/extensions/AbstractExtendable.java, commons/src/main/java/com/powsybl/commons/extensions/AbstractExtensionAdder.java, commons/src/main/java/com/powsybl/commons/extensions/Extendable.java, commons/src/main/java/com/powsybl/commons/extensions/ExtensionAdder.java, commons/src/main/java/com/powsybl/commons/extensions/ExtensionAdderProvider.java, commons/src/main/java/com/powsybl/commons/extensions/ExtensionAdderProviders.java, commons/src/test/java/com/powsybl/commons/extensions/ExtensionAdderProvidersTest.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractIdentifiableAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java
#828
Feature
It's not possible to have multiple implementations of an extension
it is possible to have multiple implementations of an extension
NO …
=> Allow to have different implementations of extensions

iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/AbstractXmlConverterTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/OptionalLoadTypeBugTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SimpleAnonymizerTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/StaticVarCompensatorXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TopologyLevelTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLExporterTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterExporterBaseExtensionsTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterLimitsTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterBaseExtensionsTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterBaseOneExtensionPerFileTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterImporterBaseOneExtensionPerFileTest.java
No
Feature: implement a new method that generates an input stream from a test resource XIIDM file
No
=> add AbstractXmlConverterTest.getVersionedNetworkAsStream method in test

iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/AbstractXmlConverterTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/BatteryXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/EurostagXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/FictitiousSwitchTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/HvdcXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NodeBreakerInternalConnectionsTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/PhaseShifterXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ReactiveLimitsXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SimpleAnonymizerTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/StaticVarCompensatorXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TopologyLevelTest.java
No
Feature: add an util method to retrieve as a string the path of a versioned network in the test resources.
No
=> Add AbstractXmlConverterTest.getVersionedNetworkPath method

loadflow/loadflow-scripting/pom.xml, pom.xml
N/A
Bug fix
The groovydoc jar generated by gmaven-plus is not attached as a javadoc jar. The checks on the staging repository fail and it's impossible to publish a new release.
The groovydoc is not attach using gmaven-plus but we use the build-helper plugin instead. Closing the staging repository …
=> Fix groovydoc attachment in powsybl-loadflow-scripting

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformerAdder.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TwoWindingsTransformer.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TwoWindingsTransformerAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerImpl.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdderAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdderAdapter.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdapterTest.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdapterTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTwoWindingsTransformerTest.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TwoWindingsTransformerXml.java, iidm/iidm-xml-converter/src/main/resources/xsd/iidm_V1_2.xsd, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXmlTest.java, iidm/iidm-xml-converter/src/test/resources/V1_2/completeThreeWindingsTransformerRoundTripRef.xml
=> Add apparent power attribute (ratedS) on transformers in IIDM

iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/AbstractOptions.java, iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/export/ExportOptions.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SkipExtensionTest.java, iidm/iidm-xml-converter/src/test/resources/V1_0/noExtension.xml
N/A
Bug fix
If I set the `iidm.export.xml.skip-extensions` option, without setting the `iidm.export.xml.extensions` option, all the extension are written.
As this property have been flagged `Deprecated`, I remove this property to make the code less confusing. …
=> Remove skip-extension property

computation/src/test/java/com/powsybl/computation/ThreadInterruptedCompletableFutureTest.java
#1210 
Bug fix
The compilation fails randomly on windows worker since we enable compilation in multi-thread mode. The timeout to wait for the termination of the thread is too low comparing to the load of the worker.
We increase the timeout to 5s. In the worst case, the compilation will fail after 5 …
=> Increase the timeout in ThreadInterruptedCompletableFutureTest

iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ShuntCompensatorAdapter.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/ShuntCompensatorAdapterTest.java
It comes after the ShuntCompensator new API (IIDM version 1.2).
Signed-off-by: Anne Tilloy <atilloy@gmail.com>
New API of ShuntCompensator (IIDM 1.2).
(if any of the …
=> Add methods in the shunt compensator adapter of the merging view

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractVoltageLevel.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
Bug fix
`voltageLevel.getConnectables()` and `voltageLevel.getConnectableStream()` do not check if they have duplicates in their respective returned iterable and stream.
The returned iterable and stream contain distinct elements.
No
It generated issues in voltage level with an internal transformer (for …
=> Ensure that voltageLevel.getConnectables() and associated return collections of distinct elements

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
Signed-off-by: Anne Tilloy <atilloy@gmail.com>
No, but the issue was raised during the functional validation of the merging view compared to the classical merging of IIDM networks.
The shunt admittance treatement of a line that is the result of the merging of 2 dangling lines in the classical merging of 2 IIDM networks. In details:
- Nothing change for the first half line ;
- For the second half line, only g2 and b2 are set from the …
=> Fix how to merge two dangling lines in a tie line.

sensitivity-api/pom.xml, sensitivity-api/src/main/java/com/powsybl/sensitivity/SensitivityComputation.java, sensitivity-api/src/main/java/com/powsybl/sensitivity/SensitivityComputationResults.java, sensitivity-api/src/main/java/com/powsybl/sensitivity/SensitivityComputationTool.java, sensitivity-api/src/main/java/com/powsybl/sensitivity/converter/CsvSensitivityComputationResultExporter.java, sensitivity-api/src/main/java/com/powsybl/sensitivity/converter/SensitivityComputationResultExporter.java, sensitivity-api/src/main/java/com/powsybl/sensitivity/mock/SensitivityComputationFactoryMock.java, sensitivity-api/src/test/java/com/powsybl/sensitivity/SensitivityComputationResultsTest.java, sensitivity-api/src/test/java/com/powsybl/sensitivity/SensitivityComputationToolTest.java, sensitivity-api/src/test/java/com/powsybl/sensitivity/converter/CsvSensitivityComputationResultExporterTest.java, sensitivity-api/src/test/java/com/powsybl/sensitivity/mock/SensitivityComputationFactoryMockTest.java, sensitivity-api/src/test/resources/contingency.json, sensitivity-api/src/test/resources/resultsExport.json, sensitivity-api/src/test/resources/sensitivity-results.csv
New feature: modification of the sensitivity api to make it possible to perform post-contingency sensitivity analyses based on Hades2. The HADES2 sensitivity provider used with Powsybl offers the possibility to calculate the sensitivity on a set of contingencies besides the N state. The computation is launched only once, but the solver itself modifies the matrix for each state of the network to output a full set of results. 
At the moment it is only possible to run single sensitivity analyses through Powsybl. It returns, besides its status and some stats on the computation itself, all the sensitivity values for each factor (combination of a …
=> Modify the sensitivity API to allow for post-contingency sensitivity analyses

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMapping.java
Bug fix
For CGMES regulating controls, `targetDeadband` is optional. But a value is required in IIDM.
When a CGMES regulating control is missing the `targetDeadband` attribute, its value is interpreted as zero for IIDM.
=> CGMES regulating controls: targetDeadband is optional

entsoe-util/src/main/java/com/powsybl/entsoe/util/MergedXnode.java, ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
This is a bug fix in the UCTE import/export feature.
In a mergedXnode, rdp is calculated as R1/(R1+R2).
When R1+R2 = 0, rdp is thus NaN. When converting a UCTE network to IIDM, for a mergedXnode with R (or X) = 0 on both sides, rdp is not written because NaN values are not serialized.
When importing the generated xiidm file into Powsybl, since rdp is a required attribute, a nullPointerException is raised. This also holds for xdp.
With this change, when R1+R2 = 0, rdp is set to 0 (resp. xdp). This fixes …
=> Set rdp to 0 when R1+R2 = 0 in mergedXnode (resp. xdp)

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerTest.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java, math/src/test/java/com/powsybl/math/graph/UndirectedGraphImplTest.java
No
Feature
If a node in `NodeBreakerView` does not have an attached network component, the methode `getTerminal(node)` throws an exception. 
The method `getOptionalTerminal` now exists and can return an empty Optional if there is no attached network component to a valid node.
No …
=> Add UndirectedGraph.vertexExists(node) method + NodeBreakerView.getOptionalTerminal(node)

sensitivity-api/src/main/java/com/powsybl/sensitivity/SensitivityComputationResults.java, sensitivity-api/src/test/java/com/powsybl/sensitivity/SensitivityComputationResultsTest.java
It just adds a constructor for the SensitivityComputationResults in order to avoid a breaking change in the API, caused by PR #1155.
=> Fix PR #1155 to avoid breaking change in the sensitivity results constructor

cgmes/cgmes-model/src/main/resources/CIM16.sparql
Signed-off-by: Elena Kaltakova <kaltakovae@aia.es>
Optimize performance of SPARQL query "terminals".
Query "terminals" takes a lot of time for particular GRIDS. 
Enhanced syntax allows collect required data with minimal cost.
A performance analysis has been made on the impact of the change made to the query. Test case time execution went from 26000 ms to 150 ms. Data collected by enhanced query is …
=> Optimize performance SPARQL query "terminals"

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdapter.java
Bug fix for conversion of isolated connectivity nodes in CGMES.
CGMES data contains an isolated connectivity node (no terminals attached to it, no related equipment).
Space for the connectivity node is reserved at IIDM node-breaker graph (a vertex is reserved).
During the conversion, the reserved vertex is never used (no equipment is attached to it).
After all equipment has been converted, voltages and angles from SV are put on …
=> Add nodeBreakerView.hasAttachedEquipment(node) method + Ensure an IIDM node number is valid before trying to use it in CGMES conversion

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/HvdcLineAdapterTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractHvdcLineTest.java, math/src/main/java/com/powsybl/math/matrix/SparseLUDecomposition.java
The documentation in the website will follow in the Following days.
No issue.
It adds some validations around HVDC lines in the internal model.
No check about the sign of active power setpoint, no hupper limits for powerFactor and lossFactor. These two factors are ratios (whitout units) but could be set in percents without new checks.
**What is the new …
=> Validations around HVDC lines in IIDM

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractComponentImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConnectedComponentImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SynchronousComponentImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractVscTest.java
No
Bug fix
The class ConnectedComponentImpl do not improve/override to super class ComponentImpl
Into synchronous component the bus filter used is the same as connected component
Add new abstract method into ComponentImpl in order to define the …
=> Fix SynchronousComponent buses filtering

triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/PropertyBag.java
* Related to Issue #1032
Signed-off-by: Laurent Cosson <lcosson@silicom.fr>
#1032
Performance : reduce execution time with debug log level.
Import and conversion time are too long, this is but one of the possible improvements.
Aiming for a 15% gain on conversion time in debug mode.
**Does this PR …
=> Performances - tabulate logs using a StringBuilder instead of concat()

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
Signed-off-by: Anne Tilloy <atilloy@gmail.com>
No.
The files that have a lossFactor greater than 1 are not imported.
The files that have a lossFactor greater than 1 are imported. …
=> Remove the hupper bound for Hvdc converter station lossFactor

iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/SubNetworkPredicate.java, iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/SubNetworkPredicateTest.java
No
feature
A new predicate for network reduction is added. It allows to specify a center voltage level to keep and a voltage level depth to keep around the center voltage level.
(if …
=> Add sub-network reduction predicate

iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/ReductionOptions.java
N/A
API update
ReductionOption getters and setters are not public, so not usable outside the package.
ReductionOption getters and setters are public
(if any of the …
=> Make setters in ReductionOptions public

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
No
Small fix in logs: an obsolete warning (regarding XIIDM export modes) has been deleted
No
=> Delete an obsolete warning concerning XIIDM export modes

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CurrentLimitsMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForGenerators.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractObjectConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractReactiveLimitsOwnerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RatioTapChangerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SvInjectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ThreeWindingsTransformerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/TwoWindingsTransformerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/AcDcConverterConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/DcMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractCgmesTapChangerBuilder.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TapChangerConversion.java, cgmes/cgmes-conversion/src/test/resources/logback-test.xml
Signed-off-by: Laurent Cosson <lcosson@silicom.fr>
#1032 
This PR modifies the way the Context class logs messages. Appropriate log levels are checked (enabled/disabled) and formatted messages are built when logging, not before calling the logging methods. 
Formatted strings are built first, then passed to logging methods as String parameters. Also, …
=> [PERF] Context logs : postpone String building and check log level

entsoe-util/src/main/java/com/powsybl/entsoe/util/EntsoeFileName.java, entsoe-util/src/test/java/com/powsybl/entsoe/util/EntsoeFileNameTest.java
N/A
Bug fix
The parsing of an IDCF UCTE file fails because the regex is too permissive a handle the type of the file that is a number not correctly.
The parsing works as expected. …
=> Fix EntsoeFileName to parse IDCF

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java
Signed-off-by: Elena Kaltakova <kaltakovae@aia.es>
Bug fix
cgmes.model.AbstractCgmesModel.conductingEquipmentTerminal can be overwritten.
conductingEquipmentTerminal  is checked for existence  before create a new one.
There are upcoming changes related to conductingEquipmentTerminal object handling. Pending for the next PR. 
@mathbagu Can this bug fix be also reported in release 3.3.0?
=> Fix conductingEquipmentTerminal is overwritten

loadflow/loadflow-validation/pom.xml, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationTool.java
No
feature removal
We can specify a Groovy script to apply to the IIDM network in the loadflow validation tool.
It seems this feature is not used and it add a fat dependency for nothing.
We cannot anymore apply a Groovy …
=> Remove Groovy script from loadflow validation tool

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForGenerators.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/CoordinatedReactiveControlImpl.java, iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/CoordinatedReactiveControlTest.java
Prevent regression
If qPercent has an invalid value during CGMES import, an exception is thrown.
If qPercent has an invalid value during CGMES import, the value is ignored.
No
This bug was not seen before as some regulating controls went undetected in node/breaker (cf PR #1251 )
@mathbagu This should be in release 3.3.0 as it …
=> Check on qPercent is deleted to prevent regression in CGMES import

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java
Bug fix: when CGMES regulating control is disabled, associated SVC has no voltage regulation (only reactive power regulation if it is specified).
=> Fix: when CGMES regulating control is disabled, SVC local regulation is disabled if voltage

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java
No
Bug fix
Node count attribute on voltage level is not supported in IIDM 1.2. When importing a IIDM < 1.2 we have one log in info level for each voltage level of the network. 
This is not an info nor a warning, as it is normal when importing an old format. It is not really an …
=> Replace a log info to trace for node count removal

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisImpl.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisTest.java
No
Bug fix
With `SecurityAnalysisImpl`, security analysis with an empty contingency list produces an error.
With `SecurityAnalysisImpl`, security analysis with an empty contingency list no longer produces an error: the worker count is at least at 1. …
=> Bug fix in SecurityAnalysisImpl: no error anymore when contingency list empty

iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusAdapter.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/BusAdapterTest.java
No
Feature
An exception is thrown when the user tries to retrieve lines and dangling lines connected to a bus in a merging view.
You can retrieve lines and dangling lines connected to a bus in a merging view (a merged dangling line is considered as a line). …
=> Implement getLineStream(), getLines(), getDanglingLineStream() and getDanglingLines() in BusAdapter

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
No
feature
When we copy a network the default network factory is used.
We can copy the network using an alternative network factory …
=> Network copy with a different factory

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_switchVLsOpen/MiniGridTestConfiguration_BC_EQ_v3.0.0.xml, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_switchVLsOpen/MiniGridTestConfiguration_BC_SSH_v3.0.0.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NodeMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
Bug fix
Currently switches in node-breaker CGMES models that have different voltage levels at its ends are mapped to low impedance lines. 
Only if both terminals of the switch are disconnected in CGMES the resulting low impedance line is opened.
If terminals are connected but the switch is opened, the resulting topology in IIDM leaves the low impedance line incorrectly connected, as if the switch was closed.
`BusView` …
=> Fix conversion of opened switches between voltage levels

iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewIndex.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewUtil.java
No
Refactoring
The lists returned by  `getLines()` and `getDanglingLines()` are read twice (once during the building, once during the using of the list). It is not efficient.
The list is only read when used.
No
=> Refactoring getLines(), getLineStream(), getDanglingLines(), getDanglingLineStream() in Merging View

commons/src/main/java/com/powsybl/commons/extensions/AbstractPrecontingencyValueExtension.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/extensions/VoltageExtension.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/VoltageExtensionSerializer.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/converter/ExporterTest.java, security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisResult.json
Signed-off-by: Etienne Lesot <etienne.lesot@rte-france.com>
it adds a new extension for the limitviolations with voltage contraints. It is similar to Current Extension but for voltage.
**Other …
=> add Voltage Extension class

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LinkData.java
Bug fix
`y12()`, `y21()` and `y22()` methods return `y11`
`Y12()` returns `y12`, `y21() `returns `y21` and `y22()` returns `y22`. 
**Other …
=> Fix branchAdmittanceMatrix get methods

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CurrentLimitsMapping.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/CurrentLimitsAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CurrentLimitsAdderImpl.java
No
Bug fix
Current limits are created even when the limits are apparent power or active power.
Current limits are created only when **current** TATL or PATL have been imported.
No
**Other …
=> Add hasTemporaryLimits() to CurrentLimitsAdder + correct CGMES conversion

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesNetworkCatalog.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java, cgmes/cgmes-conversion/src/test/resources/cim14/7buses.xiidm, cgmes/cgmes-conversion/src/test/resources/cim14/ieee14.xiidm, cgmes/cgmes-conversion/src/test/resources/cim14/nordic32.xiidm, cgmes/cgmes-conversion/src/test/resources/cim14/tx-from-microBE-adapted.xiidm, cgmes/cgmes-model/src/main/resources/CIM16.sparql
CGMES import was modified to set `Network.Generator.name` from CGMES `SynchronousMachine` instead of `GeneratingUnit`.
The change in the name was introduced for enhancing consistency (name of `Generator` now comes from the CGMES `IdentifiedObject` that is converted to the IIDM generator, not from a grouping element that contains it) and to have more readable names in the reference conformity test cases.
An error in CGMES conversion tests was detected, while comparing names of elements imported from CGMES test cases …
=> Names for generators from CGMES synchronous machines

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/Changelog.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/IidmChangeUpdate.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/elements16/GeneratorToSynchronousMachine.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/elements16/LineToACLineSegment.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/elements16/LoadToEnergyConsumer.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/elements16/ShuntCompensatorToShuntCompensator.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/elements16/TwoWindingsTransformerToPowerTransformer.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/update/CgmesUpdateTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/update/NetworkChanges.java
The changelog that records changes in IIDM attributes is used to perform updates in the CGMES triplestore when the user requests a CGMES export.
State variables (voltages, angles, flows at terminals) are not recorded explicitly in the changelog, as its values will be systematically obtained during the export to build the CGMES SV profile from scratch. No selective update of these attributes is required.
These attributes were previously …
=> CGMES updates: reduce size of changelog not recording state variables

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractIdentifiableXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractSwitchXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusbarSectionXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ShuntXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/StaticVarCompensatorXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java
No
Update
When a runnable is used with XIIDM util that throws an XmlStreamException, it must be catch in the `run()` method
We now use an IidmXmlRunnable which throws an XmlStreamException  …
=> Runnables in XIIDM util methods can now throw XmlStreamException

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
No
Bug fix in DL's notifications: the `oldValue` for current limits used not to be the actual previous value.
No
=> Small fix in DanglingLine's notifications

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
No
Bug fix
After a number of CGMES import we end up with:
```java
for (int i = 0; i < 1000; i++) {
Network network = Importers.loadNetwork("test.zip");
}
```
```bash
12:32:17.494 [main] DEBUG  o.e.rdf4j.sail.memory.MemoryStore - MemoryStore initialized
Exception in thread "main" …
```
=> Fix file leak in CGMES import

matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
N/A
Bug fix
When importing a Matpower network from a path, an input stream is created but never closed
Use try-with-resources to close the inputstream.
(if any of the …
=> Fix a memory leak in Matpower reader

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/LoadFlowParametersDeserializer.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/LoadFlowParametersSerializer.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowParametersTest.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/json/JsonLoadFlowParametersTest.java, loadflow/loadflow-api/src/test/resources/LoadFlowParametersError.json, loadflow/loadflow-api/src/test/resources/LoadFlowParametersVersion13.json, loadflow/loadflow-api/src/test/resources/LoadFlowParametersWithExtension.json, security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisParameters.json, security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisParametersWithExtension.json, sensitivity-api/src/test/resources/SensitivityComputationParameters.json, sensitivity-api/src/test/resources/SensitivityComputationParametersWithExtension.json
N/A
Feature
The slack bus used by a power-flow is not available from the IIDM network.
With #1381, we create a new SlackTerminal extension to define the slack bus in the IIDM model. This PR introduce two parameters for the loadflow:
- isReadSlackBus: the extension can be used by the power flow to …
=> Add a slackBus parameter to LoadFlowParameters

time-series/time-series-api/src/main/groovy/com/powsybl/timeseries/CalculatedTimeSeriesDslLoader.groovy, time-series/time-series-api/src/test/java/com/powsybl/timeseries/CalculatedTimeSeriesTest.java
#1421 
Bug fix
It's not possible to create a timeseries from groovy from a BigDecimal. User has to add the `d` suffix to its constant, that is not possible when the value is computed.
This PR introduce a new `putAt` overload to create a timeseries from a BigDecimal …
=> Allow creation of timeseries from BigDecimal

commons/src/main/java/com/powsybl/commons/xml/XmlUtil.java, commons/src/test/java/com/powsybl/commons/xml/XmlUtilTest.java
N/A
Feature
It's not possible to quickly reach a XML element without creating a whole XML parser.
This PR introduce a new `readUntilStartElement` method in the XMLUtil class to reach an XML path (`/a/b/c`). The aim of this function is to fail as quick as possible if the specified path doesn't …
=> Add utility function to quickly jump to a XML path

dynamic-simulation/dynamic-simulation-tool/src/main/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationTool.java, dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationToolTest.java
Signed-off-by: Agnès Leroy <agnes.leroy@rte-france.com>
Fix an option name in the dynamic-simulation tool: the dynamic-model-file option is renamed to dynamic-models-file.
=> Fix typo in dynamic simulation tool option

ucte/ucte-network/src/main/java/com/powsybl/ucte/network/ext/UcteNetworkExt.java
Bug fix
Current implementation of UCTE importer may merge UCTE substations in one unique substation if they are only connected by transformers.
However the ID chosen for this substation may change from a run to another due to the use of an HashMap in the importer.
The substation name generated is no longer changed from a run to another
=> Change Map implementation used in UCTE import

iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TerminalAdapter.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TopologyTraverserAdapter.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/TopologyTraverserAdapterTest.java
Linked to #1436 
Feature
`TerminalAdapter.traverse(TopologyTraverser)` is not implemented.
This method is now implemented and uses a specific `TopologyTraverserAdapter`.
**Does this PR introduce a breaking change or deprecate an …
=> Implement TopologyTraverserAdapter to traverse mergingview from TerminalAdapter

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/StaticVarCompensator.java
Bug
StackOverFlow in implementations of StaticVarCompensator that provide getVoltageSetPoint method, but not getVoltageSetpoint method
(if any of the questions/checkboxes don't …
=> Correct_default_implementation_of_getVoltageSetpoint_method_for_static_var_compensator

cgmes/cgmes-conversion/pom.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadata.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataAdder.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataAdderImpl.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataAdderImplProvider.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataImpl.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataXmlSerializer.java, cgmes/cgmes-conversion/src/main/resources/xsd/cgmesSvMetadata.xsd, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataXmlSerializerTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java, cgmes/cgmes-conversion/src/test/resources/extensions/eurostag_cgmes_sv_metadata.xml
No
Feature
CGMES SV metadata are only accessible from the CgmesModel
CGMES SV metadata can now be stored in the `CgmesSvMetadata` extension
More or less: the `CgmesSvMetadata` must be implemented in …
=> Add an extension containing SV metadata information for CGMES SV export

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MergeTest.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/NetworkTest1Factory.java
This PR adds a unit test that demonstrates the Null Pointer Exception produced in the following situation: after a Network merge, removed DanglingLines are still reachable when computing connected components.
It has been observed with real-world test cases and reproduced here with a minimal network.
It can only be reproduced under specific circumstances (memory related issue?) that are described in the related unit tests.
Bug fix
Fix made my @mathbagu, cache must be invalidated in node-breaker voltage level after an …
=> Fixed NPE observed after Network merge 

pom.xml
NO
Bug Fix
Importing powsybl-core (maven's scope=import) may lead to inconsistent logback dependencies
Importing powsybl-core (maven's scope=import) gives consistent logback dependencies
NO
**Other …
=> Add logback-core explicit dependency in dependencyManagement

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/StateVariablesAdder.java
In CGMES SV export, the name for the number of sections in service is `sections`
Previously, the name written in the export was `continuousSections` (it was the name of the property in CIM14).
=> Fix property name of shunt compensator sections in SV export

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConfiguredBusImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java
N/A
Bug fix
In several IIDM class, that implement MultiVariantObject, the super method is not called. For most of them, their first parent implementation is AbstractIdentifiable that manage the extensions.
That means, if we have an extension that supports variant for these objects, it wouldn't work properly. A similar fix has been done in #1404 but not …
=> Fix missing call to MultiVariantObject implementations

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NodeMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConnectorConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AsynchronousMachineConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergySourceConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentBranchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentShuntConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ExternalNetworkInjectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SeriesCompensatorConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/AcDcConverterConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractTransformerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/ThreeWindingsTransformerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TwoWindingsTransformerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/StateVariablesAdder.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
No
Feature
Terminals' and tap changer's IDs are lost during CGMES import
These IDs are kept as aliases
No …
=> Add aliases during CGMES import for missing IDs

entsoe-util/src/main/java/com/powsybl/entsoe/util/EntsoeFileName.java, entsoe-util/src/test/java/com/powsybl/entsoe/util/EntsoeFileNameTest.java
Signed-off-by: KAHYA Amira <amira.kahya@rte-france.com>
NO
Bug fix
NullPointerException when the geographicalCode is not null but the Country is null. This is the case when the geographicalCode is UC or UX.
Return null when the geographicalCode is not null and the Country is Null.
=> improve getCountry method to avoid nullPointerException when geographicalCode is not null and country is null

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolation.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationBuilder.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationBuilderTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationTest.java
update
there is no method to read the LimitViolations
for voltage limitViolations, builder can not be used because limitName parameter is needed 
added a method toString to print the limitviolation
added limitName in build method of voltage limitViolation 
**Does this PR introduce a breaking change …
=> Modify limit violation builder copy

contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyElementType.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/DanglingLineContingency.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/tasks/DanglingLineTripping.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/ContingencyTest.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/DanglingLineContingencyTest.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/tasks/DanglingLineTrippingTest.java, contingency/contingency-api/src/test/resources/contingency.json, contingency/contingency-dsl/src/main/groovy/com/powsybl/contingency/dsl/ContingencyDslLoader.groovy, contingency/contingency-dsl/src/test/java/com/powsybl/contingency/dsl/DanglingLineContingencyScriptTest.java
New feature
Currently, it is not possible to create a contingency that consists of a dangling line tripping. It can be found on some process (to simulate JVDC trip on UCTE files for example).
It is now possible to create a dangling line contingency using the contingency API of PowSyBl.
=> Add dangling line contingency

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java
Bug fix
When all alpha are equal to 0 in a PTC, the calculated x for non tabular PTC is undefined. 
In this case, x is equal to 0.
No
=> Prevent x of step to be undefined (NaN) during CGMES import for non tabular ptc

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
No
Bug fix: ensure that extension XML serializer is not null when `writeExtension` is called
Bug fix: filter extensions which are not in options during XML export
No
If you agree with these fixes, they should be also merged for release 3.7.0
=> Add a requireNonNull to ensure the extension XML serializer is not null when writeExtension() is called

iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewIndex.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ValidationUtil.java, iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/DanglingLineAdapterTest.java
No
Feature
If the merging view contains several networks, two of them containing a dangling line with the same ID, an exception is thrown
If the merging view contains several networks, two of them containing a dangling line with the same ID, if the ucteXnodeCode is identical, no exception is throw …
=> Accept DL limit cases in merging view (Merged line composed of two Dangling lines with same ID + non merged DL with null UcteXnodeCode)

iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LineAdderAdapter.java
No
Bug fix: nodes of a line are now correct when a new line is created in a merging view
No
I did not add tests but it will be tested once the PR changing the TCK will be merged (cf. #1510)
=> Fix bug in LineAdderAdapter (node1 used to be set twice)

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
N/A
Refactoring
The GenerationImpl class contains 4 attributes needed until the dangling is set. After that, these 4 attributes are never used.
The Generation is not passed to the command line, but after the dangling line is attached to the network and before the end of the DanglingLineAdder::add() …
=> Change the way DanglingLine::Generation is created

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/update/StateVariablesExport.java
Model description dates (`created` and `scenarioTime`) in CGMES export are always written referred to UTC time zone, per ENTSO-E exchange requirements.
The dates are written using the default formatting, that includes the local time zone offset in the output.
Dates `created` and `scenarioTime` in CGMES SV exported file are referred to UTC time zone.
See …
=> Always write model description dates referred to UTC

commons/src/main/java/com/powsybl/commons/xml/XmlWriterContext.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/EntsoeAreaXmlSerializer.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/MergedXnodeXmlSerializer.java, entsoe-util/src/main/java/com/powsybl/entsoe/util/XnodeXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlWriterContext.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/ActivePowerControlXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/CoordinatedReactiveControlXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/LoadDetailXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/TwoWindingsTransformerPhaseAngleClockXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/VoltagePerReactivePowerControlXmlSerializer.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadZipModelXmlSerializer.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TerminalMockXmlSerializer.java
No
Deprecate useless/error-prone method
Extensionwriter is a different objet than writer
Extensionwriter does not exist anymore, only writer is used
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
=> Deprecate useless extension writer in XmlWriterContext

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TerminalRefXml.java
No
Bug fix
When a terminal ref points to a bus bar section in a node breaker network, it is written when exported in a bus breaker or bus branch network
It throws an exception in this case …
=> Throw a comprehensive exception when a terminal ref of a busbar section is written in bus-breaker or bus-branch

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
No
feature
When a XIIDM is imported, and some extensions are in the file but the plugin extensions are not found, a log error is printed.
A warn log is printed instead of error, because it is not necessarily an error to not …
=> Warning instead of error log when extensions have not been found

dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/GroovyDynamicModelsSupplier.java, dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/GroovyDynamicModelSupplierTest.java
Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
It adds a new constructor taking an InputStream for the GroovyDynamicModelsSupplier so we don't need a file.
no constructor with IS
constructor with IS
=> add new constructor with inputStream for GroovyDynamicModelsSupplier

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAliasesTest.java
N/A
Feature
The IIDM implementation considers allows empty strings for alias type. Call `addAlias("alias", "")` should be equivalent to call `addAlias("alias", null)` or `addAlias("alias")`. To sum up, empty strings should be consider as null strings for alias types.
This PR change the behaviour of …
=> Fix empty alias type management

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
No
Soften too restrictive checks
An exception is thrown when RTC regulation attributes are not correctly set and the RTC is regulating
A warning is thrown when RTC regulation attributes are not correctly set and the RTC is …
=> Check on RTC regulation only throws exception if loadTapChangingCapabilities is true, else it logs a warning

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
bug fix
`NodeBreakerLevel::exportTopology` iterates over the first `graph.vertexCount` vertices of the graph.
Iteration must include all potential vertices, it must be done over `graph.vertexCapacity`. There could be "holes" in the array of vertices, the loop already was checking if the vertex was really used with `graph.vertexExists`.
=> Voltage level export : must iterate over graph vertex capacity

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java
No
Bug fix
If inconsistent voltage limit during CGMES import, an exception is thrown
If inconsistent voltage limit during CGMES import, it is ignored …
=> Fix CGMES voltage limit import: if inconsistent, ignore

psse/psse-converter/src/main/java/com/powsybl/psse/converter/TransformerConverter.java, psse/psse-converter/src/test/resources/ThreeMIB_T3W_modified.xiidm, psse/psse-converter/src/test/resources/ThreeMIB_T3W_phase.xiidm
No
feature
We cannot run a load flow with a warm start, so using voltage magnitude and angle from PSS/E file because voltage from 3 windings transformers star bus is lost. 
In OLF, we have taken as a convention to define 2 …
=> PSS/E importer: store star bus voltage in properties

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
Optimisation
Current lookup of bus by identifier in `BusBreakerView` is always done iterating through the voltage level stream of the network. As calculated buses are not included in the network index, bus/breaker buses created from node/breaker topologies have to be searched looking in every voltage level. But buses …
=> Optimise getBus in Bus/Breaker view for default Network implementation

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
In graph export for BusBreakerVoltageLevel the style for edges corresponding to open switches is dotted, consistent with dotted style for disconnected terminals.
switches open where drawn as solid edges, and closed switches as dotted.
=> Fix BusBreakerVoltageLevel export style for switch edges

cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesControlAreaImpl.java
CGMES control areas stored in the IIDM extension used linked hash sets to store terminals and boundaries to have predictable iteration order.
XML serialization of the extension was writing boundaries in different order when created from CGMES or read from previous XIIDM file.
serialization order of terminals and boundaries is always the same.
=> CGMES control areas extension: use linked hash sets to have predictable iteration order

cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingXmlSerializer.java
the loop for the serialization of the mapping between IIDM buses and CGMES topological nodes must be done over all the BusView buses, not the BusBreakerView buses.
There is an issue with current behavior, using BusBreakerView buses, if the following conditions are met:
* In a node/breaker voltage level, a `BusView` bus contains two `BusBreakerView` buses.
* The two `BusBreakerView` buses are separated by a retained switch. It may come, for …
=> CGMES - IIDM mapping: serialization loop must be done over BusView buses

ucte/ucte-network/src/main/java/com/powsybl/ucte/network/ext/UcteNetworkExt.java
Signed-off-by: Florian Dupuy <florian.dupuy@rte-france.com>
No
Bug fix
When importing a UCTE file, the voltage levels are imported in a random order
When importing a UCTE file, the voltage levels are imported in the order of their voltage level code …
=> Correct randomness of voltage level import order in UCTE import

action/action-util/src/main/java/com/powsybl/action/util/GeneratorScalable.java, action/action-util/src/main/java/com/powsybl/action/util/LoadScalable.java, action/action-util/src/test/java/com/powsybl/action/util/GeneratorScalableTest.java, action/action-util/src/test/java/com/powsybl/action/util/LoadScalableTest.java
Signed-off-by: Sebastien Murgey <sebastien.murgey@rte-france.com>
No
Feature
Current behaviour of the Scalable.scale() method is that if initial setpoint of a device is not included in a block's min/max interval, an exception is thrown.
Now, no scale is applied on the given block, and a log is …
=> Replace an exception thrown in Scalable.scale() by an error log

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_fixed_minP_maxP/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractReactiveLimitsOwnerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ExternalNetworkInjectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
No
Add CGMES file check/correction during import
When minP/maxP are faulty for a generatingUnit in CGMES file, an exception is thrown
When minP/maxP are faulty for a generatingUnit in CGMES file, the values are fixed (`minP = …
=> Check minP <= maxP during the CGMES import

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_eqbranch/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_eqbranch_at_boundary/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentBranchConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
Feature
Supported objects at boundaries are only ACLineSegment and Switches. 
Allow Equivalent Branches with one end at boundary. They will be mapped to an IIDM dangling line if an individual grid model is being loaded.
Observed in some real-world models.
=> CGMES: add support for Equivalent Branches at boundaries

README.md
N/A
Doc update
The badge to coveralls report is not displayed correctly
As we do not use coveralls anymore, we can safely delete the badge
(if any of the questions/checkboxes …
=> Remove old coveralls badge

action/action-util/src/main/java/com/powsybl/action/util/DanglingLineScalable.java, action/action-util/src/main/java/com/powsybl/action/util/Scalable.java, action/action-util/src/test/java/com/powsybl/action/util/DanglingLineScalableTest.java
No
Feature: when creating a dangling line scalable, the user can specify the scaling convention used
The scaling convention is always GENERATOR
The scaling convention can be LOAD or GENERATOR …
=> Add the possibility to specify the scaling convention when creating dangling line scalables

contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java, contingency/contingency-api/src/test/resources/contingency.json
No
Bug fix
2 new values have been added to `ContingencyElementType` but are not supported in json deserializer.
There are now taken into account. …
=> Fix contingency element deserializer

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
See original issue on powsybl-open-loadflow https://github.com/powsybl/powsybl-open-loadflow/issues/296 .
Perf improvement (in most cases)
When using method `Bus getBus(String busId)` of the network bus and bus-breaker views, a linear search is performed through voltages levels.
This is very, very, inefficient as soon as you start using the method multiple …
=> Add a bus cache to network implementation

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BoundaryLine.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
No
Add a determined order when creating boundary lines
No
=> When importing a CGM, boundary lines are orientated so that side1 ID < side2 ID

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/LoadFlowParametersSerializer.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowParametersTest.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/json/JsonLoadFlowParametersTest.java
I have renamed the setter from `getDcUseTransformerRatio` to `isDcUseTransformerRatio`. Small changes also after integrating the previous PR (#1724) to our Hades2 simulator.
(if …
=> Fix new three parameters of LoadFlowParameters

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
Fix CGMES export for node/breaker networks when no mapping between IIDM buses and CGMES Topological Nodes has been created and stored during CGMES import.
Current export throws a Null Pointer Exception for node/breaker voltage levels when building the mapping between IIDM BusView buses and CGMES Topological Nodes. 
The problem is fixed and a default mapping between IIDM BusView …
=> Fix CGMES export node/breaker when building bus-TN mapping

commons/src/main/java/com/powsybl/commons/io/WorkingDirectory.java, commons/src/test/java/com/powsybl/commons/io/WorkingDirectoryTest.java
Signed-off-by: Sylvain Leclerc <sylvain.leclerc@rte-france.com>
Bug fix
When closing twice a `WorkingDirectory`, we get an exception. In particular, this happens when using the same instance of `LocalComputationManager` in 2 places.
Closing is idempotent : closing a second time does not do anything.
=> Making WorkingDirectory.close() idempotent.

pom.xml
No
Vulnerability fix: [CVE-2020-8908](https://github.com/advisories/GHSA-5mg8-w23w-74h3)
Bump guava version to 30.0-jre
=> Bump guava version to 30.0-jre (CVE-2020-8908)

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLine.java
No
Bug/API fix
Current Limits methods are defined twice in Dangling Line
They are only defined in `FlowLimitsHolder`
No
**Other …
=> Delete redundant dangling line current limits methods (already defined in FlowLimitsHolder)

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/CurrentLimits.java
Fix in javadoc comment
Temporary limit was being defined, but wording related to permanent limit was used.
Fixed definition of temporary limit.
=> Fix current limits javadoc comment defining a temporary limit

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/SmallGrid/WithSvInjection/SmallGridTestConfiguration_BC_SV_v3.0.0.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
…as exported as NaN.
Feature.
The active flow `p` of `ShuntCompensator`, `StaticVarCompensator` and `Battery` is exported as NaN.
The active flow `p` of `ShuntCompensator`, `StaticVarCompensator` and `Battery` is exported as 0.0. 
In all the …
=> ShuntCompensator, StaticVarCompensator, Battery: export the active flow as 0.0.

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
Feature
The `retained `attribute of switches is not imported.
The `retained `attribute of switches is imported.
(if any of …
=> Cgmes Switches: Import retained attribute.

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
No
Bug fix? It seems weird to throw an exception for missing regulation information when regulation is not activated.
=> When the PTC is not regulating, do not throw exception if some info is missing

iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importer.java
No
Add backward compatibility to Importer.importData(ReadOnlyDataSource, NetworkFactory, Properties, Reporter): the method does not throw an exception at runtime anymore
No
=> Add backward compatibility to Importer.importData(ReadOnlyDataSource, NetworkFactory, Properties, Reporter)

commons/src/main/java/com/powsybl/commons/reporter/AbstractReporter.java, commons/src/main/java/com/powsybl/commons/reporter/Report.java, commons/src/main/java/com/powsybl/commons/reporter/ReportBuilder.java, commons/src/main/java/com/powsybl/commons/reporter/Reporter.java, commons/src/main/java/com/powsybl/commons/reporter/ReporterModel.java, commons/src/main/java/com/powsybl/commons/reporter/ReporterModelDeserializer.java, commons/src/main/java/com/powsybl/commons/reporter/ReporterModelJsonModule.java, commons/src/main/java/com/powsybl/commons/reporter/ReporterModelSerializer.java, commons/src/main/java/com/powsybl/commons/reporter/TypedValue.java, commons/src/main/java/com/powsybl/commons/reporter/package-info.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReporterTest.java
No
Bug fix
Dictionary name needs to be specified through injectable value, fallback to default name fails
- If dictionary name missing falls back to "default" name
- If dictionary name specified is not in the "dics" root entry, falls back to first entry of dics and warns the user
- if "dics" root entry is missing or empty, warns the user
**Does this PR introduce a breaking change or deprecate an …
=> Reporter POC: fix deserialization with no specified dictionary

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java, sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisProvider.java
NO
Bug fix
with old providers, the new run methods with reporters throw exceptions.
with old providers, the new run methods run without producing a report …
=> Add backward compatibility to LoadFlowProvider.run and SensitivityAnalysisProvider.run with reporter

commons/src/main/java/com/powsybl/commons/reporter/ReporterModelDeserializer.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReporterTest.java
No
Bug fix
When deserializing a `ReporterModel` json, if the `ObjectMapper` contains injectable values but not the dictionary language, then a NPE is thrown, while trying to create a uncaught `RuntimeException` (`IllegalArgumentException`)
The NPE is avoided and the `IllegalArgumentException` is caught, taking the `"default"` value for the dictionary language
No
=> Fix report deserialize corner case

computation/src/main/java/com/powsybl/computation/SimpleCommandBuilder.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java, loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/CandidateComputation.java, math/src/main/java/com/powsybl/math/graph/GraphUtil.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/package-info.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/package-info.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/preprocessor/package-info.java
No
Docs update
- License appears in the package info java doc (see com.powsybl.security.distributed in [javadoc package list](https://javadoc.io/doc/com.powsybl/powsybl-core/latest/index.html))
- Referring to a method parameter with `{@param parameter}` is not supported (see [javadoc](https://javadoc.io/doc/com.powsybl/powsybl-core/latest/com/powsybl/iidm/network/VoltageLevel.NodeBreakerView.html) & intellij)
- License does not appear …
=> Fix javadoc formatting

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/DiscreteMeasurementsXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/MeasurementsXmlSerializer.java
No
Bug fix
Values for measurements and discrete measurements are optional in the XSD and the checks but not during deserialization.
Deserializers do not try to read undefined values. …
=> Values for measurements and discrete measurements should be optional

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/NodeBreakerTopology.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CalculatedBusImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerInternalConnectionsTest.java, math/src/main/java/com/powsybl/math/graph/TraverseResult.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java, math/src/test/java/com/powsybl/math/graph/UndirectedGraphImplTest.java
No
Feature
If the whole traversing process needs to be stopped, it needs to be done with a custom added state.
The whole traversing process can be stopped by returning `TraverseResult.BREAK` in `Traverser::traverse`
**Does this PR introduce a breaking change or deprecate an API?** yes
=> Stopping traverser

math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java, math/src/main/java/com/powsybl/math/matrix/Matrix.java, math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java, math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java
No
Feature
There is already a method to create and later re-update an element but it require to create an extra `Matrix.Element` object for each element of the matrix. For large matrices, it could be responsible of performance issue (large memory allocation, gc loading).  
**What is …
=> Fast matrix element re-update

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-scripting/src/test/groovy/com/powsybl/iidm/network/scripting/VoltageLevelExtensionTest.groovy
**D**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Bug fix
Substation are optional to create voltage levels and transformers. If a voltage level without substation is defined for the Node Breaker type topology, an error occurs when trying to access the voltage level substation, a substation that does not exist
The same implementation that is used to create a voltage level for a Bus Breaker type topology is applied.
=> fix NodeBreakerVoltageLevel with optional substation

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VscConverterStation.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VscConverterStationAdapter.java
No
Bug fix
Return type for method chaining is not correct for `VscConverterStation` setters 
It is fixed! …
=> Fix VscConverterStation setters return type

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerTest.java
No
Bug fix
Bus breaker view cache cannot be build if more than one voltage level in the network: `java.lang.IllegalArgumentException` is thrown with `"Multiple entries with same key"` message. Indeed, the buses in the cached map are duplicated for each voltage level, leading to this exception.
Bus breaker view cache can be build.
No
=> Fix bus breaker view cache

cim-anonymiser/pom.xml, cim-anonymiser/src/test/java/com/powsybl/cim/CimAnonymizerTest.java, commons/src/test/java/com/powsybl/commons/AbstractConverterTest.java, commons/src/test/java/com/powsybl/commons/TestUtil.java, psse/psse-model/src/test/java/com/powsybl/psse/model/PsseRawDataTest.java, tools/pom.xml, tools/src/test/java/com/powsybl/tools/autocompletion/BashCompletionGeneratorTest.java, tools/src/test/java/com/powsybl/tools/autocompletion/BashCompletionToolTest.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReporterTest.java
No
Bug fix
Windows build is broken because of a few unit tests that are dependent of git carriage return configuration. If 'input' is configured so that all files are checkout with LF instead of CRLF (default behaviour), some unit tests based of reference file comparison fail. …
=> Fix Windows build

iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/TopologyTraverserTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTopologyTraverserTest.java
No
Unit tests fix
Traverser unit tests in the tck are testing the list of visited terminal, hence the visiting order, but the implementation might change this order.
Traverser unit tests in the tck are testing the set of visited terminal, therefore not considering the visiting order.
Order dependent tests are moved to the implementation test class `TopologyTraverserTest`.
**Does this PR …
=> Update tck traversers unit tests

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java, commons/src/main/java/com/powsybl/commons/xml/XmlUtil.java
No
Feature
The `XMLStreamWriter` returned by `XmlUtil::intializeWriter` cannot be created from a `Writer` but only from an `OutputStream`.
The `XMLStreamWriter` returned by `XmlUtil::intializeWriter` can either be created from a `Writer` or an `OutputStream` …
=> Initialize XmlStreamWriter based on Writer

cgmes/cgmes-model/src/main/resources/CIM100.sparql
Fix performance of SPARQL query for synchronous machines in CGMES 3 import (CIM100).
Query has low performance on big networks.
The performance problem was identified to a nested OPTIONAL clause sharing no variables with its parent clause. The statements in the query have been reorganised to avoid the issue. It is the same fix that was applied in #1891 to CIM16 set of queries.
=> CGMES 3 - Fix query for synchronous machines in CIM100

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
A model is considered node/breaker based on the profiles defined in its files. Recompute if the model is node/breaker only when new files are added to the triplestore.
The model profiles are queried and reviewed everytime the model is checked for node/breaker.
The flag that stores if a model is node/breaker is cached and only recomputed when new data is added to the triplestore.
=> CGMES. Optimize verification of model is node/breaker

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/VoltageLevelConversion.java
Signed-off-by: VEDELAGO MIORA <miora.vede@gmail.com>
No
Ignoring voltage level with nominal voltage equal to zero during CGMES import
Throwing an exception
=> Ignore voltage level with nominal voltage equal to zero during CGMES import

matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerModel.java
No
Bug fix
For unit testing, matpower files are stored in json (unofficial matpower format) and loaded to re-create a .mat file.
In the matpower model, elements like buses and generators are double indexed and when it is created from a json file using jackson object mapper, the double …
=> Fix Matpower json read

matpower/matpower-converter/pom.xml, matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java, matpower/matpower-converter/src/test/resources/ieee118mat.xiidm, matpower/matpower-converter/src/test/resources/ieee14mat.xiidm, matpower/matpower-converter/src/test/resources/ieee300mat.xiidm, matpower/matpower-converter/src/test/resources/ieee30mat.xiidm, matpower/matpower-converter/src/test/resources/ieee57mat.xiidm, matpower/matpower-converter/src/test/resources/ieee9mat.xiidm
No
feature
When importing a matpower file, slack bus infos is lost.
A slack terminal extension is added to the network to keep track of initial (matpower file) slack bus. …
=> Create slack terminal extension in Matpower importer

cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_rtc_ptc_faulty_tabular/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractCgmesTapChangerBuilder.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesRatioTapChangerBuilder.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
No
Feature
Does not take into account step number in tables: can fail depending on tap position + can import faulty tables
Ignore faulty tables …
=> Ignore tables with missing steps during CGMES import: tap changers considered linears

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
No
Change: strictly speaking, we cannot say a CGMES without EQ profile is not CGMES; it is not a **correct** CGMES but this is not what the method `CgmesExport.exists()` should check.
Fails if the CGMES file(s) do(es) not contain at least one file with the suffix EQ.
**Does this PR introduce …
=> Delete check if one of CGMES file with suffix EQ exists

cgmes/cgmes-model/src/main/resources/CIM16.sparql
Includes the additional type of switch `GroundDisconnector`.
Reads the attribute `normalOpen` defined in CGMES EQ profile (considering it optional: if not found, the conversion works like before, setting the state of switch by default to "closed").
=> CGMES switches: add ground disconnectors, read normal open attribute

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractTransformerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChanger.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangerAdder.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangerAdderImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangerImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangers.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangersAdder.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangersAdderImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangersAdderImplProvider.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangersImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangersXmlSerializer.java, cgmes/cgmes-extensions/src/main/resources/xsd/cgmesTapChangers.xsd
No
Feature
Transformers have a lot of properties that are not really user-friendly
These properties are replaced by extensions
Yes
=> Replace CGMES tap changers properties by extensions

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
No
Bug fix
Select as CIM namespace any namespace containing `CIM-schema-cim` which may not be a correct CIM schema.
Strictly select from known CIM namespaces …
=> Make CIM namespace detection more specific in order not to select an incorrect namespace

iidm/iidm-xml-converter/pom.xml, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/BusBreakerAnonymiserBugTest.java
No
Bug fix
We have an exception when we try to export anonymized IIDM with a switch in a bus/breaker voltage level.
**Other …
=> Fix IIDM bus/breaker switch anonymizer

iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/BranchObservability.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/InjectionObservability.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ObservabilityQuality.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BranchObservabilityAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BranchObservabilityImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/InjectionObservabilityAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/InjectionObservabilityImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ObservabilityQualityImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractBranchObservabilityTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractInjectionObservabilityTest.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/BranchObservabilityXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/InjectionObservabilityXmlSerializer.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/BranchObservabilityXmlTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/InjectionObservabilityXmlTest.java, iidm/iidm-xml-converter/src/test/resources/V1_6/branchObservabilityRoundTripRef.xml, iidm/iidm-xml-converter/src/test/resources/V1_6/injectionObservabilityRoundTripRef.xml
No
Code simplification: there is no functional difference to consider the redundant attribute in ObservabilityQuality as undefined or false.
Yes
=> redundant attribute in ObservabilityQuality is a boolean and not a Boolean anymore + some code improvements

iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/util/AbstractRemoveDanglingSwitchesTopologyTest.java
No
Bug fix
Removed equipments list check is too restrictive as it also check order.
We don't check order anymore
**Other …
=> Fix remove dangling switches TCK tests to be more generic

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
Feature
When obtaining the list of topological nodes of a bus, it is verified that it is not null.
Currently this list cannot be null, so the check is unnecessary.
=> topological nodes set can not be null

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/DefaultNetworkReducerTest.java, math/src/main/java/com/powsybl/math/graph/DefaultUndirectedGraphListener.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraphListener.java
No
Bug fix
Switches are not removed from index and still appear (for example in `getSwitchesCount()`) after all edges removed. 
Yes
=> Fix bug: switches were not removed from index when all edges were removed

shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitAnalysisResult.java, shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisMock.java, shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisTest.java
No
Remove the feederResult from ShortCircuitAnalysisResult as it is not useful there
=> Remove feeder result from short circuit analysis result

iidm/iidm-modification/pom.xml, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AttachNewLineOnLine.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AttachVoltageLevelOnLine.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/AttachNewLineOnLineTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/AttachVoltageLevelOnLineTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/TopologyTestUtils.java, iidm/iidm-modification/src/test/resources/eurostag-line-split-bb-l.xml, iidm/iidm-modification/src/test/resources/eurostag-line-split-bb-vl.xml, iidm/iidm-modification/src/test/resources/eurostag-line-split-nb-l.xml, iidm/iidm-modification/src/test/resources/eurostag-line-split-nb-vl.xml
No
Moving code from powsybl/powsybl-network-hypothesis and correcting code
=> Add hypotheses to create a voltage level on a line and to attach a line to another line

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/CorruptedNetworkWhenSecondNodeAlreadyUsed.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractCorruptedNetworkWhenSecondNodeAlreadyUsed.java
No
Bug fix
When creation a line or a transformer and setting a second node already taken by another element, an exception is thrown (normal...) but the transformer is still reachable from the substation and partially connected. So when exporting network  or running a LF we endup with …
=> Fix network corruption when second node already used

iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java, iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportersTest.java
No
Feature : Add some overload of `Importers.loadNetwork` which allows `ReadOnlyDataSource` as parameter
+ some code improvements
No
=> Add new overload for loadNetwork and improve code in Importers

ieee-cdf/ieee-cdf-converter/src/test/java/com/powsybl/ieeecdf/converter/IeeeCdfImporterTest.java, loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletion.java, matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerImporterTest.java
Feature
To calculate the balance of a bus the active and reactive power values of the terminals are used. 
Before balance, it is necessary to complete the terminal flows of lines and transformers using the `LoadFlowResultsCompletion.run` method and the active and reactive power of the terminals …
=> Improve loadflow results completion

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
No
Fix
exists() in CgmesImport returns false if files does not contain EQ, TP, SSH.... etc
exists() does not take the file name into account
=> Fix: exists() method for CGMES should not rely on profiles identifiers in file name

cgmes/cgmes-measurements/src/main/java/com/powsybl/cgmes/measurements/CgmesDiscretePostProcessor.java
No
Fix
type is OTHER when not TAP_POSITION
type can be SWITCH_POSITION
=> Small fix in CgmesDiscretePostProcessor: when SwitchPosition, type is SWITCH_POSITION, not OTHER

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java
The ability to export Network to a specific CIM version when exporting to CGMES format.
Code in `CgmesExport` wrote in the output the CIM headers corresponding to the CIM version stored in the extension `CimCharacteristics`. If the extension was not available (if the Network was not imported from CGMES data), CIM …
=> CGMES export to specific CIM version

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/HvdcOperatorActivePowerRangeXmlSerializer.java
No
Fix: HvdcOperatorActivePowerRange's attributes are optional but the deserializer does not consider them as optional. It will do so now.
=> Fix serializer of HvdcOperatorActivePowerRange: its attributes are optional

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java, commons/src/main/java/com/powsybl/commons/datasource/FileDataSource.java, commons/src/test/java/com/powsybl/commons/datasource/FileDataSourceTest.java
=> File data source lists names of files only if they start with basename

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
No
Bug fix: network validation level is not invalidated after setting tap position or section count so network validation level might not be correct. It is fixed in this PR.
No
=> Bug fix: Invalidate network validation level after setting tap position or section count

cgmes/cgmes-conformity/src/test/resources/logback-test.xml, cgmes/cgmes-model-alternatives/src/test/resources/logback-test.xml, cgmes/cgmes-model/src/test/resources/logback-test.xml, triple-store/triple-store-test/src/test/resources/logback-test.xml
No
Reduce compilation time by reducing log verbosity in CGMES tests and Triplestore tests
=> Reduce CGMES and Triplestore tests logs by default to ERROR level

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGeneratorTest.java
No
Bug fix: in SSH validation level, voltageRegulatorOn has to be defined or it throws an explicit exception
=> Fix check in ValidationUtil: voltageRegulatorOn can be null in ValidationUtil, throwing an error

powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ContainersMappingHelper.java, powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java, powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsReader.java, powerfactory/powerfactory-dgs/src/test/java/com/powsybl/powerfactory/dgs/DgsDataTest.java, powerfactory/powerfactory-dgs/src/test/resources/TwoBuses.json, powerfactory/powerfactory-dgs/src/test/resources/TwoBusesCommaAsDecimalSeparator.json, powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/DataObject.java, powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/DataObjectIndex.java, powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/DataObjectRef.java, powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/StudyCase.java, powerfactory/powerfactory-model/src/test/java/com/powsybl/powerfactory/model/DataObjectTest.java, powerfactory/powerfactory-model/src/test/java/com/powsybl/powerfactory/model/StudyCaseTest.java
No
Design fix
When reading from DGS file, object reference are modeled by an INTEGER64 attribute, which is wrong. There are INTEGER64 attributes that are not object references and there is a dedicated type (see PF C++ API) for that.
**What is the new behavior (if this is a feature …
=> Refactor PowerFactory object reference

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportTest.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMapping.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingAdder.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingAdderImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingAdderImplProvider.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingXmlSerializer.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMapping.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingAdder.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingAdderImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingImpl.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingXmlSerializer.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/Source.java, cgmes/cgmes-extensions/src/main/resources/xsd/baseVoltageMapping.xsd, cgmes/cgmes-extensions/src/main/resources/xsd/cgmesIidmMapping.xsd, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
No
Undefined: prepare the eventuality of deleting CgmesIidmMapping (TP may only be an output for node-breaker networks)
=> CgmesIidmMapping now strictly contains topological mapping and is optional for CGMES import and export

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ControlAreaEq.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ModelDescriptionEq.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/RegulatingControlEq.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
Ability to export go CGMES 3. It can be requested by the user setting export param `iidm.export.cgmes.cim-version` to 100.
(if any of the questions/checkboxes don't apply, please …
=> CGMES export to version 3

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
No
Bug fix, following #1992 
Boundaries files must have base name corresponding to their directory to be considered
All files inside boundary directory are considered for boundaries …
=> Bug fix: When looking for boundaries, all files inside the boundary location directory are considered

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
No
Bug fix: CGMES regions and subregions are set from countries and geographical tags if they exist in `CgmesExportContext` and not uniquely generated for each substation
No
=> Bug fix: CGMES region and subregion are set from country and geotag (not randomly)

powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsStudyCaseLoader.java, powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/StudyCaseLoader.java
No
Bug fix
When reading a DGS file, 2 ÌnputStream`are created but never closed.
All ÌnputStream` are correctly closed.
**Other …
=> Fix file leak when reading DGS file

cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingAdderImplProvider.java
Bug fix
The BaseVoltage extension provider uses the NAME variable of the CgmesIidmMapping extension.
Correct the BaseVoltage extension provider so that it uses the correct variable
=> fix extension name

computation/src/main/java/com/powsybl/computation/CompletableFutureTask.java, computation/src/test/java/com/powsybl/computation/CompletableFutureTaskTest.java
NO
BugFix / Feature
calling cancel(true) on the CompletableFuture returned by the SecurityAnalysis API (probably other APIs too) do not kill the external process (when using an implementation based on LocalComputationManager)
kills the external process.
Calling cancel() multiple times now returns …
=> Propagate Cancel to CompletableFutureTask (kill external process of localcomputationmanager)

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
No
Fix
An exception is thrown when there is no bus of the bus view at both ends of a switch.
A fictitious topological node is created. …
=> Fix: does not crash during CGMES export when a terminal is disconnected

powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/AbstractConverter.java, powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ContainersMappingHelper.java, powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/DataAttributeNames.java, powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/GeneratorConverter.java, powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/LineConverter.java, powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java, powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGenerator.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGenerator.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAvmode.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAvmode.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorElmReactiveLimits.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorElmReactiveLimits.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorIqtype.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorIqtype.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorTypMvarReactiveLimits.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorTypMvarReactiveLimits.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorTypReactiveLimits.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorTypReactiveLimits.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorWithoutActiveLimits.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorWithoutActiveLimits.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorWithoutIqtype.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorWithoutIqtype.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorWithoutIvmode.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorWithoutIvmode.xiidm, powerfactory/powerfactory-converter/src/test/resources/TwoBusesLineWithC.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesLineWithGandB.dgs, powerfactory/powerfactory-converter/src/test/resources/TwoBusesLineWithTandB.dgs
Feature
Only `iv_mode` is considered to define `voltageRegulatorOn`
`Q_min` and `Q_max` are used to convert per unit reactive limits to Mvar reactive limits
Use `iv_mode` and `av_mode` to define `voltageRegulatorOn`
Use targetP as default …
=> PowerFactory: GeneratorConverter

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerTest.java
No
Bug fix: IDs of calculated buses can be identical to IDs of existing equipment, creating issues on some cases.
=> Ensure IDs of calculated buses are unique in IIDM networks

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
No
Bug fix: ensuring connectivity nodes and topological nodes have different IDs when coming from non-CGMES networks
They can have identical IDs.
No
(if any of the …
=> Ensure connectivity nodes and topological nodes have different IDs in CGMES networks from IIDM networks

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
No
Fix switch terminals ID in CGMES EQ export: IDs did not correspond to IDs specified in IIDM network
=> Fix switch terminals ID in CGMES EQ export

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
No
Fix: Shunts' RC are not written in EQ and generators' and static var compensators' RC are checked twice
=> Fix Regulating Control export in CGMES export

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusbarSectionAdderImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/NpeInBusbarSectionAdderTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNpeInBusbarSectionAdderTest.java
No
Bug fix
If node is not set in busbar section adder, we have a NPE
A proper exception is thrown with a clear message
**Other …
=> Fix NPE in busbar section adder

triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/PropertyBag.java
minor optimization
IRI prefixes of RDF names are removed using `String::replaceAll` with a regular expression.
IRI prefixes of RDF names are removed using `String::indexOf`.
Removed unused private method `padr`.
=> Triplestore: remove prefix using indexOf instead of replaceAll

pom.xml
No
Bug fix
We use math native 1.2.0 which has a regression compared to 1.1.0 because MacOS lib has been compiled on MacOS 11 instead of MacOS 10.
Math native 1.2.1 has been compiled on MacOS 10 …
=> Math native 1.2.1

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
No
Bug fix
A NPE is thrown when a network component is added and the validation level has been invalidated
No
(if any of the questions/checkboxes don't apply, please delete …
=> Fix NPE: no NPE thrown when equipment added and validation level has been invalidated

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
Fields `description` and `modellingAuthoritySet` in CGMES model metadata are not identifiers, they should be obtained from `PropertyBag` as regular attributes.
Fields are obtained using `PropertyBag::getId`.
Fields are obtained using `PropertyBag::get` to avoid specific processing for identifiers. …
=> description, modellingAuthoritySet are not identifiers

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_gen_unit_with_two_sync_machines/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
Bug fix.
Network created from CGMES inputs where multiple synchronous machines are in the same generating unit.
If Network is exported to CGMES the generating unit is written multiple times in the EQ instance file, once for each synchronous machine.
Generating unit definitions are written only once in the EQ, even if multiple IIDM generators (coming from multiple CGMES synchronous …
=> Fix export of generating units with multiple synchronous machines

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
bug fix
Path for boundary is not verified before attempting to import files.
If path does not exists, import of boundary files is not attempted.
=> CGMES import: ensure path exists before trying to load boundaries

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ShuntCompensatorEq.java
Bug fix
In CGMES exports, shunt compensators are missing the reference to its corresponding regulating controls.
Shunt compensators with a regulating control are exported with proper reference in the CGMES EQ file.
=> CGMES export: shunt compensator reference to its regulating control

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/RegulatingControlEq.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ShuntCompensatorEq.java
Bug fix
If the same regulating control (RC) was referred by more than one equipment a separate definition for the RC was written to CGMES EQ output for each referral, resulting in multiple objects with same identifier being exported.
A regulating control definition is written only once in the CGMES EQ export, even if it is referred by multiple equipment.
=> CGMES export: export definition of regulating controls only once

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractConnectableXml.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadingLimitsBugTest.java, iidm/iidm-xml-converter/src/test/resources/loading-limits-bug.xml
No
Bug fix
If we have a network with a transformer with apparent or active power limit and if we export to a <= 1.5 XIIDM version,
the resulting XML is ill formed.
Apparent or active power limit, should not be exported if XIIDM …
=> Loading limits bug when exporting to XIIDM 1.5

shortcircuit-api/src/main/java/com/powsybl/shortcircuit/Fault.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FaultParameters.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/converter/JsonShortCircuitAnalysisResultExporter.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FaultDeserializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FaultParametersDeserializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FaultParametersSerializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FaultResultDeserializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FaultResultSerializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FaultSerializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FeederResultDeserializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FeederResultSerializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FortescueValuesDeserializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FortescueValuesSerializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/JsonShortCircuitParameters.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/ShortCircuitAnalysisJsonModule.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/ShortCircuitAnalysisResultDeserializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/ShortCircuitAnalysisResultSerializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/ShortCircuitBusResultsDeserializer.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/ShortCircuitBusResultsSerializer.java, shortcircuit-api/src/test/java/com/powsybl/shortcircuit/converter/ShortCircuitAnalysisResultExportersTest.java, shortcircuit-api/src/test/java/com/powsybl/shortcircuit/json/JsonFortescueValueTest.java
No
Moves serializers and deserializers of the shortcircuit API into the right package.
Serializers/deserializers are into the converter package.
=> Move shortcircuit serializers/deserializers into json package

powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsHandler.java, powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsParser.java, powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsReader.java, powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/DataObject.java
… dgs case or a powerfactory dump case.
Feature
Vectors and matrices are recorded as a list of flat fields when a dgs case is imported.
Same DataObject format for vectors and matrices regardless if it is a dgs case or a powerfactory dump case. …
=> Same dataObject format for vectors and matrices.

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SourceForIidmIdentifiersTest.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModelFactory.java, triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStore.java, triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStoreFactory.java, triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStoreFactoryService.java, triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStoreOptions.java, triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreFactoryServiceRDF4J.java, triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreRDF4J.java
Feature
IIDM identifiers are equal to CGMES **mRIDs** (Master Resource Identifiers). 
Using a configuration parameter for CGMES Import, source for IIDM identifiers can be set to **rdf:ID** (Resource Description Framework Identifiers). RDF identifiers are built from CGMES mRIDs prefixed with a `_` character.
The name of the new parameter is `iidm.import.cgmes.source-for-iidm-id`. …
=> CGMES import parameter for IIDM id source: mRID or rdfID

matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java, matpower/matpower-converter/src/test/resources/ieee9_limits.xiidm
No
Feature
Apparent power limits are arbitrary created at side one.
Apparent power limits are duplicated at both sides.
**Other …
=> Matpower: create limits at both sides

pom.xml
No
Bug fix
There is a bug in graph 1.4.0 when we add the same edge multiple times. See "Fixed issue with inconsistent graph after duplicate edge addition" in release notes 1.5.0: https://github.com/jgrapht/jgrapht/blob/master/HISTORY.md
We add this issue in OLF, see PR …
=> Upgrade jgrapht to 1.5.1

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ActionDeserializer.java
bug fix
when deserializing action json, boolean of lineConnectionAction can be null
they can not be null now
=> fix lineConnectionAction deserializer

commons/src/main/java/com/powsybl/commons/xml/XmlUtil.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ObservabilityQuality.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ObservabilityQualityImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractBranchObservabilityTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractInjectionObservabilityTest.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/BranchObservabilityXmlSerializer.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/InjectionObservabilityXmlSerializer.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/InjectionObservabilityXmlTest.java, iidm/iidm-xml-converter/src/test/resources/V1_6/branchObservabilityRoundTripRef.xml, iidm/iidm-xml-converter/src/test/resources/V1_7/branchObservabilityRoundTripRef.xml, iidm/iidm-xml-converter/src/test/resources/V1_8/branchObservabilityRoundTripRef.xml, iidm/iidm-xml-converter/src/test/resources/V1_8/injectionObservabilityRoundTripRef.xml
for observability extensions quality P Q and V have a redundancy false by default and it is not exported with iidm if it is false
redundancy can be null and it is exported if it is false
=> allow to serialize redundancy equal to false

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/TopologyModificationUtilsTest.java
No
Bug fix
Wrong range in `TopologyModificationUtils::getUnusedOrderPositionsAfter` if no orders before
Range fixed
No
=> [Network modifications] range fix in utility method

powerfactory/powerfactory-converter/pom.xml, powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/TransformerConverter.java, powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java, powerfactory/powerfactory-converter/src/test/resources/TransformersWithPhaseAngleClock.dgs, powerfactory/powerfactory-converter/src/test/resources/TransformersWithPhaseAngleClock.xiidm
Feature
Connection type of transformers is not read.
PowerFactory expresses the winding configurations of three-phase transformers using the notation of vector group defined by the International Electrotechnical Commission (IEC) in the attribute `vecgrp`. 
In the vector group value (the _connection symbol_) the digits following the letter codes indicate the difference in phase …
=> PowerFactory: add phase angle clock from transformer connection type

sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisResult.java, sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisParametersTest.java, sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisProviderMock.java, sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java, sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisToolTest.java, sensitivity-analysis-api/src/test/resources/SensitivityAnalysisResultRefV1.json, sensitivity-analysis-api/src/test/resources/contingencyStatusRef.json
After some discussion with @annetill it has been decided to rename some of the contingency status enum : 
CONVERGED is now SUCCEED
FAILED is now FAIL
(if any of the …
=> Rename contingency status enum

powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsParser.java, powerfactory/powerfactory-dgs/src/test/java/com/powsybl/powerfactory/dgs/DgsDataTest.java, powerfactory/powerfactory-dgs/src/test/resources/EmptyMatrix.dgs
Bug fix
DGS lines in a data block may have empty matrices (mTaps), even if the header declared a specific size.
The parser always expected at least the number of rows and cols declared in the header.
The DGS lines may have empty matrices (with either columns or rows equal to zero).
All matrices must have exactly the number of columns declared in the header .
=> PowerFactory: allow empty matrices in DGS parser

pom.xml
No
Fix vulnerability [CVE-2022-25857] https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25857
Bump org.yaml.snakeyaml to 1.31
=> Bump snakeyaml to 1.31 (vulnerability [CVE-2022-25857])

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBays.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java, iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line.xml, iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-bbs4.xml
No
Add configurable feeder names in hypotheses creating feeders' bays
The connectable ID is used for feeders' names.
They can be manually set. If not set, connectable ID is used.
=> Add configurable feeder names in hypotheses creating feeders' bays

iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/GeneratorShortCircuit.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/IdentifiableShortCircuit.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/IdentifiableShortCircuitAdderImplProvider.java
No
Bug fix
IdentifiableShortCircuit extension is supported for every Identifiable.
Supported only for voltage levels, buses and busbar section.
=> Fix IdentifiableShortCircuit so that it only applies to voltage levels, buses and busbar sections.

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
feature
it allow to directly get a specified connectable from a Network
=> add getConnectable(string) in network

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java, iidm/iidm-modification/src/test/resources/network_one_voltage_level.xiidm
No
Bug fix.
If a voltage level has busbar sections but no connectable and a modification is applied, the extensions are not created because a busbar section is considered as a Connectable (it is an Injection).
Now, if there are busbar …
=> [Network modification] Fix extension creation in case of no connectables in the voltage level.

iidm/iidm-comparator/src/main/java/com/powsybl/iidm/comparator/NetworkStateComparator.java, iidm/iidm-comparator/src/test/java/com/powsybl/iidm/comparator/NetworkStateComparatorTest.java
No
Feature
No SVC state comparison
SVC state comparison in comparison Excel: v and q in new 'Static VAR Compensators' worksheet
No
=> Added SVCs reactive power and voltage comparison in NetworkStateComparator

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
No
Bug fix
Terminals and flows of non-exported switches are exported in CGMES export.
No
=> CGMES export fix: do not export flows and terminals of non-exported switches

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/TopologyModificationUtilsTest.java, iidm/iidm-modification/src/test/resources/network-nb-no-connectable-position.xiidm
No
Bug fixes
- When no minimum value defined for unused positions, return 0, not `Integer.MIN_VALUE` (cannot be negative) 
- Fix loop to get unused positions : no infinite loop
No …
=> Fix loop to get unused positions + refactoring + min is 0, not Integer.MIN_VALUE

powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/GeneratorConverter.java
Feature
pgini and qgini is used for targetP and targetQ in generators.
pgini_a and qgini_a is used for targetP and targetQ in generators when they are available otherwise pgini and qgini is used. …
=> Powerfactory: Generator converter, for targetP and targetQ use pgini_a and qgini_a if are available

iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/StandbyAutomaton.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/StandbyAutomatonAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/StandbyAutomatonAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/StandbyAutomatonAdderImplProvider.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/StandbyAutomatonImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/StandbyAutomatonTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractStandbyAutomatonTest.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/StandbyAutomatonXmlSerializer.java, iidm/iidm-xml-converter/src/main/resources/xsd/standbyAutomaton.xsd, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/StandbyAutomatonXmlTest.java, iidm/iidm-xml-converter/src/test/resources/standbyAutomatonRoundTripRef.xml
=> StandbyAutomaton extension of static var compensator

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/LoadGroup.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/LoadGroups.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/EnergyConsumerEq.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
Exported EQ must contain load groups if Conform or NonConform energy consumers are present.
No load groups were exported, resulting in warnings when the output instance files were validated against the profile.
A unique `ConformLoadGroup` is created and referred in all `Conform` loads.
A unique `NonConformLoadGroup` is created and referred in all `NonConform` loads.
Groups are …
=> CGMES Export: export missing load groups

matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java, matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerImporterTest.java, matpower/matpower-converter/src/test/resources/ieee14-inverted-voltage-limits.xiidm, matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerModel.java
No
Bug fix
On case1888rte case, some voltage limits have been inverted: minimumVoltageMagnitude is greater that maximumVoltageMagnitude. Import failed on such a case because of IIDM consistency validation.
The case is …
=> Matpower: fix inverted voltage limits

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_eqbranch_with_zero_impedance_inside_voltage_level/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_eqbranch_with_zero_impedance_inside_voltage_level/MicroGridTestConfiguration_BC_BE_TP_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentBranchConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/EquivalentBranchConversionTest.java
…ide a voltage level
Bug fix
The method `updateParametersForEquivalentBranchWithDifferentNominalVoltages` throws an exception when an equivalent branch with zero impedance inside a voltage level is imported. This method expects always a line and in this case the equivalent branch is converted to a …
=> Cgmes Conversion: Fix exception processing an equivalent branch with zero impedance

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysis.java
Feature
`SecurityAnalysis.Runner(provider)` is private.
In some situations, in particular unit tests,
it's useful to be able to use a security analysis provider which is defined programmatically, and not in config.
This is consistent with loadflow and sensitivity analysis API
=> Make SecurityAnalysis.Runner constructor public

iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/StandbyAutomatonAdder.java
Bug fix: deprecated `setLowVoltageSetPoint` called `setHighVoltageSetpoint` instead of `setLowVoltageSetpoint`
=> Fix default implementation of deprecated method of StandbyAutomatonAdder

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
Update
The identifier of the boundary terminal was initially stored as a property of dangling lines during conversion, and read from the tie line properties in the merging view.
The terminal is needed when exporting flows at boundaries in the SV profile.
Currently, the terminal is stored and read from a typed alias.
The property was not needed anymore, and an error was raised if an access to the property value was detected.
This resulted in the tutorial for the merging view to …
=> CGMES export: do not throw exception when merged lines contain boundary terminals properties

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisCommandOptions.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandler.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisCommandOptionsTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlersTest.java
Bug
The distributed security analysis is not working since operator strategies:
we write actions instead of parameters into the parameters file, this causes the distributed security analysis to fail systematically when trying to parse parameters.
We correctly write new files to `actions.json` and `strategies.json`.
=> Fix regression in distributed security analysis

cgmes/cgmes-shortcircuit/src/main/java/com/powsybl/cgmes/shorcircuit/CgmesShortCircuitPostProcessor.java, cgmes/cgmes-shortcircuit/src/test/java/com/powsybl/cgmes/shortcircuit/CgmesImporterTest.java
Add CGMES post-processor to import short-circuit data
No post-processor: only way to import short-circuit data is to call the explicit class
It is possible to import short-circuit data by setting the correct property during CGMES import
=> Add CGMES post-processor to import short-circuit data

pom.xml
No
Fix vulnerability
[CVE-2022-41854] Snakeyaml vulnerable to Stack overflow leading to denial of service
Bump to 1.33
No
**Other …
=> Fix vulnerability [CVE-2022-41854] by bumping snakeyaml to 1.33

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBays.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveFeederBayTest.java, iidm/iidm-modification/src/test/resources/eurostag-create-line-feeder-bays.xml, iidm/iidm-modification/src/test/resources/eurostag-create-load-feeder-bay.xml, iidm/iidm-modification/src/test/resources/eurostag-create-twt-feeder-bays.xml
No
Feature: allow to use modifications to create feeder bays in a bus-breaker voltage level.
Modifications to create feeder bays only work in node-breaker voltage levels.
Yes, deprecation
**Other …
=> Allow to create feeder bays in a bus-breaker voltage level

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
Fix in CGMES dangling lines import
Only two ACLineSegment linked to a X-node are imported at the maximum and other are ignored.
If exactly two connected ACLineSegments are linked to a X-node but other **disconnected** ACLineSegments are linked to the same X-node, the disconnected ACLineSegments are imported as dangling lines.
If more than two connected …
=> Import ignored ACLineSegment linked to boundary as dangling lines

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java
No
Bug fix
If inductive or capacitive ratings are undefined or 0 for SVC during CGMES import, bMin or bMax are infinite.
In this case, bMin or bMax are `Double.MAX_VALUE`
No
(if …
=> Fix SVC bMin/bMax during CGMES if capacitive and/or inductive rating are undefined or 0

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/Cgmes3ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/geographicalRegionInBoundary/20171002T0930Z_ENTSO-E_EQ_BD_2.xml, cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/geographicalRegionInBoundary/20210209T1930Z_1D_BE_EQ_9.xml, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/Cgmes3ModifiedConversionTest.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
CGMES importer: fix Substation import error when the associated GeographicalRegion is defined in EquipmentBoundary profile instance
Signed-off-by: Damien Jeandemange <damien.jeandemange@artelys.com>
No
Bug fix / remove a limitation that shouldn't exist
If a cim:Substation links to a cim:GeographicalRegion (via cim:SubgeographicalRegion) that is defined in the boundary set, the substation is not converted and the CGMES import fails later on because of the missing substations.
**What is the new …
=> CGMES importer: handle GeographicalRegion in BoundarySet

cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_Assembled_v2_bad_ids/MicroGridTestConfiguration_BC_NL_TP_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
Bug fix
Identifiers of topological nodes in the SV output may not match the identifiers exported to TP file.
When buses have ids that are invalid mRIDs and they are fixed in the export, the TP uses the fixed ids, while the SV uses directly the bus ids.
Identifiers of topological nodes in the SV export match the identifiers in the TP file.
=> CGMES SV export: use naming strategy to obtain proper topological node identifiers

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandler.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/OperatorStrategyDeserializer.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/OperatorStrategyListDeserializer.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/OperatorStrategySerializer.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/strategy/OperatorStrategy.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/strategy/OperatorStrategyList.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/tools/SecurityAnalysisTool.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisResultBuilderTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/converter/ExporterTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlersTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonOperatorStrategyExtensionTest.java, security-analysis/security-analysis-api/src/test/resources/OperatorStrategyFileExtensionsTest.json, security-analysis/security-analysis-api/src/test/resources/OperatorStrategyFileExtensionsTest2.json, security-analysis/security-analysis-api/src/test/resources/OperatorStrategyFileTestV1.0.json, security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisResultV1.3.json, security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisTest.java
No
Feature
We can only associate an operator strategy to one contingency.
We can thanks to contingency context associate an operator strategy to not only one contingency but also to non or all contingencies.
**Does this PR …
=> Use contingency context in operator strategies

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelExt.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSwitchSetRetainedTest.java
No
Feature
Bus breaker view cache invalidate when switch opened/closed even if switch is retained
If switch is retained, bus breaker view cache not invalidated when switch opened/closed
No
=> Bbv cache not invalidated for a retained switch when opened/closed

sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java, sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityVariableType.java, sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java, sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityFactorTest.java
No
Feature
The side can be easily guessed from the enum name or the javadoc
Wrong formatting in Javadoc
The user can get the side with an `OptionalInt getSide()` method on the enums.
Javadoc formatted
No
=> Add side integer to SensitivityFunctionType, SensitivityVariableType 

commons-test/src/main/java/com/powsybl/commons/test/AbstractConverterTest.java
No
Make roundTrip more robust by checking intermediary result: checks that read and write are consistent
RoundTrip only checks that the last file is identical with the reference
RoundTrip also checks that the intermediary file is …
=> Add comparison of intermediary file in roundTrip

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalableTest.java
No.
Proportional scaling with constant power factor possible in LOAD convention.
Proportional scaling with constant power factor was always done in GENERATOR convention.
=> Fix proportional scaling with constant power factor

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
=> CGMES import: active power control extension is optional

iidm/iidm-reducer/pom.xml, iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducer.java, iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/DefaultNetworkReducerTest.java
No
Bug fix
When reducing an HVDC line and turning it into a generator, maxP is set to terminal P and minP to 0.
It's causing errors when P < 0.
The new generator has max and min P set based on maxP of HVDC line, or taking into consideration HvdcOperatorActivePowerRange extension if present
=> Fixing min/max p for hvdc reduction into generator

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/AbstractTapChangerTapPositionActionDeserializer.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java, security-analysis/security-analysis-api/src/test/resources/WrongActionFileTest2.json
bug fix
it prevents AbstractTapChangerTapPositionActionDeserializer to have a 0 tap position
=> [Security analysis] Fix check on 0 value in tap changer tap position action

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
The fix is related to the checks made in the powsybl/powsybl-entsoe#88.
Bug fix
All network merge methods consider the whole (g, b) of boundary lines at network side.
When both lines of a boundary were imported and a tie line must be created, the same criteria has to be applied.
When both lines of …
=> Fix conversion of boundary lines: consider all (g,b) at network side

sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java, sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityVariableType.java
=> [Sensitivity analysis] add new variable and function types

commons/src/main/java/com/powsybl/commons/config/InMemoryPlatformConfig.java, commons/src/main/java/com/powsybl/commons/config/PlatformConfig.java
Yes, fixes #2482 
Note that InMemoryPlatformConfig still creates a config dir. Indeed this PlatformConfig is (only) used in unit tests, and in some of them files are copied into the config dir.
=> PlaftormConfig: config folder not created if non existing

shortcircuit-api/src/main/java/com/powsybl/shortcircuit/AbstractFaultResult.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueValue.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/converter/AbstractTableShortCircuitAnalysisResultExporter.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FortescueValuesSerializer.java, shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisTest.java, shortcircuit-api/src/test/java/com/powsybl/shortcircuit/converter/ShortCircuitAnalysisResultExportersTest.java
No
Replace names: phases are now A,B,C and homopolar are now positive, negative, zero.
=> [Short Circuit API] Replace names in FortescueValue

iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractComplexIdentifiableXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractIdentifiableXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractSimpleIdentifiableXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractSwitchXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AliasesXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BatteryXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusbarSectionXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ConnectableXmlUtil.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/DanglingLineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/GeneratorXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/HvdcLineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LccConverterStationXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LoadXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/PropertiesXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ShuntXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/StaticVarCompensatorXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/SubstationXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TwoWindingsTransformerXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VscConverterStationXml.java
No but it has been discussed in PR about replacing DanglingLine by HalfLine
Refactoring (XIIDM serialization) to be less strict for complex equipments (shunt compensators and in the future, tie lines)
Might create issues in extensions serialization elsewhere
=> Refactoring XML IIDM serialization classes

contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/IdentifierContingencyList.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/json/IdentifierContingencyListDeserializer.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/json/IdentifierContingencyListSerializer.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/NetworkElementIdentifierContingencyListTest.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/json/NetworkElementIdentifierContingencyListJsonTest.java, contingency/contingency-api/src/test/resources/identifierContingencyList.json, contingency/contingency-api/src/test/resources/identifierContingencyListv1_0.json
No
Feature
I removed the `identifiableType` from `IdentifierContingencyList` because it forbid to create hybrid contingency list (for instance a generator and a line) which is a valid use case.
(if any of the questions/checkboxes don't apply, please delete …
=> Remove useless identifiableType from IdentifierContingencyList

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/ShuntCompensatorPositionAction.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/ShuntCompensatorPositionActionBuilder.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisJsonModule.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/ShuntCompensatorPositionActionDeserializer.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/ShuntCompensatorPositionActionSerializer.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java, security-analysis/security-analysis-api/src/test/resources/ActionFileTest.json, security-analysis/security-analysis-api/src/test/resources/ActionFileTestV1.0.json
No
Feature: create action to change shunt compensator position
No
=> Create action to change shunt compensator position

sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisParameters.java, sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/JsonSensitivityAnalysisParameters.java, sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/SensitivityAnalysisParametersDeserializer.java, sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/SensitivityAnalysisParametersSerializer.java, sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisParametersTest.java, sensitivity-analysis-api/src/test/resources/SensitivityAnalysisParameters.json, sensitivity-analysis-api/src/test/resources/SensitivityAnalysisParametersV1.0.json, sensitivity-analysis-api/src/test/resources/SensitivityAnalysisParametersV1.0Invalid.json, sensitivity-analysis-api/src/test/resources/SensitivityAnalysisParametersWithExtension.json
Add parameters discussed in issue  https://github.com/powsybl/powsybl-core/issues/2496
=> Add sensitivity threshold parameters

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
No
Bug fix
NPE when trying to export in CGMES a network containing a voltage level without substation.
A fictitious substation is created in the CGMES file containing all voltage levels without substation. …
=> Create a fictitious substation during CGMES export when a voltage level does not have a substation

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractCompoundScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalableAdapter.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalingContext.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalingParameters.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/StackScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/UpDownScalable.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/DanglingLineScalableTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/GeneratorScalableTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/LoadScalableTest.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalableTest.java
No
Bug fix: adds a boolean saying whether the terminal should be reconnected in case of scaling on a disconnected element.
The terminal is always reconnected.
=> Introduce ScalingParameters for Scalable

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportProfilesConsistencyTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportTest.java
No
Clean: delete unused option, rename with simpler names and order options by alphabetical order.
No
=> Clean of CGMES options

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
No
Bug fix
Busbar sections getters in node-breaker view can return a non-null busbar section if it exists even if it is not in their voltage level
Busbar sections getters in node-breaker view return null if the busbar section exists in another voltage level …
=> Fix: BusbarSection getters in node-breaker view only return a non-null BusbarSection if it is in their voltage level

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
No
Bug fix
`ClassCastException` when `network.getIdentifiableStream(IdentifiableType.BATTERY)`
=> Fix identifiable stream

sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisParameters.java
Fix doc for sensitivity thresholds
=> Fix doc for sensitivity thresholds

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLine.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineTest.java, iidm/iidm-modification/src/test/resources/eurostag-replace-tee-point-by-voltage-level-on-line-bb.xml
Bug fix
Creating a modification "replace tee point by voltage level on line" with wrong bus bar section is not sending an exception and provoke an unexpected behaviour
Creating a modification "replace tee point by voltage level on line" with wrong bus bar section is throwing an exception
=> Creating an modification with wrong bus bar section now throws an exception

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLine.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevel.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevelTest.java, iidm/iidm-modification/src/test/resources/eurostag-remove-voltage-level-nb.xml
No
Bug fix
The breakers and disconnectors are not removed.
In RemoveHvdcLine: the switches of the HVDC line and of the shunts are removed.
In RemoveVoltageLevel: the switches of branches in other voltage levels are removed. 
the converting stations of HVDC lines on the other side are removed.
=> [Network modifications] Fix: Remove disconnectors and breakers in RemoveHvdcLine and RemoveVoltageLevel

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java
No
Fix old regression: listeners were notified before invalidating cache, leading to inconsistencies in connectivity in methods called if checked
No
=> Notify listeners after invalidating cache when switches' status is updated: connectivity is then correctly taking the update into account

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/TieFlowEq.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
No
Bug fixes
Not consistent with quality of CGMES dataset
- when creating or referencing TN for disconnected switches, naming strategy is called
- Name is truncated to 32 characters in CGMES export (Quality check) 
- store all topological nodes in context to write all SvVoltage 
- Add netInterchange for control areas
- Add TieFlow.positiveFlowIn 
- neutralU in RTC and PTC is ratedU
No
=> Cgmes export fixes

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLine.java
Bug fix
converterStation.getId() is called after the station had been deleted.
We store the id and the converter station type before the station is removed.
No
=> Fix hvdc removal reporting

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
Bug fix
The report severity for a removedVoltageLevelReport or removedHvdcLineReport is ERROR_SEVERITY
The report severity for a removedVoltageLevelReport or removedHvdcLineReport should be INFO_SEVERITY.
No
=> Fix severity for remove vl or hvdc reports

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BusTopologyPoint.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NodeTopologyPoint.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TopologyPoint.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTopologyPointImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTerminal.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTopologyPointImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TerminalExt.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/MoveConnectableNotifTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLoadTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMoveConnectableNotifTest.java
No
Bug fix
moveConnectable emits a event when a listener is connected, but this is just a String and not formatted in a way it could be easily parsed. 
moveConnectable emits a `TopologyPoint` object as a value containing all information about the new connection point.
=> Improve move connectable notification

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java, iidm/iidm-api/src/test/java/com/powsybl/iidm/network/util/SVTest.java
Feature
Dc approximation is not supported in the SV class.
Dc approximation is supported in the SV class. When there is not enough information to calculate all the values on the other side, the Dc approximation is calculated if the `p` and `a` are defined.
=> SV: support of DC approximation

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/EqOnlyConversionTest.java, cgmes/cgmes-conversion/src/test/resources/t-line.xml, commons/src/main/java/com/powsybl/commons/parameters/Parameter.java
Bug fix to import T-Point (inside Line container) correctly from CGMES Bus-Branch.
On current version, T-Point are imported as dangling lines.
No
=> Fix handling of T-Point during CGMES Bus-Branch import

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
No
Bug fix
During state variable export, tie lines are processed as branches and as tie lines.
During state variable export, tie lines are processed only one time.
=> Fix StateVariableExport following branch changes

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLine.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveHvdcLineTest.java
This is a fix only visible in the persistent implementation of the iidm model, dealing with a known issue: we try to access an equipment after its deletion. This procudes an exception in powsybl-network-store (_Object has been removed in current variant_). Its happens in method removeShuntCompensators().
Because it is not visible in powsybl-core, there is no specific test to show this issue.
=> Fix post-removal shunt compensator access

.github/workflows/maven.yml
No
Feature
Full sonar analyses are only performed on `main` and `release-v**` branches.
Full sonar analyses will also be performed for `full-sonar-analysis-**` branches.
**This PR is not sufficient.** To have full sonar analyses on these branches, the pattern must also be added to the "long-living branches" definition in the SonarCloud project.
(To have a full report, the analysis must be performed on a branch and not a PR - this is the purpose …
=> New name pattern for full Sonar analyses

math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java, math/src/test/java/com/powsybl/math/matrix/DenseMatrixTest.java
No
Bug fix
When we create large dense matrices we may encounter the maximum allowed size which is dependent of Java max integer value and unfortunately it silently fail because of an integer overflow. The buffer capacity is allowed without any error but with max integer value and later on we end up when setting element value to an index out of bound issue.
We throw an exception if the created dense matrix is too large.
=> Check dense matrix max element count

README.md
No
Doc fix
The the proxy configuration is false in the Maven Wrapper documentation.
Fixes the proxy configuration in the Maven Wrapper documentation
=> Fix the Maven Wrapper doc (proxy configuration)

shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueValue.java
No
Bug fix (?)
The method toThreePhaseValue is package private so inaccessible.
The class is public
=> [Shortcircuit API] Make the method toThreePhaseValue public in FortescueValue

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
Fixes #2650
Feature
No user-friendly method returns the dangling line on other side of a tie line.
A utility method returns an `Optional` corresponding to the dangling line on the other side of a tie line.
=> Add a utility method to find the optional other side dangling line

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
Feature
When 2 dangling lines have the same id, if one or two of them don't have a `ucteXnodeCode`, they are merged into a tie line during networks' merge.
If 2 dangling lines have the same id, regardless of their `ucteXnodeCode`, the networks' merge will fail.
=> Remove dangling lines merge by ID

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
…te validationLevel
No
Bug fix
- An EQ network can be merged in a network with SSH as minimal validation level
- The validation level of the network is **not** updated after a merge
- An exception is thrown when trying to merge an EQ network in a network with SSH as minimal validation level
- The validation level of the network is updated after a merge
=> Validation level management when merging networks

ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java, ucte/ucte-converter/src/test/resources/lineBetweenTwoXnodes.uct
No
Error message improvement
When we have a line between 2 xnodes in a UCTE file, we get an error message but without the information of the 2 xnodes.
We have the name of the 2 xnodes.
=> Improve error message for lines between 2 Xnodes

commons/src/main/java/com/powsybl/commons/compress/ZipHelper.java, commons/src/main/java/com/powsybl/commons/config/ModuleConfigRepository.java, commons/src/main/java/com/powsybl/commons/config/PlatformConfig.java, commons/src/main/java/com/powsybl/commons/config/PlatformConfigNamedProvider.java, commons/src/main/java/com/powsybl/commons/xml/XmlWriterContext.java, computation/src/main/java/com/powsybl/computation/SimpleCommand.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Importer.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactory.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractMultiVariantConnectableExtension.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDeviceBuilder.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ConnectableXmlUtil.java, iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlWriterContext.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java, math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java, math/src/main/java/com/powsybl/math/matrix/Matrix.java, shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitParameters.java
Quality
`@Deprecated` annotations without "since" and/or "forRemoval" arguments
Version number `(since = "X.Y.Z")` added to `@Deprecated` annotations
=> Java S6355 rule: add arguments to @Deprecated annotations

itools-packager/pom.xml
TODO is this really the right thing to do ? Someone needs to look into it a bit..
This fixes the new maven 3.9.2 warning:
[WARNING]
[WARNING] Plugin validation issues were detected in 1 plugin(s) [WARNING]
[WARNING]  * com.powsybl:powsybl-itools-packager-maven-plugin:5.4.0-SNAPSHOT
[WARNING]   Declared at location(s):
[WARNING]    * com.powsybl:powsybl-distribution-core:5.4.0-SNAPSHOT (pom.xml) @ line 492
[WARNING]   Used in module(s):
[WARNING]    * com.powsybl:powsybl-distribution-core:5.4.0-SNAPSHOT (pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-repository-metadata:3.8.5, org.apache.maven:maven-artifact:3.8.5, org.apache.maven:maven-settings-builder:3.8.5, …
=> itools-packager, add scope provided for dependency on maven-core

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_NL_v2_switch_without_name/MicroGridTestConfiguration_BC_NL_EQ_V2.xml, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
Feature.
The `name` is a required attribute for most identified objects. According to the CGMES standard documentation and QoCDC rules (3.3.1) it may be omitted for `ACDCTerminal` instances.
We have decided to relax the requirement and let the name to be optional for switches, after observing this modelling it in a real-world case.
=> CGMES import: switches may not have a name attribute

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
feature
The unitary test to check that bot tap steps are exported to the SV file does not work properly as the cmges import process obtains the tap position from the SSH file if it is not present in the SV file.
The test verifies that the SV file contains a svTapStep record for each ratio and phase tap changer defined in the network model
=> CGMES fix export SV unitary test when ratio and phase tap changer are present

ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfNetworkFactory.java, ieee-cdf/ieee-cdf-converter/src/test/resources/ieee118cdf.xiidm
No
Bug fix
Nominal voltage coming from Matpower IEEE 118 case are not correct (https://matpower.org/docs/ref/matpower5.0/case118.html)
Nominal voltage have been fixed to be conform to Matpower ones. 
=> Fix IEEE 118 nominal voltages

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_NL_v2_switch_type_preserved/MicroGridTestConfiguration_BC_NL_EQ_V2.xml, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_NL_v2_switch_type_preserved/MicroGridTestConfiguration_BC_NL_SSH_V2.xml, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_switch_type_preserved/MiniGridTestConfiguration_BC_EQ_v3.0.0.xml, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_switch_type_preserved/MiniGridTestConfiguration_BC_SSH_v3.0.0.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SwitchEq.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/SwitchExportTest.java, cgmes/cgmes-model/src/main/resources/CIM14.sparql
Bug fix
Switch types with no direct mapping to IIDM kinds are exported back using the generic `Switch` class.
XIIDM files saved with previous versions used the alias type "Terminal" for recording the dangling line network terminal (paired dangling lines were not saved, only their tie lines). Now all dangling lines are saved in the XIIIDM file, with the tie lines referring to them. To have uniform treatment of aliases all equipment, including dangling lines, save their first terminal in the alias "Terminal1". The terminal reference read from old XIIDM files was lost. 
Original type (class name) …
=> CGMES: preserve original switch type and use it for export; update alias type for terminals of DLs

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalableAdapter.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/StackScalable.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/UpDownScalable.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/UpDownScalableTest.java
`UpDownScalable` throws an exception in method `getSteadyStatePower`.
GSLK module in powsybl-entsoe creates up/down scalables. Some of the features in GSLK fail if we do not allow scaling on these objects.
Because `UpDownScalable` delegates in its `upScalable` or `downScalable` inner objects to perform the scaling, it seems to make sense to delegate also the `getSteadyStatePower` method to the proper sub-object. The sub-object is selected depending on the `asked` parameter of the scaling, so to do the proper delegation we must pass …
=> Proposal for handling UpDown scalable get steady state power instead of throwing exception

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
=> Clean CGMES export with subnetworks

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
Fixes #2700 
A new parameter has been introduced. Set `iidm.import.cgmes.import-node-breaker-as-bus-breaker = true` to force the model be imported as bus/breaker (TP instance file is required).
=> CGMES option to force import of node/breaker as bus/breaker

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeSides.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
No
Feature
Add conversion material for integer to ThreeSides and ThreeSides to integer.
No
=> ThreeSides to integer conversion helper in enum

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactory.java, iidm/iidm-api/src/test/java/com/powsybl/iidm/network/NetworkFactoryMock.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkFactoryImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MergeTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAliasesTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractComponentCalculationBugWhenMergingTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNullPointerWhenRemovingMergedLineBugTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksExplorationTest.java, iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java, ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteExporterTest.java, ucte/ucte-util/src/test/java/com/powsybl/ucte/util/UcteAliasesCreationTest.java
No
Quality
The method to merge several networks was `Network.create(Network...)`.
The method to merge several networks is now `Network.merge(Network...)`, which is clearer.
=> Rename 'Network.create(Network...)' in 'Network.merge(Network...)'

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_line_disconnected_at_boundary_node/MicroGridTestConfiguration_BC_BE_SSH_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesReports.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
Feature
When an equipment (ACLS, switch, 2w transformer, equivalent branch) located at boundary has the terminal at boundary side disconnected, the equivalent injection is set to zero, but there is not way to indicate that it should not be connected at boundary side.
This approach works for an individual grid model (IGM): leaving p0, q0 of dangling line set to zero when the boundary terminal is disconnected is electrically equivalent (a reactive injection at network side would be seen, if this side is connected).
But is creates a problem when the network is merged with another one: the tie line will be considered as connected. 
**What is the new behavior …
=> Disconnect dangling lines disconnected at boundary

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/Cgmes3ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/phaseTapChangerXMin/20210209T1930Z_1D_BE_EQ_9.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
Bug fix.
Error observed when `xMin = 0` for a symmetrical phase tap changer. This resulted in an actual `x = 0` for the neutral tap position, when it should be equal to `transformerEnd.x`. 
According to the standard, `xMin` must be consistent with `transformerEnd.x`. So, if `xMin <= 0` is found in the input, its value will be ignored, and we will be consider `xMin = transformerEnd.x`.
In addition, `xMin` has been deprecated in CGMES 3. This means that one can specify only `xMax` (and phase shift increment / voltage step increment) when defining a linear / non-linear phase tap changer.
**Does …
=> CGMES phase tap changer xMin: optional and consistent with transformer x

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/InterpretedT3xModel.java
Fixes regression that was provoked in #2648
Bug fix
=> Fix regression introduced in #2648 (optional ratedS for 3-winding transformers)

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java
Log message improvement.
CGMES substations connected by transformers are mapped to a single IIDM substation. The log message that prints which substations have been merged has been improved.
CGMES voltage levels connected by switches are mapped to a single IIDM voltage level. The log message that prints which voltage levels have been merged has been improved.
Changed the name of a variable (`record`) that is considered a restricted identifier.
=> CGMES: improve log message for merged containers (substations and voltage levels)

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java, iidm/iidm-api/src/test/java/com/powsybl/iidm/network/TieLineUtilTest.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
No
Bug fix (+ logs)
When merging a network having a tie line between 2 dangling lines of pairing key `k` with another network having a sole dangling line of pairing key `k`, we try to create a tie line between the 2 networks, which prevents the merging (an Exception is thrown).
\+ Nothing indicates when dangling lines cannot be merged.
When merging a network having a tie line between 2 dangling lines of pairing key `k` with another network having a sole dangling line of pairing key `k`, we don't try to create a tie line between the 2 …
=> Fix merging networks with a tie line and a dangling line of same pairing key

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageAngleLimitAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageAngleLimitImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VoltageAngleLimitTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksCreationTest.java
No
Bug fix
Calling `remove()` on a `VoltageAngleLimit` does nothing.
Calling `remove()` on a `VoltageAngleLimit` removes it from its network.
=> Implement VoltageAngleLimit removal

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksCreationTest.java
No
Bug fix
On a subnetwork `n` containing a `VoltageAngleLimit` which identifier is "id", `n.getVoltageAngleLimit("id")` returns `null`.
On a subnetwork `n` containing a `VoltageAngleLimit` which identifier is "id", `n.getVoltageAngleLimit("id")` returns the said `VoltageAngleLimit`.
=> Fix VoltageAngleLimit retrieval by id from a subnetwork

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1NetworkCatalog.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java
`asin` is used to calculate `alfa` in symmetrical phase shifters
Following CGMES documentation, `atan` is used in the formulas to calculate `alfa`.
=> Cgmes import: fix atan in symmetrical phase shifters

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/CgmesDcConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/IslandEndHvdc.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/NodeEquipment.java
Feature
Some dc configurations are not imported.
The issue happens when multiple dc links lie on the same ac bus and the converters on the other dc ends have different ways of connecting to the ac network. All other ends are expected to be connected in the same way: either through transformers or directly to terminal buses, but a mix is not considered.
The following image shows the kind of connection that is not supported:
Because dc links share a common ac bus (the ac bus for converters R1 and R2) the configuration is explored as a group, during conversion. Converters L1 and L2 have …
=> Cgmes Import: HVDC fix lost configurations

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksCreationTest.java
No
Bug fix
If two subnetworks have the same country, then this country is counted twice.
The method should return the exact amount of countries.
=> Correct getCountryCount in SubnetworkImpl

.github/workflows/maven.yml
[Official GitHub blog article](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
Feature
CI was using [setup-java](https://github.com/actions/setup-java/) v1 and [checkout](https://github.com/actions/checkout/) v1
CI is now using setup-java v3 and checkout v4
=> Update CI actions due to node.js v12 deprecation

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
Bug fix
When a CGMES export is prepared, a regulating control identifier is created for every shunt compensator.
When we export a network, we create regulating control identifiers in advance if we do not already have them from a potential CGMES input and the equipment has regulating capabilities active. For shunt compensators, the regulating control identifiers were always created.
Following the same strategy followed for generators and static var compensators, a regulating control identifier is created for a shunt compensator only if voltage regulation is on, or if the regulating terminal is …
=> CGMES export shunt compensators: do not create new regulating controls if not needed

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
No
Bug fix
When exporting an EnergySource, only the name and ID are written.
According to QoCDC 3.3.1, every EnergySource must have an EquipmentContainer referred to, which is the Voltage Level. This information is added to the export.
=> CGMES export: add EquipmentContainer when exporting EnergySource

cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_off_svc_control_v/MicroGridTestConfiguration_T4_BE_EQ_V2.xml, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_off_svc_control_v/MicroGridTestConfiguration_T4_BE_SSH_V2.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionUtil.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/SvcExportTest.java
Bug fix
When importing from CGMES, information about disabled regulation controls for static var compensators is not preserved in the IIDM Network. When the Network is exported back to CGMES (only SSH or full export) the regulating control is not present in the output.
Information about the disabled regulating controls for static var compensators is preserved in the IIDM Network and used in the export. Specifically, its identifier and target value.
=> CGMES. Preserve static var compensator regulating control data even if disabled

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java
Bug fix
The SV export of a CGM did not include power flow values for the equivalent injections of tie lines. Only equivalent injections of dangling lines adjacent to the external boundaries were considered.
The SV export of a CGM also contains power flows for the equivalent injections corresponding to dangling lines that were grouped in tie lines.
Due to current CGMES importer behaviour, the information about equivalent injections and equivalent injection terminals in a tie line is only available if the CGM has been built from separately imported Networks joined as subnetworks. If the CGM is …
=> CGMES: fix CGM export adding equivalent injection power flows at tie lines

cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingSerDe.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesControlAreasSerDe.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSshMetadataSerDe.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSvMetadataSerDe.java, cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangersSerDe.java, commons/src/main/java/com/powsybl/commons/io/TreeDataWriter.java, commons/src/main/java/com/powsybl/commons/json/JsonReader.java, commons/src/main/java/com/powsybl/commons/json/JsonUtil.java, commons/src/main/java/com/powsybl/commons/json/JsonWriter.java, commons/src/main/java/com/powsybl/commons/xml/XmlWriter.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AliasesSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ConnectableSerDeUtil.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/PropertiesSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ReactiveLimitsSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ShuntSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/SubstationSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/VoltageLevelSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/DiscreteMeasurementsSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/LinePositionSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/MeasurementsSerDe.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/SecondaryVoltageControlSerDe.java
No
Feature
`TreeDataWriter::startNodes` expects the arrayFieldName which has to be consistent with the corresponding element name
`TreeDataWriter::startNodes` does not take any argument and gets the array field name from a arrayFieldName/elementFieldName map when writing the first element by a call to `TreeDataWriter::startNodes`
No, this API is not yet released
=> Remove arrayFieldName parameter from TreeDataWriter::startNodes

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/DateParsingTest.java, cgmes/cgmes-conversion/src/test/resources/dateParsing.xml, cgmes/cgmes-conversion/src/test/resources/timeParsing.xml, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
No
Bug fix
In some CGMES files, the fractions of second may be written with more than 6 digits, for instance:
`2023-07-31T00:30:00.0000000Z`
Such a date leads to a DateTimeParseException, and then the caseDate is overwritten with ZonedDateTime.now()
Increasing to maximum the max width (9).
=> Fix CGMES date parsing

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
Bug fix
Static var compensators with `bmin` or `bmax` equal to zero are exported to CGMES with `inductiveRating` or `capacitiveRating` set to `Infinity`.
If `bmin` is equal to zero, export `inductiveRating` as zero.
If `bmax` is equal to zero, export `capacitiveRating` as zero.
=> CGMES export fix static var compensator with bmin = bmax = 0

iidm/iidm-impl/pom.xml, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BusbarSectionPositionImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/CoordinatedReactiveControlImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorEntsoeCategoryImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/HvdcAngleDroopActivePowerControlImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LoadDetailImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ReferencePrioritiesImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ReferencePriorityImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/StandbyAutomatonImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/BusbarSectionPositionImplTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/GeneratorEntsoeCategoryTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/LoadDetailTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/StandbyAutomatonTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractCoordinatedReactiveControlTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractHvdcAngleDroopActivePowerTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractReferencePrioritiesTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractStandbyAutomatonTest.java
=> Precise error and log messages for extensions

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/tools/ConversionToolUtils.java
No
Quality
Typo on `itools convert-network`
`--import-parameters <IMPORT_PARAMETERS>   the importer configuation file`
`--import-parameters <IMPORT_PARAMETERS>   the importer configuration file`
=> Fix typo in ConversionTool argument description

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
Bug fix
Topological node for boundary point of tie line was read from IIDM `TieLine` alias. Now that tie line is only a container of underlying tie lines, this data should be read from the inner dangling lines.
Topological node for boundary point of tie line is read from IIDM property of dangling lines of `TieLine`.
=> CGMES export SV: voltage of tie line boundary node

math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java, math/src/test/java/com/powsybl/math/matrix/SparseMatrixTest.java
https://github.com/powsybl/powsybl-math-native/issues/37
Bug fix
Once `SparseMatrix` has been contructed from array, we cannot anymore add new values or run a decomposition. 
Once `SparseMatrix` has been contructed from array, it is now possible to add new values or run a decomposition. 
=> Fix sparse matrix construction from CSC arrays

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
This PR adds the CGMES file ID to the reporter, enabling their retrieval at a later time.
Currently, there is no straightforward method to retrieve CGMES file IDs after their generation.
The reporter now stores the IDs of the SSH and TP files. These IDs can be accessed post file generation.
=> Add CGMES model ID to reporter

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/GroundConversionTest.java, cgmes/cgmes-conversion/src/test/resources/groundTest.xml
Update unit test resource.
The unit test for CGMES conversion of cim:Ground objects has been reduced to a minimum size.
Only the required objects have been left in the CGMES EQ file.
It contains two `Ground` objects with their corresponding `GroundDisconnector`s. One is declared as normally open, the other is declared as normally closed:
=> CGMES ground conversion: minimize unit test file

iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ControlZone.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ControlZoneImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractSecondaryVoltageControlTest.java
No
Feature
To access to a `ControlUnit` of a `ControlZone` from its id, you need to loop on every `ControlUnit` of the result of `ControlZone.getControlUnits()`.
A convenient method `ControlZone.getControlUnit(String id)` allows a direct access.
No need for the breaking change label since the modified class is not yet released.
**What changes might users need to make in their application due to this …
=> Secondary voltage control: add convenient method

iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerDe.java, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/NetworkSerDeTest.java, iidm/iidm-serde/src/test/resources/skippedExtensions.xml, iidm/iidm-serde/src/test/resources/xsd/terminalMockNoSerDe.xsd
No
Bug fix
Extensions not included in ImportOptions are skipped when deserializing, but then we try to read it anyway, leading to an exception.
Extensions skipped with ImportOptions are skipped
=> Fix deserialization bug in skipped extensions

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/AutomationSystem.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OverloadManagementSystemImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractOverloadManagementSystemTest.java
No
Bug fix
There is no way to remove an overload management system from a network. The `OverloadManagementSystem.remove()` method was forgotten.
Add the missing `OverloadManagementSystem.remove()` method.
Not a breaking change since the `OverloadManagementSystem` class is not yet in a production release, …
=> Add overload management system removal (missing method)

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
No
Bug fix
If no step has alpha or rho equal to 1 then the step with the highest position is returned.
Now the function returns the step where rho or alpha is the closest to 1.
=> CGMES: Correct neutral step calculation for tap changers

iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_12.xsd, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/EquipmentXsdTest.java
Bug fix
`equipment_V1_12.xsd` is inconsistent with `iidm_V1_12.xsd`: operational limits are not correctly modelled.
The operational limits model in `equipment_V1_12.xsd` is consistent with `iidm_V1_12.xsd`.
Other problems were fixed:
- missing `ground` element in `VoltageLevel`;
- missing `regulatingTerminal` element in `VscConverterStation`;
- missing `property` element in `CalculatedBus`;
- missing `voltageAngleLimit` in `Network`.
Add a unit test to check the consistence of "equipment_iidm" XSD with "iidm" XSD.
**Does this PR …
=> Fix equipment_V1_12.xsd

iidm/iidm-reducer/pom.xml, iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducer.java, iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/DefaultNetworkReducerTest.java
no
Fix multiple issues regarding the replacement of VSC stations regulating voltage by generators when reducing HVDC lines : generator voltage regulation status and targetV, reactive limits, sign of P and Q 
=> Fix vsc replacement by regulating generator

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ActivePowerLimitsAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ApparentPowerLimitsAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CurrentLimitsAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupsImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupImplTest.java
No
Bug fix
It is not possible/easy to directly instantiate a `CurrentLimitsAdderImpl` (for instance to add limits in an extension) because its constructor takes a `OperationalLimitsGroupImpl` which is protected since the operational limits refactoring.
The following classes are now public:
- `ActivePowerLimitsAdderImpl`;
- `ApparentPowerLimitsAdderImpl`;
- `CurrentLimitsAdderImpl`;
- `OperationalLimitsGroupImpl`;
- `OperationalLimitsGroupImpl.PermanentLimitInfo` (record);
- `OperationalLimitsGroupImpl.OperationalLimitsInfo` (record). …
=> Fix the visibility of the XxxLimitsAdderImpl classes

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
No
Bug fix
When merging 2 networks, the order of the dangling lines of the created tie lines is not always the same.
Because of that, the networks merge is not reproducible.
When merging networks, the dangling lines of each created tie lines are sorted by lexicographical order of their ID
( `tieline.getDanglingLine1().getId() < tieline.getDanglingLine2().getId()`).
**What changes might users need to …
=> Sort the paired dangling lines when merging networks

cgmes/cgmes-conversion/pom.xml, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RemoveGroundsPostProcessor.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/GroundConversionTest.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
Feature
CGMES `Ground` objects are always imported and left in the IIDM `Network`.
Some users may not want to have `Ground` objects imported.
A post-processor to remove all `Ground` objects has been added. 
The `Ground` objects and their paths connecting them to the rest of the network will be removed, including potential CGMES `GroundDisconnector` objects that were imported as switches of kind `Disconnector`.
To activate the feature configure a post-processor with name `RemoveGrounds`.
**What changes might users need to make in …
=> CGMES post-processor to remove grounds

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/ReferenceDataProvider.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/ModelIdTest.java
No
Bug fix: the ID of the EQ, TP, SSH and SV FullModel should be unique, this implies adding business process in the string used to generate the UUID. 
Business process parameter does not exist, ID is not unique.
ID is not unique yet but it completes PR #2888.
=> [CGMES export] New business process parameter

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/BusbarSectionTerminalsExportTest.java
Fixes #2885
When CGMES data is imported to IIDM bus/breaker model the terminals of all busbar sections inside a given CGMES Topological Node are stored in a property of the corresponding IIDM bus. The SSH and TP export modules use this property to write data about the busbar sections that have not been explicitly modelled in IIDM.
=> CGMES. Updated export of busbar section terminals

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/ConsiderValidMasterRIDWithLeadingUnderscoreTest.java
Bug fix
The issue was raised when exporting an updated SSH of an IIDM network that had valid UUID in its identifiables, but prefixed with an underscore. When the SSH was exported using the `cgmes` naming strategy, these prefixed identifiers were considered not valid and "fixed": replaced by newly created ones. This meant that the references to the original objects in the CGMES EQ instance file were lost.
UUIDs with a leading `"_"` character are considered valid Master Resource Identifiers.
A specific unit test to check the scenario where the issue was first raised has been added.
=> CGMES. UUIDs with a leading underscore are considered valid master resource ids

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/LoadScalableTest.java
No
Bug fix (handle the case when Scaling a load with P0=0 and constantPowerFactor = true).
The calculated new Q0 value will be NaN because of dividing by P0=0. Which will make setQ0() throw an error.
The value of Q0 is not updated ant stays as is, instead of throwing an error.
=> LoadScalable: Do not apply constant power factor if P0 is zero

ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplExportConfig.java, ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplExporter.java, ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java, ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java, ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModelExecutionHandler.java, ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplParameters.java, ampl-executor/src/main/java/com/powsybl/ampl/executor/EmptyAmplParameters.java, ampl-executor/src/test/java/com/powsybl/ampl/executor/SimpleAmplParameters.java
Signed-off-by: Hugo Marcellin <hugo.marcelin@rte-france.com>
It allows to tune AMPL Converter network export in order write equipments alphabetically sorted in the output, the feature is optional and is enabled through a new parameter added to AmplExportConfig
This PR also adds the ability to tune AMPL Converter network export by passing the desired configuration through AMPL Executor 
Currently the output order of AMPL Converter is inconsistent 
Equipments may be alphabetically sorted by their id through the AMPL export …
=> [AMPL Converter] Add export sorting option

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
Update
CGMES import code contains references to parameters that are not used anymore.
The code handling the parameter `iidm.import.cgmes.allow-unsupported-tap-changers` have been removed. This parameter is not used in the current conversion from CGMES to IIDM.
Internal parameters containing low impedance threshold in conversion config have also been removed.
The parameter `change-sign-for-shunt-reactive-power-flow-initial-state` has also been removed.
The default value for parameter `create-active-power-control-extension` has been set to `true`.
The documentation has already been updated.
=> CGMES import. Remove obsolete parameter and methods from config

contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyBuilder.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyDeserializer.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencySerializer.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/ContingencyTest.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java, contingency/contingency-api/src/test/resources/contingenciesWithOptionalName.json
This PR add an optional Name in core Contingency for powsybl-open-rao to be able to use directly core Contingency knowing that a name is mandatory for rao. 
This is part of the issue: https://github.com/powsybl/powsybl-core/issues/2868
=> Add name in contingency for open rao

time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/AbstractMinMaxNodeCalc.java
No
Feature
AbstractMinMaxNodeCalc implements directly NodeCalc
AbstractMinMaxNodeCalc now extends AbstractSingleChildNodeCalc
=> AbstractMinMaxNodeCalc extends AbstractSingleChildNodeCalc

tools/src/main/java/com/powsybl/tools/AbstractVersion.java, tools/src/main/java/com/powsybl/tools/Version.java, tools/src/test/java/com/powsybl/tools/VersionTest.java
No
https://github.com/powsybl/powsybl-core/pull/2778 introduced a regression when displaying the Powsybl versions. 
For example, when running the network-store-server, it displays: 
```
2024-02-27T15:17:48.777+01:00  INFO 522297 --- [           main] c.p.n.s.s.NetworkStoreStartupRunner      : Powsybl versions:
+-----------------------+-----------------------+------------+------------------------------------------+------------------------+
| Repository name       | Maven project version | Git branch | Git version                              | Build timestamp        | …
```
=> Fix build timestamp when displaying powsybl version

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/BusbarSectionConversionTest.java, cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_EQ.xml, cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_TP.xml, cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_TP_withoutLinkToTN.xml, cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_TP_withoutTN.xml
Bug fix
Import of bus/branch models containing busbar sections without an association to a topological node raise an exception because no container can be determined for the busbar section.
The container is needed to find a bus where we could store the identifier of the busbar section terminal, that is required in SSH, TP files for updated exports.
If we can not determine the container for a busbar section we will ignore it, and we will not store its terminal. If the busbar section is missing a topological node, there will be no bus where we could store it. …
=> CGMES. Fix access to busbar section container in bus/breaker import

sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java
Extend the sensitivity API by adding a new enum in SensitivityFunctionType, BUS_REACTIVE_POWER
It can be used to request the sensitivity of the total  reactive injection at a bus, for example to a change in a targetV in the network.
DQInj/DtargetV cannot be implemented at this time because the enum is missing.
- [ X] The migration steps are described in the following section
Developers using the SensitivityFunctionType in …
=> Add a new enum value for sensitivity function (bus reactive power)

action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/AbstractBranchActionExpressionNode.java, action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/ActionExpressionEvaluator.java, action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/ActionExpressionHelper.java, action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/AllOverloadedNode.java, action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/IsOverloadedNode.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Branch.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LimitViolationUtils.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectableBranch.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolation.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetector.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/Security.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/DefaultLimitViolationDetector.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/LimitViolationDeserializer.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/LimitReduction.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorForThreeWindingsTransformerTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/limitreduction/LimitReductionListTest.java, security-analysis/security-analysis-api/src/test/resources/LimitReductions.json, security-analysis/security-analysis-api/src/test/resources/PostContingencyResultTest.json, security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisResult.json, shortcircuit-api/src/test/java/com/powsybl/shortcircuit/TestingResultFactory.java
No
Feature
Limit reduction values are in **float** format in:
- `LimitViolation`;
- `LimitReduction`;
- the methods taking a limit reduction value in `LimitViolationUtils`, the action DSL and in the API's equipment classes.
Limit reduction values are in **double** format.
- …
=> Use double format for limit reduction values

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLine.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractDanglingLineTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
No
Feature
Once a dangling line is created, it is not possible to change its pairing key.
A setter is available to change the pairing key of a dangling line after its creation.
In this PR, the setter throws an exception if the dangling line is already paired.
In a future PR, if the dangling line is already paired, changing its pairing key will unpair it and possibly pair it with another dangling line having the same pairing key. But this raises a lot of questions and the wanted behavior should be clarified before.
**Does this PR …
=> Add a pairing key setter for unpaired dangling line

commons/src/main/java/com/powsybl/commons/json/JsonReader.java
No
Feature
When parsing a JSON network, the thrown exceptions don't show much details.
The thrown exceptions contain more details when possible.
=> More detailed exceptions when parsing a JSON network

iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/IdentifiableCriterion.java, iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/json/IdentifiableCriterionDeserializer.java, iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/IdentifiableCriterionTest.java, iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/json/NetworkElementCriterionModuleTest.java, iidm/iidm-criteria/src/test/resources/criterion/identifiable-criteria.json
No
Feature / bug fix
- When creating an `IdentifiableCriterion` without criterion on network elements or limit durations, you have no choice but to use `null` values (there's only one constructor taking both parameters);
- It is thus possible to create an empty `IdentifiableCriterion` valid for every network element.
- New constructors were introduce taking one or both of criteria. A `null` value could not be used anymore for the criterion parameters.
- It is thus not possible anymore to create an `IdentifiableCriterion` valid for …
=> Reject null values for IdentifiableCriterion

iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/duration/EqualityTemporaryDurationCriterion.java, iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterion.java, iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterionTest.java
No
Feature
- `TemporaryDurationCriterion` sub-classes don't accept 0 value as a valid acceptable duration;
- When not using the `filter(...)` method, `IntervalTemporaryDurationCriterion` processing can be unpractical.
- `TemporaryDurationCriterion` sub-classes now accept 0 value as a valid acceptable duration;
- `IntervalTemporaryDurationCriterion` has now a `asRange()` method returning an Apache commons-lang3 `IntegerRange` representation of its range.
**If yes, …
=> `TemporaryDurationCriterion` improvements

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/limitreduction/LimitReductionDeserializer.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/LimitReduction.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlersTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/limitreduction/LimitReductionModuleTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/limitreduction/LimitReductionBuilderTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/limitreduction/LimitReductionListTest.java, security-analysis/security-analysis-api/src/test/resources/LimitReductions.json
No
Feature + doc update
When creating a `LimitReduction` with either a contingency context or a criterion list, every characteristics of a `LimitReduction` must be given as parameter for the constructor. This forces the user to give empty lists to the constructor for the unneeded parameters. 
- Two small constructors are now present for simple cases:
- `LimitReduction(LimitType limitType, double value)`;
- `LimitReduction(LimitType limitType, double value, boolean monitoringOnly)`.
- For more complex cases, a builder was added. …
=> Add a builder for LimitReductions

iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterion.java, iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterionTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/limitreduction/LimitReductionModuleTest.java
No
Feature
The only way to create an `IntervalTemporaryDurationCriterion` is to use the builder (via `builder()` method).
3 convenient static methods `lowerThan(...)`, `greaterThan(...)` and `between(...)`, creating an `IntervalTemporaryDurationCriterion` with one or both bounds, were added.
**Other …
=> Add convenient creation methods for IntervalTemporaryDurationCriterion

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineBoundaryImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java, iidm/iidm-serde/src/test/resources/V1_10/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_11/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_12/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_3/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_4/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_5/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_6/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_7/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_8/danglingLineWithGeneration.xml, iidm/iidm-serde/src/test/resources/V1_9/danglingLineWithGeneration.xml, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/DanglingLineNetworkFactory.java, matpower/matpower-converter/src/test/resources/dangling-line-generation.json
No, but it is a bug fix. In case of unpaired dangling line with a not null generation part, the `Boundary` P, Q, voltage and angle are totally wrong.
This is a quick fix, not ideal. If the dangling line is not paired but with a generation file, we rely on power flow results at network side to retrieve the good value at boundary side.
**What changes might users need to make in their application due to …
=> Fix flows, voltage and angle at Boundary if generation present

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowParametersTest.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/json/JsonLoadFlowParametersTest.java, loadflow/loadflow-api/src/test/resources/LoadFlowParametersVersion17.json, loadflow/loadflow-api/src/test/resources/LoadFlowParametersVersion18.json, loadflow/loadflow-api/src/test/resources/LoadFlowParametersVersion19.json
No
Bug fix
The `hvdcAcEmulation` option is not read from the LF parameters **yaml** config file. The default value is always used.
The `hvdcAcEmulation` option is read from the LF parameters yaml config file.
=> Fix hvdcAcEmulation option loading from a yaml config file

time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeries.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTest.java
No
Feature/Bug fix
Since v6.3.0, the `parseCsv(BufferedReader reader, TimeSeriesCsvConfig timeSeriesCsvConfig)` needed a ReportNode as third parameter.
For convenience, a static method `parseCsv(BufferedReader reader, TimeSeriesCsvConfig timeSeriesCsvConfig)` is again available.
=> Add back static method parseCsv without ReportNode for TimeSeries

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java
Bug fix
Unit tests for transformer conversion are looking for specific transformers in the network by id. Hardcoded ids with a prefixed underscore are used.
But current conversion uses CGMES mRIDs as identifiers, that do not use prefix underscore.
As a result, transformers are not found in the network.
The tests tried to compare expected and actual flows in terminals of transformers. When the transformer is not found, the flows are initialized to `NaN` values.
The comparison between expected and actual flows does not take into account potential `NaN` values.
**What is the new behavior (if …
=> CGMES unit tests for transformer conversion

.github/workflows/maven.yml
No
Feature
CI is often not launched on version commit, as the "prepare release" pull request contains two commits which are often pushed at once. The CI is then launched only at the latest commit ("Bump to X.Y.Z-SNAPSHOT version") and not the the first one ("Bump to X.Y.Z version")
The CI is launched when the added tag "vX.Y.Z" is pushed
=> Launch CI when new version tag is pushed

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/LegacyCommonGridModelExportTest.java
Bug fix
Modelling authority set in the metadata models by an external user is always overwritten with the default value of the corresponding export parameter.
Modelling authority set in the metadata models is overwritten only if a specific value has been set through parameters. If the parameter has the default value, the metadata models are not modified, and its modelling authority will be used in the export.
=> CGMES export fix: modelling authority must be preserved

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SlackTerminal.java
No
Bug fix
`SlackTerminal.isEmpty()` is used in some places to check if the terminal is present for the current variant. But when this method returns `false`, the terminal may still be `null` since this method's purpose is to check if the extension is used for at least one variant (see [SlackTerminal.setTerminal(Terminal terminal, boolean cleanIfEmpty)](https://github.com/powsybl/powsybl-core/blob/f8ef9c6cc61ab4ad521fdaa347092b2b6b39b15e/iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SlackTerminal.java#L95)). …
=> Fix SlackTerminal.isEmpty misuses

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStation.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStationAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimits.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimitsAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChangerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GenerationAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorLinearModelImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationImpl.java
No
Quality / Feature
- Public methods have as argument the validation level and not the boolean that says if we want to log an error or an exception. This will lead to adaptations in the network-store. C++ implementation must be checked. 
- When loss factor is not defined, the network falls in EQUIPMENT validation level.
**What changes might users need to make in their application due to this PR? …
=> IIDM Validation Util rework 

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
No
Bug fix
When writing a SvInjection for a fictitious load, the Id of the bus is used for the topological node reference, without regards to the naming strategy.
The topological node reference is the one of the bus and takes into account the naming strategy.
=> Fix: the fictitious load SvInjection should refer to TopologicalNode UUID

iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/AbstractNetworkReducer.java, iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducer.java, iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducerObserver.java, iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/NetworkReducerObserver.java, iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/NetworkReducerObserverImpl.java, iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/TieLineReductionTest.java
#3026 
Bug fix
When network reduction impact the removal of one of a tie line voltage levels, we remove the tie line (so we un-merge the dangling lines). 
=> Tie lines in network reduction

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Completes the unit test for #3037. 
Checks that the `TopologicalNode` referred in the SV `SvInjection` for the slack bus mismatch is present in properly defined inside the exported TP instance file.
=> CGMES SvInjection for slack unit test: referred topological node must be defined

commons/src/main/java/com/powsybl/commons/parameters/Parameter.java, commons/src/test/java/com/powsybl/commons/parameters/ParameterTest.java
No
Feature
`Parameter` class has now an new optional free-string attribute `categoryKey`, corresponding to a business key which is meant to group together the parameters concerning a same topic.
This feature was extracted from #3032.
=> Add an optional category in parameters

docs/grid_features/extraction.md, docs/grid_features/index.md
Documentation update.
This PR adds documentation about the network extraction from the website to readthedocs.
=> Add network extraction feature in documentation

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineBoundaryImpl.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineData.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TieLineTest.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java
No. We have:
- A dangling line (paired or unpaired)
- May have a generation part or not.
- Has zero impedance (X = 0, R = 0).
Bug fix
Values at boundary are not calculated correctly when  dangling lines have zero impedance.
Calculations of boundary magnitudes in IIDM boundary implementation and `DanglingLineData` now have support for zero impedance.
Zero impedance check for dangling lines is kept at `DanglingLineData`.
Zero impedance paired dangling lines (inside tie lines) are also calculated correctly. …
=> Boundary P, Q, angle and voltage with zero impedance 

docs/grid_model/extensions.md, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/OperatingStatus.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractOperatingStatusTest.java
No
Feature
OperatingStatus in-memory implementation cannot be added on a busbar section (no restriction at all on network-store implementation!)
OperatingStatus in-memory implementation can be added on a busbar section
=> Allow OperatingStatus on busbar sections

docs/grid_model/network_subnetwork.md, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Generator.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/GeneratorAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/GeneratorSerDe.java, iidm/iidm-serde/src/main/resources/xsd/iidm_V1_13.xsd, iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_13.xsd, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/AbstractIidmSerDeTest.java, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/GeneratorSerDeTest.java, iidm/iidm-serde/src/test/resources/V1_12/generator.xml, iidm/iidm-serde/src/test/resources/V1_13/generator.xml, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGeneratorTest.java
=> Support of condensers

action-api/src/test/java/com/powsybl/action/ApplyActionToNetworkTest.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/AbstractDisconnection.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ConnectableConnection.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PlannedDisconnection.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/UnplannedDisconnection.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ConnectionAndDisconnectionsTest.java
No
Bug fix
If you use for example a ConnectableConnection on a non-existing connectable or on a TieLine (which is not a Connectable), the application of the NetworkModification will crash due to a null pointer exception
You will now get a PowsyblException if you apply with `throwException==true` or the Network Modification will not be applied and the error will be logged
=> Fix exception for connectable not found in Network Modification connection and disconnection

action-api/src/main/java/com/powsybl/action/TerminalsConnectionAction.java
No
Javadoc fix
Reading the javadoc, you can think that it is possible to use a `TerminalsConnectionAction` to connect or disconnect a tie line or an HVDC line.
The javadoc explicitly states that a `TerminalsConnectionAction` can NOT be use to connect or disconnect a tie line or an HVDC line, since they are not `Connectable`s.
**What changes might users need to make in their application due to this PR? …
=> TerminalsConnectionAction: fix javadoc

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAreaTest.java
No
Bug fix
In #2955 listeners were implemented to automatically delete area boundaries when the undelying equipment is removed from the network (e.g. DanglingLine removal). This was done using "cleanup" listeners. However when performing network merge or detach, the listeners are lost / not transfered to the new root network of the Areas.
The "cleanup" listeners are properly moved to the new root Network when merging and detaching.
This is very …
=> Fix area boundary auto-removal with merged and detached Networks

iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/VoltageRegulationSerDe.java, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_10.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_11.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_12.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_2.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_3.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_4.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_5.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_6.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_7.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_8.xsd, iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_9.xsd, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/test/VoltageRegulationSerDeTest.java, iidm/iidm-serde/src/test/resources/V1_12/voltageRegulationCompatibilityVersion.xml
No
Bug fix
"Historical" versions of the `VoltageRegulation` extension are **not** supported.
"Historical" versions of the `VoltageRegulation` extension are supported.
The `VoltageRegulation` extension was historically a private extension which was added to `powsybl-core`.
When it was …
=> Add historical versions of voltageRegulation xsd for compatibility purposes

docs/grid_model/extensions.md, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControl.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdder.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlAdderImpl.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlImpl.java, iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/ActivePowerControlSerDe.java, iidm/iidm-serde/src/main/resources/xsd/activePowerControl_V1_2.xsd, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java, iidm/iidm-serde/src/test/resources/V1_13/activePowerControlWithLimitRoundTripRef.xml, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractActivePowerControlTest.java
No
Quality / bug fix:
- Better naming of fields.
- Additional checks to avoid inconsistent behaviors.
- `ActivePowerControl` extension has 2 fields `minPOverride` and `maxPOverride`;
- There are no checks on their values.
- `ActivePowerControlExtension`'s fields were renamed:
-  `minPOverride` -> `minTargetP`;
- `maxPOverride` -> `maxTargetP`
- Additional checks were introduced on these fields:
- they should be between `minP` and `maxP`;
- `minTargetP < maxTargetP`. …
=> `ActivePowerControl` extension: Rename optional fields min/maxPOverride -> min/maxTargetP

tools-test/src/main/java/com/powsybl/tools/test/AbstractToolTest.java, tools-test/src/test/java/com/powsybl/tools/test/CommandLineToolsTest.java, tools-test/src/test/resources/com/powsybl/tools/test/tool-output.sh
No
Bug fix
Due to #2777, a regression appeared: it was not anymore possible to use an `assertCommand` with an output and/or error message containing a regex since only strict string comparison were now available
- The old `assertCommand` is back (but deprecated), adapted to the modifications from #2777;
- A new `assertCommandMatchTextOrRegex` method was introduced, doing the same thing but with a clearer name.
**If yes, please check if the following requirements are …
=> Fix regression on assert command for tool tests

psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseTransformerWinding.java
No
The PsseTransformerWinding have properties only having getters but not setters, which limits modeling capability. This PR creates all setters (if not yet exist).
See the point above.
See the point above.
No
=> Open setters for all properties in PsseTransformerWinding class

iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
There are tests that compare Ratio/PhaseTapChanger steps by reference and expect that we keep the same reference for these objects
Reference comparison for steps in TCK
No more Reference comparison for steps in TCK
=> TCK: remove reference comparison for TapChangers step

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
Bug fix
When using a stepsReplacer on a TapChanger, the neutralPosition isn't updated
When using a stepsReplacer on a TapChanger, the neutralPosition is updated
This is not really a breaking change, but a TCK test is added and so, the mainteners of a custom IIDM implementation must make sure that the neutralPosition of the TapChanger is correctly updated when using a …
=> Fix: Update TapChanger neutralPosition after using a stepsReplacer

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesMetadataModelImpl.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/HvdcUtils.java
Yes, https://github.com/powsybl/powsybl-open-loadflow/pull/1062
Method `HvdcUtils::getHvdcLineLosses` has now a public access.
=> Make method to compute hvdc line losses public

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java, commons/src/main/java/com/powsybl/commons/report/TypedValue.java
Bug fix
The identifier of the exported model was written in the `Report` under the key `CgmesId`.
After the recent refactoring of `Report`, only the first `CgmesId` key present in the report could be retrieved, because the exported model identifiers were written as message templates instead of values.
Allow for multiple `CgmesId` values to be present in the `Report` output.
The identifiers of the exported model must be retrieved by looking at the message of each report node, instead to its message template:
```java
// Prepare a root report node
ReportNode report = ReportNode
.newRootReportNode() …
```
=> CGMES export: report multiple model identifiers

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesMetadataModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesMetadataModelImpl.java
Bug fix
Supersedes set in CGMES metadata models (SSH) can not be emptied by the user.
This creates a problem when trying to export CGMES data for a network that is read from CGMES inputs that already specify superseding info. 
In CGM quick export, the previous supersede and the one added automatically during export are present in the output.
In manual export, the user may add a supersede to the model, to prepare the export, but the previous supersede can not be removed. The exported files contains two supersede items.
The CGMES metada model supersedes set in the network extension can be emptied …
=> CGMES metadata models: allow clear of supersedes

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/RegulatingControlEq.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/TapChangerEq.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java, docs/grid_exchange_formats/cgmes/export.md, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/PhaseShifterTestCaseFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/ShuntTestCaseFactory.java, iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/SvcTestCaseFactory.java
Fixes #2920 '
`ACTIVE_POWER` and `CURRENT_LIMITER` are already implemented for PSTs.
=> Cgmes active reactive regulating control

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/Cgmes3ConversionTest.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/CgmesOnDataSourceTest.java
No
Bug fix
- In `CgmesOnDataSource.checkIfMainFileNotWithCgmesData()`, a stream was open without first checking if the file existed, which could result in an unexpected exception.
- In `CgmesOnDataSource.checkIfMainFileNotWithCgmesData()`, we first check if the file exists before trying to open a stream on it.
**What changes might users need to make in their application due to this PR? (migration …
=> Datasources - part 5: fixes

computation/src/main/java/com/powsybl/computation/CompletableFutureTask.java, computation/src/test/java/com/powsybl/computation/CompletableFutureTaskTest.java
NO
bug fix 
When calling cancel(true), the CompletableFutureTask was throwing a NullPointerException in its run method because cancel(true) causes future.get() to throw a CancellationException without a cause (null) and completeExceptionally requires a non null Exception
the exception was thrown to the executor and the very end. Executors usually catch and ignore everything (just logs to stdout) so the problem was just ugly logs and a slight performance drop. But also maybe in some cases an exception with a cause was thrown and the bad exception was used to completeexceptionally the …
=> CompletableFutureTask, fix spurious error logging when cancelling

config-test/src/main/java/com/powsybl/config/test/TestPlatformConfigProvider.java, config-test/src/test/java/com/powsybl/config/test/TestPlatformConfigProviderTest.java, config-test/src/test/resources/com/powsybl/config/test/filelist.txt, config-test/src/test/resources/com/powsybl/config/test/subfolder/subfolder_file.txt
No
Bug fix
If you have files in subfolders in the TestPlatformConfigProvider, the copy of these resources during `getPlatformConfig() ` will fail since the subfolder does not yet exists.
`getPlatformConfig() ` will first create the subfolder and then copy the resources inside of it.
=> Create directory for resources in TestPlatformConfigProvider

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TerminalFinder.java
Feature
In TerminalFinderTest tck test class : methods testLineTerminal1 and testLineTerminal2
These 2 tests succeed here only because the 2 lines "NHV1_NHV2_1" and "NHV1_NHV2_2" are created and attached to the bus "NHV1" before the 2 windings transformer "NGEN_NHV1".
If the transformer is created before the lines, these 2 tests will fail.
And In the network store implementation, these 2 tests also fail.
Regardless of the lines and transformer creation order on the bus, these 2 tests will succeed.
And in the network store …
=> Distinguish between line and 2 windings transformer in TerminalFinder default rules

docs/grid_exchange_formats/ampl/export.md, docs/grid_exchange_formats/cgmes/export.md, docs/grid_exchange_formats/cgmes/import.md, docs/grid_exchange_formats/iidm/export.md, docs/grid_exchange_formats/iidm/import.md, docs/grid_exchange_formats/iidm/index.md, docs/grid_exchange_formats/psse/import.md, docs/grid_exchange_formats/ucte/format_specification.md, docs/grid_exchange_formats/ucte/import.md, docs/grid_features/import_post_processor.md, docs/grid_features/loadflow_validation.md, docs/simulation/shortcircuit/parameters.md, docs/user/itools/index.md
No
Docs update
A lot of sections of the documentation have no anchors so they cannot be referenced to in the documentation of other repositories.
Add some anchors
=> Add anchors in the documentation

docs/grid_exchange_formats/cgmes/import.md
No
Documentation bugfix
incorrect parameter name `iidm.import.cgmes.cgm-with-subnetworks-defined`
correct parameter name `iidm.import.cgmes.cgm-with-subnetworks-defined-by`. Also added precision on default value.
=> Fix CGMES importer documentation of parameter cgm-with-subnetworks-defined-by

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/CgmesOnDataSourceTest.java
NO
Bug fix
can't import a cgmes zip with a dot in the name and not ".xml.zip" as the extension (e.g. microgrid.v2.complete.zip)
can import
This happens when filenames have the 2 following properties:
- the filename contains a dot:
- the filename does not contain the dataextension For example this filename triggers the bug:  "microgrid.v2.complete.zip" but these work:
"microgrid_v2_complete.zip" (because empty dataextension)
or …
=> CgmesImporter, allow importing with wrong dataextension when the mainfile doesn't exist

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ImportConfig.java, iidm/iidm-api/src/test/java/com/powsybl/iidm/network/ImportConfigTest.java
No
Bug and feature 
ImportConfig post processors depending on the way it is built (through load, or different constructor), are a mutable or immutable List.
ImportConfig post processors getter return an immutable List.
A method has been added to add new post processors.
=> Allow adding new post processors on an existing ImportConfig

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesReports.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentBranchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentShuntConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ExternalNetworkInjectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/GroundConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SubstationConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/VoltageLevelConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/AcDcConverterConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/DcLineSegmentConversion.java, cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-invalid-voltage-bus.txt, cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-target-deadband.txt, cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE.txt, cgmes/cgmes-conversion/src/test/resources/functional-logs/miniGridNodeBreaker.txt, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
Implements #3140
Feature
There is some reporting done during CGMES import conversion but the logs are for the moment scattered and not hierarchically organized.
The purpose of that PR is to set a canvas of the main conversion steps in order to add the detailed functional logs.
=> CGMES functional logs (first steps)

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/AbstractLoadFlowDefaultParametersLoader.java
No
Bug fix : the constructor of `AbstractLoadFlowDefaultParametersLoader` was not visible outside its package, so this abstract class couldn't be used in other projects.
=> Its visibility is set to protected.
=> Fix visibility of default LF parameters loader's constructor

security-analysis/security-analysis-api/src/main/java/com/powsybl/security/BusBreakerViolationLocation.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetection.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/NodeBreakerViolationLocation.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/ViolationLocation.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/DefaultLimitViolationDetector.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ViolationLocationDeserializer.java, security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ViolationLocationSerializer.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationDetectionTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/converter/ExporterTest.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/PostContingencyResultTest.java, security-analysis/security-analysis-api/src/test/resources/PostContingencyResultTest.json, security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisResult.json
No
Bug fix
#3153 introduces ViolationLocations for voltage violation.
- In the bus/breaker topology case, the bus id in the `BusBreakerViolationLocation` corresponds to a merged bus. This is not stable depending on the network implementation.
- In the node/breaker topology case, the `NodeBreakerViolationLocation` contains a list of busbar section ids. But in some cases there are no busbar section where the violation is detected.
- The `busId` of `BusBreakerViolationLocation` was replaced by a list of ids corresponding to the …
=> Return stable ids/nodes in ViolationLocation classes

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ProportionalScalableTest.java
No
Bug fix
Infinite loop in proportional scalable under the following condition:
- asking a little bit more power than the full available power range over all scalables
- scalable percentages are low enough so that the difference of asked power minus done power on one scalable falls below the 0.01 MW epsilon
In this case the iteration percentage of the scalable is never set to zero, there is remaining asked power, and the scaling is stuck in an infinite loop.
May sound like a marginal case, but was observed on real data. On large networks a given load may have a small percentage.
**What is …
=> Fix proportional scalable infinite loop

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
=> Fix NPE in network validation

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
No
Fix the javadoc for a method present in the API.
Method description is incorrect.
Method description has been fixed.
=> Fix new internal connection javadoc

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowDefaultParametersLoaderTest.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowParametersTest.java, loadflow/loadflow-api/src/test/resources/LoadFlowParametersUpdate.json
No
Bug 
When loading loadflow parameters from a PlatformConfig, every field of the LoadFlowParameters is either set to the value written in the config or to its default value (if the configuration module `load-flow-default-parameters` is used). 
It is a problem for the `LoadFlowDefaultParametersLoader` mechanism that is meant to change values before the PlatformConfig load.
As a additional related problem, the old `noGeneratorReactiveLimits` parameter (now replaced by `useReactiveLimits`) is ignored: its value is overwritten by the default value of `useReactiveLimits`.
**What is the new …
=> Fix load flow default parameters loading mechanism

math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java, math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java, math/src/test/java/com/powsybl/math/graph/UndirectedGraphImplTest.java
No
Feature
When a listener is added to the graph, when a modification is done on the graph, listener is called.
We can control using a boolean if the listeners are called or  not.
=> UndirectedGraph notification deactivation

cgmes/cgmes-model/src/main/resources/CIM100.sparql
Not, but we discovered the issue in slack channel.
Bug fix - CIM 100 condenser import performance regression.
Importing CGMES3 data takes a long time, and most of the time is spent on importing synchronous machines. Activsg70k dataset import takes more than 1 hour.
Activsg70k import now takes 1 minute.
No actions needed.
=> Fix CIM100 CGMES import regression issue on synchronous machine

math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java, math/src/test/java/com/powsybl/math/matrix/DenseMatrixTest.java
This PR adresses multiple needs :
- This issue : https://github.com/powsybl/powsybl-core/issues/3194
- This comment PR in OpenLoadFlow which needs emptyMatrix singleton : https://github.com/powsybl/powsybl-open-loadflow/pull/1095#discussion_r1837873885
- The already existing class MatrixUtil in OpenLoadFlow
This PR introduces 4 new methods in DenseMatrix
- Copying values from another DenseMatrix
- Resetting a specific row of a DenseMatrix
- Resetting a specific column of a DenseMatrix
- Remove small values of a DenseMatrix
It introduces also a new final static object EMPTY for empty matrix. …
=> Add new matrix methods for DenseMatrix

docs/simulation/shortcircuit/parameters.md
No
Docs update
The voltage field of the shortcircuit voltage range parameter is not mentioned in the documentation.
Adds the documentation.
=> [Shortcircuit] Add some documentation about the voltage attribute of voltage ranges.

contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/SwitchContingencyTest.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java, contingency/contingency-api/src/test/resources/contingenciesWith3wt.json, contingency/contingency-api/src/test/resources/contingenciesWithDlAndTl.json, contingency/contingency-api/src/test/resources/contingenciesWithSeveralElements.json
No
Bug fix
Switch contingency type is not fully supported: no validation + no deserialization
Switch contingency type is supported at validation and deserialization.  
\+ add unit tests on other contingency types.
=> Fix switch contingency support

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/OperationalLimitsGroupTest.java
No.
Feature change.
At CGMES import, OperationalLimitSet names and ids are stored in a property of the corresponding identifiable as follows:
- Property name: "CGMES.OperationalLimitSet_\<rdfid\>"
- Property value: "\<name\>"
Since rdfid are globally uniques, this results in the model creating overall as many property keys as OperationalLimitSet. This is an issue in pypowsybl where a huge number of property keys severly alters performances.
At CGMES import, OperationalLimitSet names and ids are stored in a property of the …
=> Store the CGMES id/name of OperationalLimitSet in a unique property

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowParametersTest.java
No
Bug fix
Unable to parse yml because of a typos in parser:
- `dcUseTranformerRatio` instead of `dcUseTransformerRatio` (missing the `s` in Transformer)
- `contriesToBalance` instead of `countriesToBalance` (missing the `u` in countries)
yml correctly parsed
- Detected in a unit test in open-rao
- problems introduced by #3193
=> Fix typos in LoadFlowParameters yml parsing

time-series/time-series-api/src/main/java/com/powsybl/timeseries/IrregularTimeSeriesIndex.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeries.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/IrregularTimeSeriesIndexTest.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTest.java
No
Bug fix
`TimeSeries` can be created with duplicate time index value.
Skipped row when duplicate time index is found during CSV `timeseries` parsing
Throws exception in `IrregularTimeSeriesIndex` if the times array contains duplicate or is unordered
Linked to a practical case in powsybl-dynawo PR [413](https://github.com/powsybl/powsybl-dynawo/pull/413)
=> Handle duplicate timeseries index

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/NodeContainerMappingTest.java
No
Bug fix
Fictitious voltage levels marked as non-fictitious
Fictitious voltage levels marked as fictitious
=> CGMES: fictitious voltage levels marked as fictitious

docs/.readthedocs.yaml
Documentation configuration update: allows to download readthedocs documentation in pdf format.
=> Enable documentation download in pdf format

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java, docs/grid_exchange_formats/cgmes/import.md
No.
Bug fix.
A CGMES GroundDisconnector is imported in IIDM as a `Switch` with kind `SwitchKind.DISCONNECTOR`, which is intended. However, the original CGMES switch type is not saved in the `CGMES.switchType` property in IIDM, and as a consequence it is exported back to CGMES as Disconnector instead of GroundDisconnector.
GroundDisconnector CGMES switch type is saved in IIDM during import. Thus, GroundDisconnector can be reexported as such in CGMES.
**Other …
=> Save GroundDisconnector CGMES switch kind in a property

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractTransformerConversion.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/WindingType.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/WindingTypeTest.java
No.
Refactoring.
During CGMES conversion of a CIM16 file (CGMES 2.4.15), `WindingType` class is using Terminal.sequenceNumber to classify and sort the windings as PRIMARY/SECONDARY/TERTIARY. However, sequenceNumber isn't fetched by the SPARQL query and therefore is never used in the `WindingType` class. As a consequence, WindingType.windingType always returns PRIMARY for CIM16 Propertybags.
This is not an issue because another sort is done in the CGMES import using PowerTransformerEnd.endNumber, giving the correct classifications of windings for CIM16 files, but this additional sorting …
=> Use PowerTransformerEnd.endNumber to sort transformer windings

docs/simulation/security/index.md
Missing documentation about some possible remedial actions available in the repository.
Need to add a link to the powsybl-open-loaflow documentation about the actions implemented there.
Add documentation
Incomplete documentation about available security analisys remedial actions inputs.
All the remedial actions are now documented in the docs and a link is set to the OLF documentation about there implemented actions.
**If yes, please check if the following requirements …
=> Complete docs about implemented remedial actions

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
No.
Refactoring.
At CGMES import, if the Switch kind doesn't have a direct map to IIDM, i.e. if its class is: Switch, ProtectedSwitch, GroundDisconnector, Jumper, then its CGMES original class is stored in a CGMES.switchType property. The purpose is to be able to export back to CGMES the object with the correct class.
Similarly, at CGMES import, the original CGMES class of load or generator is stored in a CGMES.originalClass property.
For consistency purposes, drop the use of CGMES.switchType property in favor of CGMES.originalClass. …
=> Replace CGMES.switchType property by CGMES.originalClass property.

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForGenerators.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForShuntCompensators.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/RegulatingControlEq.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/SvcExportTest.java
No.
Bug fix.
It is allowed in CGMES to define a SynchronousMachine with a ReactiveCapabilityCurve (or just the minQ and maxQ) but no RegulatingControl. It is imported flawlessly in iidm.
For instance, if a SynchronousMachine has no RegulatingControl, and a minQ < maxQ, it is imported with:
- voltageRegulatorOn = false
- no targetV, or rather it is Double.NaN
- no RegulatingTerminal, or rather it is the local supplier
- minQ
- maxQ
But when exporting the network back to CGMES, a RegulatingControl is exported for that SynchronousMachine. The reason is primarily that the SynchronousMachine is …
=> Review conditions of RegulatingControl creation at CGMES export

cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesSubset.java, cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/CgmesSubsetTest.java
Fixes #3295 
Bug fix.
Boundary cgmes subsets were not always clearly identified.
Boundary cgmes subsets are now better identified.
=> Rework condition to better identify boundary subsets

cgmes/cgmes-model/src/main/resources/CIM100.sparql
No.
Bug fix.
SSH graph for CIM100 OperationalLimits query is expected.
SSH graph for CIM100 OperationalLimits query is now optional.
Note that all attributes fetched in the SSH graph are optional, so even though the query is not correct it already works the way it is.
=> Make SSH graph for CIM100 OperationalLimits query optional

cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_with_tie_flow/MicroGridTestConfiguration_BC_BE_EQ_V2.xml, cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_with_tie_flow/MicroGridTestConfiguration_BC_BE_SSH_V2.xml, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java, cgmes/cgmes-model/src/main/resources/CIM16.sparql
No
Improve performance
ControlArea SPARQL query is using a FILTER REGEX clause. This isn't optimal performance-wise.
The query has been slightly changed to use a VALUES clause instead, which gives better performances.
A similar work has been done in https://github.com/powsybl/powsybl-core/pull/3218 to remove the FILTER clause of NonlinearShuntCompensatorPoints qurery.
=> Remove use of filter in controlarea query

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java
No
Bug fix in unit test
Unit test is using XMLStreamReader.getText() which does not ensure that the full content is read.
Unit test is using XMLStreamReader.getElementText() which ensures that the full content is read.
`getText()` was used in another repo to read an xml content, which lead to corrupted data, as it was often cut in two and only the second half of the string was kept. In powsybl-core this is the only place where it's used. It …
=> Replace XMLStreamReader.getText with getElementText in unit test

commons/src/main/java/com/powsybl/commons/report/AbstractReportNodeAdderOrBuilder.java, commons/src/main/java/com/powsybl/commons/report/ReportConstants.java, commons/src/main/java/com/powsybl/commons/report/ReportNodeAdderOrBuilder.java, commons/src/main/java/com/powsybl/commons/report/ReportNodeBuilder.java, commons/src/main/java/com/powsybl/commons/report/ReportNodeChildAdderImpl.java, commons/src/main/java/com/powsybl/commons/report/ReportNodeImpl.java, commons/src/main/java/com/powsybl/commons/report/ReportNodeNoOp.java, commons/src/main/java/com/powsybl/commons/report/ReportNodeRootBuilderImpl.java, commons/src/main/java/com/powsybl/commons/report/TreeContext.java, commons/src/main/java/com/powsybl/commons/report/TreeContextImpl.java, commons/src/main/java/com/powsybl/commons/report/TreeContextNoOp.java, commons/src/test/java/com/powsybl/commons/report/NoOpTest.java, commons/src/test/java/com/powsybl/commons/report/ReportNodeTest.java
No
Remove unused feature
timestamp may be added automatically on all report nodes if specified at root node construction.
timestamp may be added on any report node manually.
Timestamps can not be automatically added on a whole `ReportNode` tree.
If timestamp is needed on a specific `ReportNode`, the user …
=> ReportNode: change timestamp feature

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ReactiveCapabilityCurveImpl.java, iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/ReactiveCapabilityCurveImplTest.java
No
Bug fix
When the lowest point of a reactive capability curve has a `p` equals to `0.0`, calling `curve.getMinQ(-0.0);` leads to a `NullPointerException`.
When the lowest point of a reactive capability curve has a `p` equals to `0.0`, calling `curve.getMinQ(-0.0);` return the `minQ` of the lowest point. …
=> Handle negative zero case in reactive capability curves

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
No.
Bug fix.
When reading a CGMES EQ file that's defining the CIM16 EquimentOperation profile in its header, and when exporting back to CGMES the network, the EquipmentOperation profile is written twice.
```xml
<md:FullModel rdf:about="urn:uuid:ModelID_EQ">
<md:Model.scenarioTime>2021-03-01T23:00:00Z</md:Model.scenarioTime>
<md:Model.created>2025-03-14T09:50:11Z</md:Model.created>
<md:Model.description>Model description</md:Model.description>
<md:Model.version>1</md:Model.version>
<md:Model.profile>http://entsoe.eu/CIM/EquipmentCore/3/1</md:Model.profile> …
```
=> Fix duplicate EquipmentOperation profile in header

loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowDefaultParametersLoaderTest.java
No
Bug fix
When `load-flow` module is defined in configuration but the `default-parameters-loader` property is absent, an exception is thrown when loading the loadflow parameters
No exception is thrown
\+ Add another unit test
Bug detected via the CI Snapshot, during powsybl-open-rao …
=> Fix LoadFlowParameters selection when 'load-flow' module is defined

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ControlAreaEq.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionUtil.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesTopologyKindTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportCornerCasesTest.java, cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java, docs/grid_exchange_formats/cgmes/export.md
No.
New feature.
CGMES export's topology kind depends on the network's topology kind computation. A network with at least one node/breaker voltage level will be exported as `NODE_BREAKER`, and a full bus/breaker network will always be exported as `BUS_BRANCH`.
The network topology kind computation has been revised. The network has to be a full node/breaker to be exported in CGMES as `NODE_BREAKER`, likewise it has to be a full …
=> CGMES export: Add a parameter to export as bus branch

cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesTopologyKindTest.java, docs/grid_exchange_formats/cgmes/export.md
Related to #3318
Additional unit test.
The goal is to show that when using bus/branch exports of a node/breaker network, you should  close all non-retained open switches in your case before exporting it, if you plan to use the exported files for later calculations (and want to keep the maximum amount of connectivity). 
Having non-retained open switches in a network that is exported as bus/branch may result in multiple connectivity components in the exported network.
No behaviour is changed. The unit tests tries to clarify potential …
=> CGMES export as bus/branch: unit test to clarify behaviour with non-retained open switches

iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAreaTest.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractOverloadManagementSystemTest.java
No
Feature
Cannot get stream of `AREA`-s and `OVERLOAD_MANAGEMENT_SYSTEM`-s with `Network.getIdentifiableStream(IdentifiableType identifiableType)`
Can get stream of areas and overload management systems.
=> Network.getIdentifiableStream completeness

time-series/time-series-api/src/main/java/com/powsybl/timeseries/CompressedDoubleDataChunk.java, time-series/time-series-api/src/main/java/com/powsybl/timeseries/CompressedStringDataChunk.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/DoubleDataChunkTest.java, time-series/time-series-api/src/test/java/com/powsybl/timeseries/StringDataChunkTest.java
No
Bug fix
When a compressed datachunk is append to another one, if the last value of the first datachunk is equal to the first value of the second datachunk, the corresponding length should be added together.
However, in the current version, the last length of the first datachunk was added to the first length of the **new datachunk**, which was initialized with the first datachunk so the wrong length was added.
Tests `compressedMergeTest()` in `StringDataChunkTest` and in `DoubleDataChunkTest` used the same length value in the two datachunks so the bug wasn't apparent.
**What is the new …
=> Fix append method on compressed datachunks

iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/BatteryShortCircuitSerDe.java, iidm/iidm-serde/src/main/resources/xsd/batteryShortCircuit_V1_0_legacy_2.xsd, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/BatteryShortCircuitXmlSerDeTest.java, iidm/iidm-serde/src/test/resources/shortcircuits/batteryShortCircuitRef_V1_0-legacy-2.xml
No
Bug fix
The legacy version for the battery short circuit extension has 2 distinct namespaces, and both can be used.
But only one (the less commonly used) was declared:
- Actually supported: `"http://www.itesla_project.eu/schema/iidm/ext/battery_short_circuits/1_0"`
- Most commonly used: `"http://www.itesla_project.eu/schema/iidm/ext/batteryshortcircuits/1_0"` - not supported.
Both legacy namespaces are supported.
To avoid a breaking change, the missing legacy namespace is added as a `1.0-legacy-2` version.
**Does this PR introduce …
=> Fix legacy version for the battery short circuit extension

dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/DynamicSimulationReports.java
No
Bug fix
Dynamic simulation tool root report node use only the core resources bundle and thus will not use the simulation provider specific resources bundle.
Use `withAllResourceBundlesFromClasspath` in dynamic simulation tool root report node.
=> Use all resources bundles in dynamic simulation tool report node

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
No
Bug fix
For createCouplingDevice, the error threw contains the busbar object and not the busbar id.
Fix it
=> Fix logs on "CreateCouplingDevice" network modification

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/CgmesDcConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/DcLineSegmentConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/Hvdc.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/LossFactor.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/HvdcConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
No.
Bug fix.
There are a few things at CGMES import of a DC model that give non-uniform or erroneous result:
* `HvdcLine.mode` can't be determined when importing an EQ only because there isn't enough information in the EQ to determine which converter (side) is rectifier and which is inverter. A default value has to be given. This default value depends on the order the converters appear in the EQ file, and on the type of the hvdc line: it is `SIDE_1_RECTIFIER_SIDE_2_INVERTER` for a LCC and `SIDE_1_INVERTER_SIDE_2_RECTIFIER` for a VSC.
* In the case the active power at **p**oint of **c**ommon …
=> Hvdc adjustments

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/NodeMappingTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportCornerCasesTest.java
No.
Fix.
The node of an isolated IIDM equipment (a connectable not linked to any other element either through switch or internal connection) isn't exported to CGMES. This leads to a cardinality issue in the CGMES EQ file where the terminal of the isolated equipment doesn't have a ConnectivityNode association.
The node of an isolated IIDM equipment is exported to CGMES.
Nodes are now exported in order of their number. This shall ensure that nodes …
=> Rework nodes mapping to allow export of isolated nodes

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractCgmesTapChangerBuilder.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractTransformerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TapChanger.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TapChangerConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java, docs/grid_exchange_formats/cgmes/export.md, docs/grid_exchange_formats/cgmes/import.md
Fixes #3414 
CGMES import parameter `CgmesImport.PROFILE_FOR_INITIAL_VALUES_SHUNT_SECTIONS_TAP_POSITIONS` (`"iidm.import.cgmes.profile-for-initial-values-shunt-sections-tap-positions"`) was removed.
Now that there are distinct attributes for initial values (`sectionCount` and `tapPosition`) and solved values (resp. `solvedSectionCount` and `solvedTapPosition`), this parameter was no more pertinent.
If you need to have the SV values in the …
=> Use solved values in CGMES import and export

commons/src/main/java/com/powsybl/commons/report/BundleMessageTemplateProvider.java, commons/src/main/java/com/powsybl/commons/report/MessageTemplateProvider.java, commons/src/main/java/com/powsybl/commons/report/MultiBundleMessageTemplateProvider.java
No
Bug fix to fallback on default `reports.properties` message templates for all existing `MessageTemplateProvider`.
The fallback on default `reports.properties` message templates is not set for all existing `MessageTemplateProvider` (not set for `EmptyMessageTemplateProvider` and `MultiBundleMessageTemplateProvider`)
The fallback on default `reports.properties` message templates is set for all existing `MessageTemplateProvider`.
=> Use NO_FALLBACK_CONTROL for all MessageTemplateProvider

iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java, iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/PhaseShifterXmlTest.java, iidm/iidm-serde/src/test/resources/V1_0/terminalRef.xiidm, iidm/iidm-serde/src/test/resources/V1_1/completeThreeWindingsTransformerRoundTripRef.xml, iidm/iidm-serde/src/test/resources/V1_1/terminalRef.xiidm, iidm/iidm-serde/src/test/resources/V1_2/completeThreeWindingsTransformerRoundTripRef.xml, iidm/iidm-serde/src/test/resources/V1_2/terminalRef.xiidm, iidm/iidm-serde/src/test/resources/V1_3/completeThreeWindingsTransformerRoundTripRef.xml, iidm/iidm-serde/src/test/resources/V1_3/terminalRef.xiidm, iidm/iidm-serde/src/test/resources/V1_4/completeThreeWindingsTransformerRoundTripRef.xml, iidm/iidm-serde/src/test/resources/V1_4/terminalRef.xiidm, iidm/iidm-serde/src/test/resources/V1_5/completeThreeWindingsTransformerRoundTripRef.xml, iidm/iidm-serde/src/test/resources/V1_5/disMeasRef.xiidm, iidm/iidm-serde/src/test/resources/V1_5/terminalRef.xiidm
No
Bug fix
In all IIDM versions, non-regulating phase tap changers are exported with the following characteristics:
- regulating: false
- regulation mode: CURRENT_LIMITER
- regulation value: NaN (attribute non included)
Having the CURRENT_LIMITER regulation mode and either no regulation value or no regulation terminal is problematic for old PowSyBl versions and softwares/libraries reading old IIDM versions (<= 1.5), such as iidm4cpp.
In IIDM 1.5, these phase tap changer are exporter with the following characteristics:
- regulating: …
=> PhaseTapChanger SerDe: Backward compatibility with old IIDM <= 1.5 versions

iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/RemoteReactivePowerControlImpl.java, iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractRemoteReactivePowerControlTest.java
No
Bug fix
When `setRegulatingTerminal(...)` is called on a `RemoteReactivePowerControl` extension, and the previous terminal is removed, the extension is automatically removed.
When `setRegulatingTerminal(...)` is called on a `RemoteReactivePowerControl` extension, and the previous terminal is removed, the extension is **not** removed.
**What changes might users need to make in their application due …
=> Fix RemoteReactivePowerControl regulating terminal replacement

docs/grid_exchange_formats/cgmes/export.md
No.
Documentation update.
CIM 14 is marked available for export in the documentation.
CIM 14 is removed from the available versions for export in the documentation.
=> Fix CIM version available for export in documentation

action-api/src/main/java/com/powsybl/action/PhaseTapChangerRegulationAction.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TopologyTester.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesTopologyKindTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/ExportNumberMaxValueTest.java, computation/src/main/java/com/powsybl/computation/ComputationExceptionBuilder.java, computation/src/main/java/com/powsybl/computation/ThreadInterruptedCompletableFuture.java, contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyElementFactory.java, contingency/contingency-api/src/test/java/com/powsybl/contingency/CriterionContingencyListTest.java, iidm/iidm-api/src/main/java/com/powsybl/iidm/network/identifiers/json/IdentifierDeserializer.java, iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/PropertyCriterion.java, iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/json/CriterionDeserializer.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/DiscreteMeasurement.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/Measurement.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/util/DiscreteMeasurementValidationUtil.java, iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/util/MeasurementValidationUtil.java, iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/MeasurementAdderImpl.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/Replace3TwoWindingsTransformersByThreeWindingsTransformers.java, iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ReplaceThreeWindingsTransformersBy3TwoWindingsTransformers.java, psse/psse-converter/src/main/java/com/powsybl/psse/converter/AbstractConverter.java, psse/psse-model/src/main/java/com/powsybl/psse/model/PsseVersioned.java, psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOJson.java, psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOLegacyText.java, psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/CaseIdentificationData.java, security-analysis/security-analysis-api/src/test/java/com/powsybl/security/PhaseTapChangerRegulationActionTest.java
There was a recurring typo throughout the repository, with 'can not' being written instead of 'cannot'. This was fixed.
=> Fix typos "can not" -> "cannot"

iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSections.java, iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSectionsTest.java
no
fix
when creating a new busbar with CreateVoltageLevelSections the unicty of the id is not ensured and it can crash when adding the bar after a existing bar
ensure unicity on the new id bar created
=> Ensure unicity on new busbarSection id for CreateVoltageLevelSections

cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/AbstractCgmesAliasNamingStrategy.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/NamingStrategiesServiceLoader.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/NamingStrategyFactory.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/NamingStrategyProvider.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/providers/FixedCgmesNamingStrategyProvider.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/providers/IdentityNamingStrategyProvider.java, cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/providers/SimpleCgmesNamingStrategyProvider.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/naming/MockNamingStrategyTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/naming/NamingStrategiesServiceLoaderTest.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/naming/mock/MockNamingStrategy.java, cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/naming/mock/MockNamingStrategyProvider.java, computation-local/src/test/java/com/powsybl/computation/local/LocalComputationManagerTest.java, docs/grid_exchange_formats/cgmes/export.md, docs/grid_exchange_formats/cgmes/import.md
No
Feature
Naming strategy for CGMES import and export must be defined in powsybl-core.
This PR allows automatic discovery of Naming Strategies, allowing thus to define one outside powsybl-core.
=> Enable AutoService Discovery for CGMES Naming Strategy

action-ial/action-ial-simulator/src/test/java/com/powsybl/action/ial/simulator/LoadFlowProviderMock.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java, loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowRunParameters.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderMock.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderTest.java, loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowTest.java, loadflow/loadflow-scripting/src/test/java/com/powsybl/loadflow/scripting/LFMock.java, loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/LoadFlowProviderMock.java
No
Bug fix
Changes introduced in #3538 rendered the loadflow runner not stateless.
The loadflow runner is stateless again and a new class LoadFlowRunParameters has been introduced to define the different parameters with possible default values.
A new methods has been added to the loadflow provider API: …
=> Fix LoadFlow API to introduce `LoadFlowRunParameters` to keep a stateless runner
