- afs/afs-core/src/main/resources/lang/Project_it.properties
Make the code running on a machine with locale IT
> Add Italian localization to afs

- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
- loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationConfig.java
Unit-test have to be independent from developer configuration
> Use platformConfig to read load-flow parameters

- cim1/cim1-converter/src/main/java/com/powsybl/cim1/converter/CIM1Converter.java
- computation-local/src/main/java/com/powsybl/computation/local/LocalComputationManager.java
- computation-mpi/src/main/java/com/powsybl/computation/mpi/MpiJobSchedulerImpl.java
- computation/src/main/java/com/powsybl/computation/InputFile.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TwoTerminalsConnectable.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBranch.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractConnectableXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XmlUtil.java
- loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationFormatterCsvWriter.java
- loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationType.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/OverloadSecurityIndex.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/TransientSecurityIndex.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/TsoFrequencySecurityIndex.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/TsoOverloadSecurityIndex.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/TsoOvervoltageSecurityIndex.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/TsoSynchroLossSecurityIndex.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/TsoUndervoltageSecurityIndex.java
- simulation-api/src/main/java/com/powsybl/simulation/securityindexes/UnderOverVoltageSecurityIndex.java
- ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
Solve a lot of issues/bugs reported by sonar
> Replace InternalError by AssertionError with explicit error message

- action/action-dsl/src/main/groovy/com/powsybl/action/dsl/task/ScriptDslTaskExtension.groovy
- action/action-dsl/src/test/java/com/powsybl/action/dsl/ActionDslLoaderTest.java
- action/action-dsl/src/test/resources/actions2.groovy
(cherry picked from commit 74422d4)
> More specific exception thrown in dsl script task

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
- iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/LoadBarExt.java
- iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/LoadFooExt.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlTest.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadBarXml.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadFooXml.java
- iidm/iidm-xml-converter/src/test/resources/multiple-extensions.xml
- iidm/iidm-xml-converter/src/test/resources/xsd/loadBar.xsd
- iidm/iidm-xml-converter/src/test/resources/xsd/loadFoo.xsd
Regroup all the extensions for the same Identifiable in the same XML element
> Fix XML extension export

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SwitchSetRetainedTest.java
> The retained property of switches is stateful

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Bus.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBus.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/MergedBus.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusFilter.java
- iidm/iidm-xml-converter/src/test/resources/fictitiousSwitchRef-bbk.xml
> Fix regression on the export of retained switches

- scripts/itools.bat
Everything going well it should work :-)
> Itools for windows

- commons/src/main/java/com/powsybl/commons/extensions/ExtensionConfigLoader.java
- security-analysis/src/main/java/com/powsybl/security/ExtensionSAParametersSerializer.java
- security-analysis/src/main/java/com/powsybl/security/ParametersConfigLoader.java
- security-analysis/src/main/java/com/powsybl/security/SecurityAnalysis.java
- security-analysis/src/main/java/com/powsybl/security/SecurityAnalysisImpl.java
- security-analysis/src/main/java/com/powsybl/security/SecurityAnalysisParameters.java
- security-analysis/src/main/java/com/powsybl/security/SecurityAnalyzer.java
- security-analysis/src/test/java/com/powsybl/security/SecurityAnalysisParametersTest.java
- security-analysis/src/test/java/com/powsybl/security/SecurityAnalysisTest.java
I've added security analysis parameters. 
Note : This branch should be merged before the branch with the same name from the powsyble-rte-core project.
> added security analysis parameters

- commons/src/main/java/com/powsybl/commons/json/JsonUtil.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/JsonLoadFlowParameters.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/LoadFlowParametersDeserializer.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/LoadFlowParametersJsonModule.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/LoadFlowParametersSerializer.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/tools/RunLoadFlowTool.java
- loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/json/JsonLoadFlowParametersTest.java
- loadflow/loadflow-api/src/test/resources/LoadFlowParameters.json
- loadflow/loadflow-api/src/test/resources/LoadFlowParametersError.json
- loadflow/loadflow-api/src/test/resources/LoadFlowParametersWithExtension.json
- security-analysis/src/main/java/com/powsybl/security/SecurityAnalysisParameters.java
- security-analysis/src/main/java/com/powsybl/security/SecurityAnalysisTool.java
- security-analysis/src/main/java/com/powsybl/security/SecurityAnalyzer.java
- security-analysis/src/main/java/com/powsybl/security/json/JsonSecurityAnalysisParameters.java
- security-analysis/src/main/java/com/powsybl/security/json/LimitViolationResultDeserializer.java
- security-analysis/src/main/java/com/powsybl/security/json/SecurityAnalysisParametersDeserializer.java
- security-analysis/src/main/java/com/powsybl/security/json/SecurityAnalysisParametersJsonModule.java
- security-analysis/src/main/java/com/powsybl/security/json/SecurityAnalysisParametersSerializer.java
- security-analysis/src/test/java/com/powsybl/security/SecurityAnalysisToolTest.java
- security-analysis/src/test/java/com/powsybl/security/json/JsonSecurityAnalysisParametersTest.java
- security-analysis/src/test/resources/SecurityAnalysisParameters.json
- security-analysis/src/test/resources/SecurityAnalysisParametersError.json
- security-analysis/src/test/resources/SecurityAnalysisParametersIncomplete.json
- security-analysis/src/test/resources/SecurityAnalysisParametersWithExtension.json
Adds also the possibility to define a parameters file for command line tools "loadflow" and "security-analysis".
> Add serialization of load flow and security analysis parameters as json

- cim1/cim1-converter/src/main/java/com/powsybl/cim1/converter/CIM1Converter.java
Also in shunts, fix max section count in IIDM if current value is greater than maximum
> keep line and two windings transformer ends sorted

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StateManagerImpl.java
> Restore the current state at the end of forEachState

- afs/afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java
> Fix AppFileSystem.java

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java
It is used in CGMES to compute power flow at network side for lines that lie on boundary and will be converted to dangling line
> Extend SV to take into account Y1 and Y2 for a Line

- afs/afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorageDataSource.java
- afs/afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
- commons/src/main/java/com/powsybl/commons/datasource/FileDataSource.java
- commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
- commons/src/main/java/com/powsybl/commons/datasource/ReadOnlyDataSource.java
- commons/src/main/java/com/powsybl/commons/datasource/ReadOnlyMemDataSource.java
- commons/src/main/java/com/powsybl/commons/datasource/ZipFileDataSource.java
- commons/src/test/java/com/powsybl/commons/datasource/AbstractDataSourceTest.java
For CGMES support we do not know in advance the "expected" names of the files to import. We have added support for listing the contents of a data source.
> List names in data source

- ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkReader.java
- ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkReaderTest.java
To be in line with the writer names.
> Correct AmplNetworkReader expected file names

- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisParametersDeserializer.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisParametersJsonModule.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisParametersSerializer.java
I have modified the visibility of some classes in order to be used in itesla_as-server application.
> modifcation-for-itesla-as-server

- math/src/main/java/com/powsybl/math/timeseries/TimeSeriesTable.java
Statistics correction for incomplete timeseries
> Statistics correction (for incomplete time-series)

- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TerminalRefTest.java
- iidm/iidm-xml-converter/src/test/resources/terminalRef.xiidm
if the regulatingTerminal is not set for a non regulating ratio tap changer
> Fix NullPointerException in XML export

- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/ParallelLoadFlowActionSimulator.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/tools/ActionSimulatorTool.java
- action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/ParallelLoadFlowActionSimulatorTest.java
* Add possibility to pass script to parallel action simulator as str…ing.
* Clarify the interface of parallel action simulator:
does not implement any more ActionSimulator, as it does not use ActionDb,
but only work on scripts.
> Possibility to pass script as string to parallel action simulator

- action/action-dsl/src/main/groovy/com/powsybl/action/dsl/ConditionDslLoader.groovy
- action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/ExpressionEvaluator.java
- action/action-dsl/src/test/java/com/powsybl/action/dsl/ConditionDslLoaderTest.java
> Fix arithmetic operator between network property

- commons/src/main/java/com/powsybl/commons/json/JsonUtil.java
Preparation for Json Converter (IIDM)
* in **JsonUtil**
* add method writeOptionalBooleanField
* add method writeOptionalDoubleField with default value
* add method to write Extensions without an "extensions" header
* add method to read one Extension
* in **IdentifiableAdder**
* add method to add properties on the adder
* in **iidm-impl**
* allow every adder to set properties in add() method
> prepare correction of JSON converter

- computation-local/src/main/java/com/powsybl/computation/local/LocalComputationConfig.java
- computation-local/src/test/java/com/powsybl/computation/local/LocalComputationConfigTest.java
**LocalComputationConfig:**
* deprecated property names are checked *after* current property names
**LocalComputationConfigTest:**
* checks deprecated property names are checked last
> Fix bug in localcomputationconfig + add some tests

- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/ParallelLoadFlowActionSimulator.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/tools/ActionSimulatorTool.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/tools/ActionSimulatorToolConstants.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisTool.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/DistributedSecurityAnalysis.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/ExternalSecurityAnalysis.java
- tools/src/main/java/com/powsybl/tools/CommandLineTools.java
- tools/src/main/java/com/powsybl/tools/ToolConstants.java
* hide `--task`
* hide `--task-count`
> Hide parallelization in the usage of itools commands

- afs/afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java
the old name should be removed before adding new name to the node
> make the rename method delete old name

- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/CopyStateStrategy.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/CopyStrategy.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/DeepCopyStrategy.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulator.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulatorConfig.java
- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/NetworkCopyStrategy.java
- action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulatorConfigTest.java
possibility to clone the network state instead of coping the entire network in the case when  the property "CloneNetworkState" is set true (ITESLA-15)
> action simulator network state clone optimization

- action/action-dsl/src/main/java/com/powsybl/action/dsl/GroovyDslContingenciesProvider.java
- action/action-dsl/src/main/java/com/powsybl/action/dsl/GroovyDslContingenciesProviderFactory.java
- contingency/contingency-dsl/src/main/java/com/powsybl/contingency/dsl/AbstractDslContingenciesProvider.java
- contingency/contingency-dsl/src/main/java/com/powsybl/contingency/dsl/GroovyDslContingenciesProvider.java
Important for :
- backward compatibility of existing configurations and input files
- possibility to use action language scripts for security-analysis
> Restore action DSL contingency provider

- action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/ParallelLoadFlowActionSimulator.java
- computation/src/main/java/com/powsybl/computation/AbstractExecutionHandler.java
- computation/src/main/java/com/powsybl/computation/Partition.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisTool.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/DistributedSecurityAnalysis.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/ExternalSecurityAnalysis.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SubContingenciesProviderTest.java
I have fixed two bugs on the security-analysis first when the result diverge the result wasn't written, fixed now is written.
Second bug when then contingency file is empty we had an error on the distributed security-analysis, fixed. 
I have enhanced the error message for  ExternalSecurityAnalysis, ParallelLoadFlowActionSimulator, and implicitly for DistributedSecurityAnalysis.
> bug fixing security-analysis

- action/action-dsl/src/test/java/com/powsybl/action/dsl/afs/ActionScriptTest.java
- afs/afs-core/src/main/java/com/powsybl/afs/AbstractNodeBase.java
- afs/afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java
- afs/afs-core/src/test/java/com/powsybl/afs/AppFileSystemToolTest.java
- afs/afs-core/src/test/java/com/powsybl/afs/DependencyCacheTest.java
- afs/afs-core/src/test/java/com/powsybl/afs/LocalTaskMonitorTest.java
- afs/afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ImportedCaseTest.java
- afs/afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ModificationScriptTest.java
- afs/afs-ext-base/src/test/java/com/powsybl/afs/ext/base/VirtualCaseTest.java
- afs/afs-mapdb/src/test/java/com/powsybl/afs/mapdb/MapDbAppFileSystemProviderTest.java
- afs/afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/AppDataBeanMock.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/afs/ContingencyStoreTest.java
- scripting/src/test/java/com/powsybl/scripting/groovy/AfsExtensionErrorGroovyScriptTest.java
- scripting/src/test/java/com/powsybl/scripting/groovy/AfsExtensionGroovyScriptTest.java
- scripting/src/test/java/com/powsybl/scripting/groovy/AfsGroovyScriptTest.java
- security-analysis/security-analysis-afs/src/test/java/com/powsybl/security/afs/SecurityAnalysisRunnerTest.java
and use mem mapdb everywhere to avoid missing serialization issues
> Fix node rename method

- afs/afs-ws/afs-ws-client-utils/src/main/java/com/powsybl/afs/ws/client/utils/UncheckedDeploymentException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedClassNotFoundException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedIllegalAccessException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedInstantiationException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedInterruptedException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedJaxbException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedParserConfigurationException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedSaxException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedTransformerException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedUnsupportedEncodingException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedUriSyntaxException.java
- commons/src/main/java/com/powsybl/commons/exceptions/UncheckedXmlStreamException.java
- commons/src/main/java/com/powsybl/commons/io/ForwardingInputStream.java
Overrides should match their parent class methods in synchronization
> Fix sonar bugs

- pom.xml
- triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreRDF4J.java
And fix the building of the CGMES case data namespace after changes in RDF4J library.
> Update rdf4j library to version 2.4.4

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java
Small optimization.
When assigning voltage and angle from CGMES, check that values are valid before looking for the corresponding IIDM bus.
> check voltage angles values are valid before looking for the IIDM bus

- loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletion.java
- loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/z0flows/Z0BusGroup.java
- loadflow/loadflow-results-completion/src/test/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletionZ0FlowsTest.java
Loops are lines with same bus at both ends.
Instead of trying to compute the flow using the regular BranchData formulae, consider them as a special case of zero-impedance lines.
> consider loops as a special case of z0 results completion

- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/LoadFlowParametersJsonModule.java
hot fix made LoadFlowParametersJsonModule class public
> hot fix made LoadFlowParametersJsonModule class public

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
Fix #631 
cf. documentation on  `powsybl.github.io`
> Homogenize CGMES import params

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImportPostProcessor.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Profiling.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/CgmesImportPostProcessorTest.java
- cgmes/cgmes-model/pom.xml
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
This pull-request fixes #686 
We can define CGMES post processors
No, just a new functionality added.
> CGMES post processor

- cgmes/cgmes-model-alternatives/src/test/java/com/powsybl/cgmes/alternatives/test/AlternativeQueriesForRatioTapChangersTest.java
- iidm/iidm-impl/src/test/groovy/com/powsybl/iidm/network/GroovySetIdIssueTest.java
- time-series/time-series-api/src/test/java/com/powsybl/timeseries/NodeCalcEqualsTest.java
- time-series/time-series-api/src/test/java/com/powsybl/timeseries/NodeCalcToJsonTest.java
- time-series/time-series-api/src/test/java/com/powsybl/timeseries/StringTimeSeriesLostColumnsIssueTest.java
Some unit tests are renamed.
Tests with incorrect name are ignored.
Tests are  now taken into account.
No
> Unit should end with Test to be taken into account by Maven

- README.md
Improve the README.md
A user is kind of lost compiling c++ and downloading dependencies when most of the time a simple java build is enough
The simple java build is described.
Feel free to continue building on this work and improve the wording !
> Readme.md: add a more gentle introduction and a nice logo

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MergeNetworkTest.java
* **Othe information**
This PR solves issue #699. Please refer to the issue for more detailed context description.
> Solves #699: Remove merged network ID modification and renaming

- README.md
> Tiny fix readme

- commons/src/main/java/com/powsybl/commons/extensions/AbstractExtendable.java
- commons/src/test/java/com/powsybl/commons/extensions/ExtensionTest.java
No
Bug fix
When an extension is removed, it remains in one of the 2 internal map, so getExtension(Class) still return the extension.
Extension is fully removed and state remains consistent.
**Does this PR introduce a breaking change?** *(What changes might users need to make in their application …
> Fix extension removal

- README.md
N/A
The badge to the Gitter chat has been replaced by a new badge linked to the spectrum community, in the README.md file
There is a badge to Gitter in README.md file.
There is a badge to Spectrum in README.md file.
**Does this PR introduce a breaking change?** *(What changes might users need to …
> Replace Gitter badge by Spectrum

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VariantManagerHolder.java
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
No
make VariantManagerHolder interface public
VariantManagerHolder package private
VariantManagerHolder interface public
**Does this PR introduce a breaking change?** …
> make VariantManagerHolder interface public

- .github/topissuebot.yml
No.
Just a configuration needed for bot top issue.
Nothing.
(if any of the questions/checkboxes …
> Add top issue configuration.

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Bus.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
Signed-off-by: BENHAMED CHAMSEDDINE <chamseddine.benhamed@rte-france.com>
fix #777
> removing deprecated methods

- ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkReaderTest.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BusTest.java
> Add getBus(id) method

- math/src/main/java/com/powsybl/math/matrix/AbstractMatrix.java
- math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
- math/src/main/java/com/powsybl/math/matrix/DenseMatrixFactory.java
- math/src/main/java/com/powsybl/math/matrix/Matrix.java
- math/src/main/java/com/powsybl/math/matrix/MatrixFactory.java
- math/src/main/java/com/powsybl/math/matrix/SparseLUDecomposition.java
- math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java
- math/src/main/java/com/powsybl/math/matrix/SparseMatrixFactory.java
- math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java
- math/src/test/java/com/powsybl/math/matrix/DenseMatrixTest.java
- math/src/test/java/com/powsybl/math/matrix/SparseMatrixTest.java
No
Methods renaming + javadoc fxes
getM -> getRowCount
getN -> getColumnCount
getValue -> get
setValue -> set
addValue -> add
N/A
N/A
**Does this PR introduce a breaking change?** *(What changes might users need to make in …
> Matrix renaming + javadoc fixes

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
- math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java
- math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
> Add javadoc to the Graph API

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VariantManager.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VariantManagerImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
> Variant can now be copied into an already existing Variant

- computation/src/main/java/com/powsybl/computation/DefaultExecutionReport.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysis.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisResult.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/DistributedSecurityAnalysis.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/DistributedSecurityAnalysisExecution.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/ExternalSecurityAnalysis.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/ForwardedSecurityAnalysisExecution.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisCommandOptions.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandler.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlers.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/package-info.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/NetworkVariant.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/SecurityAnalysisExecution.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/SecurityAnalysisExecutionInput.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/package-info.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/DistributedSecurityAnalysisTest.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisCommandOptionsTest.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlersTest.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/execution/NetworkVariantTest.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/execution/SecurityAnalysisExecutionInputTest.java
Iso-functional refactoring.
Currently, distributed security analysis implements the security analysis interface.
It is a little misleading, as some of the inputs and methods of that interface are not correctly
handled by this implementation, for example because they are not properly serializable.
This evolution dissociates explicitly the distributed execution from the security analysis interface,
which is meant to be the SPI for actual computation implementations.
It also refactors the execution handlers, to make the code more clear …
> Security analysis distribution refactoring: dissociate it from security analysis interface.

- contingency/contingency-api/src/main/java/com/powsybl/contingency/AbstractInjectionContingency.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyElementType.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/ShuntCompensatorContingency.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/StaticVarCompensatorContingency.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/tasks/AbstractInjectionTripping.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/tasks/GeneratorTripping.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/tasks/ShuntCompensatorTripping.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/tasks/StaticVarCompensatorTripping.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/ContingencyTest.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/ShuntCompensatorContingencyTest.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/StaticVarCompensatorContingencyTest.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/tasks/ShuntCompensatorTrippingTest.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/tasks/StaticVarCompensatorTrippingTest.java
- contingency/contingency-api/src/test/resources/contingency.json
- contingency/contingency-dsl/src/main/groovy/com/powsybl/contingency/dsl/ContingencyDslLoader.groovy
Signed-off-by: calinbanc <calinbanc@yahoo.com>
Yes.#783
> enable ShuntCompensator and StaticVarCompensator groovy DSL contingency

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ExternalNetworkInjectionConversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BatteryAdder.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/GeneratorAdder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ValidationUtil.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/GeneratorTest.java
No
Check bounds of minP maxP and targetP of batteries and generators
Check if minP<=targetP<=maxP
Check if minP<maxP
Change default value for cgmes import of generators to Double.MAX_VALUE
The checks above are not done
Add this checks
> add checks to battery and generator attributs

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BatteryTest.java
No
fix missing operation on variant dependent attributes for Battery object
> add missing operation on variant linked attributes

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CalculatedBusImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/EmptyCalculatedBusBugTest.java
Report [PR#838](https://github.com/powsybl/powsybl-core/pull/838) to release-v2.5.0
> Fix traverser in CalculatedBusImpl to handle properly internal connections

- contingency/contingency-dsl/src/test/java/com/powsybl/contingency/dsl/GroovyDslContingenciesProviderTest.java
- dsl/src/main/groovy/com/powsybl/dsl/DslLoader.groovy
> Fix comparison operations in Contingency DSL

- afs/afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java
Signed-off-by: Marianne Funfrock <marianne.funfrock@rte-france.com>
#873
Bug fix
> mapDB uncomplete time series cleaning #873

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VariantManagerImpl.java
> improve VariantManagerImpl::removeVariant performance (removes O(N^2)worst case)

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
- cgmes/cgmes-model-alternatives/src/test/java/com/powsybl/cgmes/alternatives/test/AlternativeQueriesTester.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModelFactory.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesSubset.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
- distribution-core/pom.xml
- triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/PrefixNamespace.java
- triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/PropertyBag.java
- triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStore.java
- triple-store/triple-store-impl-blazegraph/src/main/java/com/powsybl/triplestore/impl/blazegraph/TripleStoreBlazegraph.java
- triple-store/triple-store-impl-jena/src/main/java/com/powsybl/triplestore/impl/jena/TripleStoreJena.java
- triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/PowsyblWriter.java
- triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreRDF4J.java
- triple-store/triple-store-test/pom.xml
- triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/ExportTest.java
- triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/TripleStoreTester.java
This PR replaces PR #857
Extend the triple store API/implementations in order to support the export of a network in CGMES format
The triple store API does not provide all the needed support for exporting a network in CGMES format
The triple store API provides the needed support for exporting a …
> Extend support for CGMES export

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractMultiVariantConnectableExtension.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MultiVariantExtensionTest.java
N/A
Feature
N/A
Add an abstract class for extensions that depend on the variant. This base class can be use to implement its own extension.
(if any of the questions/checkboxes …
> Add AbstractMultiVariantExtension

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
N/A
Bug fix
The value send to the listeners are not correct (copy/paste error)
The values are now OK
> Fix AbstractTapChanger notifications

- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_invalid_svc_mode/MicroGridTestConfiguration_T4_BE_EQ_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_missing_reg_control_reactive_power_svc/MicroGridTestConfiguration_T4_BE_EQ_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_off_svc/MicroGridTestConfiguration_T4_BE_SSH_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_off_svc_control/MicroGridTestConfiguration_T4_BE_SSH_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_reactive_power_svc/MicroGridTestConfiguration_T4_BE_EQ_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/Type4_T4/BE_BB_Complete_v2_svc_no_regulating_control/MicroGridTestConfiguration_T4_BE_EQ_V2.xml
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMapping.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
- cgmes/cgmes-model/src/main/resources/CIM16.sparql
> Correct CGMES import of SVC

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorImpl.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
Bug fix
Update the correct value.
> Fix svc notify

- sensitivity-api/pom.xml
No
Fix: typo in automatic module name
No
> Correct automatic module name of sensitivity-api

- iidm/iidm-reducer/pom.xml
- iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/DefaultNetworkReducerTest.java
- iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/DanglingLineXmlTest.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/EurostagXmlTest.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TieLineXmlTest.java
- iidm/iidm-xml-converter/src/test/resources/danglingLine.xml
- iidm/iidm-xml-converter/src/test/resources/eurostag-tutorial1-lf.xml
- iidm/iidm-xml-converter/src/test/resources/tieline.xml
N/A
Quality
TieLineXml and DanglingLineXml are not tested
TieLineXml and DanglingLineXml are now tested
I fixed an issue in TieLineXml to manage names of HalfLine like in all the …
> Increase code coverage in XML converter

- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1Catalog.java
- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java
- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1Test.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/CgmesImportPostProcessorTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ImportExportPerformanceTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesConversionTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesNetworkCatalog.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
- cgmes/cgmes-model-alternatives/src/test/java/com/powsybl/cgmes/alternatives/test/AlternativeQueriesForGeneratorsTest.java
- cgmes/cgmes-model-alternatives/src/test/java/com/powsybl/cgmes/alternatives/test/AlternativeQueriesForSwitchesTest.java
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/cim14/Cim14SmallCasesCatalog.java
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/cim14/Cim14SmallCasesTest.java
Better coding practices
For CGMES catalogs/factory, we don't use final classes.
CGMES catalogs/factory have been made final
No
> Make CGMES catalogs final + add back a removed test

- time-series/time-series-api/pom.xml
- time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeries.java
- time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTest.java
Signed-off-by: Paul <paul.bui-quang@runbox.com>
https://github.com/powsybl/powsybl-core/issues/978
> Use supercsv lib to parse csv

- afs/afs-core/src/main/java/com/powsybl/afs/ProjectFile.java
- afs/afs-ext-base/src/main/java/com/powsybl/afs/ext/base/VirtualCase.java
- afs/afs-ext-base/src/test/java/com/powsybl/afs/ext/base/VirtualCaseTest.java
- security-analysis/security-analysis-afs/src/main/java/com/powsybl/security/afs/SecurityAnalysisRunner.java
- security-analysis/security-analysis-afs/src/test/java/com/powsybl/security/afs/SecurityAnalysisRunnerTest.java
Signed-off-by: Nassirou NAMBIEMA <nassirou.nambiena@rte-france.com>
- [X ] The commit message follows our guidelines
No
feature
incomplete nodes are not identified by a method
nodes with missing dependencies can be identified with a method
**Does this PR introduce a breaking change or deprecate an …
> Detect incomplete nodes

- .travis.yml
No
Bug fix.
Something on Travis side has changed and Sonar report push failed.
As recommended by Travis support team we have modified the script like this:
https://travis-ci.community/t/deploy-fails-with-aws-signaturedoesnotma …
> Fix Travis build (Sonar issue)

- afs/afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java
- afs/afs-core/src/main/java/com/powsybl/afs/LocalTaskMonitor.java
- afs/afs-core/src/main/java/com/powsybl/afs/TaskMonitor.java
- afs/afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java
- afs/afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
- afs/afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java
- afs/afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/AppDataBeanMock.java
- afs/afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/AppStorageServerTest.java
- afs/afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/UserAuthenticatorMock.java
- afs/afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/RemoteTaskMonitor.java
Signed-off-by: Paul Bui-Quang <paul.buiquang@rte-france.com>
- [ x] Tests for the changes have been added (for bug fixes / features)
Add a less restrictive way to create tasks.
Task must be related to a project file.
Task only need a name and an project reference.
> Add less restrictive task creation

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ValidationUtil.java
> Enhancement of validation method checkOnlyOneTapChangerRegulatingEnabled

- computation/pom.xml
- computation/src/main/java/com/powsybl/computation/ComputationException.java
- computation/src/main/java/com/powsybl/computation/ComputationExceptionBuilder.java
- computation/src/test/java/com/powsybl/computation/ComputationExceptionBuilderTest.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandler.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlers.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlersTest.java
fix #1015 
Between feature and bug.
See [here](https://github.com/powsybl/powsybl-core/wiki/Migration-guide-v3.1.0#computation-exceptions-evolutions) for migration guide.
> Improve computation exceptions logging.

- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractInjectionAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BatteryAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BatteryAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusbarSectionAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/GeneratorAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/GeneratorAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LoadAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LoadAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ShuntCompensatorAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ShuntCompensatorAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/StaticVarCompensatorAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/StaticVarCompensatorAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdapter.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/BatteryAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/BusbarSectionAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/DanglingLineAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/GeneratorAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/LoadAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/ShuntCompensatorAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/StaticVarCompensatorAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/VoltageLevelAdapterTest.java
No
New adaptated classes are implemented.
Each method adaptated not implemented yet throw an exception
Merging view module implementation need to implement Injections adapters
Merging view module implementation step : Injections adapters implementation …
> Merging view : injections adapter implementation

- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLImporter.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterTest.java
> Fix bug in XmlImporter.exists() method after versioning of XIIDM

- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractBranchAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractIdentifiableAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractTapChangerAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LegAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LegAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewIndex.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/PhaseTapChangerAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/PhaseTapChangerAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/PhaseTapChangerStepAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/RatioTapChangerAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/RatioTapChangerAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/RatioTapChangerStepAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/SubstationAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdderAdapter.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/BusAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/LccConverterStationAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/LineAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/MergingNetworkTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/PhaseTapChangerAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/RatioTapChangerAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/SubstationAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/VoltageLevelAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/VscConverterStationAdapterTest.java
No
New adaptated classes are implemented.
Each method adaptated not implemented yet throw an exception
Merging view module implementation need to implement Transformers & TapChanger adapters
Merging view module implementation step : Transformers & …
> Merging view : transformers adapter implementation

- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractInjectionAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BatteryAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/GeneratorAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LoadAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ShuntCompensatorAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/StaticVarCompensatorAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VscConverterStationAdderAdapter.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/GeneratorAdapterTest.java
No
New abstract class in order to reduce code duplication
Code is duplicated for all adder adapters classes inherited of InjectionAdder interface 
Creation and usage of class AbtsractInjectionAdderAdapter …
> Merging view : common Injection adder adapter implementation

- README.md
No
Bug fix
Now we have switched to github actions, CI badge in README.md has to be changed.
CI badge is now github actions one. …
> Fix CI README.md badge

- afs/afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
Signed-off-by: Paul Bui-Quang <paul.buiquang@rte-france.com>
- [x ] Tests for the changes have been added (for bug fixes / features)
test
due to some appstorage implematentions, it was found useful to add some more test for the setmetadata method
> Add more test to appstorage

- entsoe-util/src/test/resources/entsoeAreaRef.xml
- entsoe-util/src/test/resources/mergedXnodeRef.xml
- entsoe-util/src/test/resources/xnodeRef.xml
- ieee-cdf/ieee-cdf-converter/src/test/resources/ieee118cdf.xiidm
- ieee-cdf/ieee-cdf-converter/src/test/resources/ieee14cdf-solved.xiidm
- ieee-cdf/ieee-cdf-converter/src/test/resources/ieee14cdf.xiidm
- ieee-cdf/ieee-cdf-converter/src/test/resources/ieee300cdf.xiidm
- ieee-cdf/ieee-cdf-converter/src/test/resources/ieee30cdf.xiidm
- ieee-cdf/ieee-cdf-converter/src/test/resources/ieee57cdf.xiidm
- ieee-cdf/ieee-cdf-converter/src/test/resources/ieee9cdf.xiidm
- iidm/iidm-extensions/src/test/resources/activePowerControlRoundTripRef.xml
- iidm/iidm-extensions/src/test/resources/coordinatedReactiveControl.xml
- iidm/iidm-extensions/src/test/resources/threeWindingsTransformerPhaseAngleClock.xml
- iidm/iidm-extensions/src/test/resources/twoWindingsTransformerPhaseAngleClock.xml
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/IidmXmlConstants.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TerminalMockXmlSerializer.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterTest.java
- iidm/iidm-xml-converter/src/test/resources/V1_0/fictitiousSwitchRef-bbk.xml
- iidm/iidm-xml-converter/src/test/resources/V1_0/fictitiousSwitchRef-bbr.xml
Revert XIIDM version to 1.0 until a functional evolution is merged.
> Revert XIIDM to version 1.0

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImportPostProcessor.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModelFactory.java
- triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStoreFactory.java
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>
> add create method to cgmes factory

- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/DanglingLineAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/DanglingLineAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdapter.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/DanglingLineAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/VoltageLevelAdapterTest.java
No
New adaptated classes are implemented.
Each method adaptated not implemented yet throw an exception
Merging view module implementation need to implement DanglingLine adapter
Merging view module implementation step : DanglingLine adapter …
> Merging view : DanglingLine adapter implementation

- loadflow/loadflow-scripting/pom.xml
- pom.xml
N/A
Bug fix
The javadoc jar is not created for loadflow-scripting because it's a full groovy module.
The javadoc jar is created using groovydoc.
(if any of the …
> Javadoc jar for loadflow-scripting

- iidm/iidm-scripting/src/main/groovy/com/powsybl/iidm/network/scripting/NetworkLoadSaveGroovyScriptExtension.groovy
fix https://github.com/powsybl/powsybl-core/issues/1195
> Fix network loadsave groovy extension constructor

- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractBranchAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractHvdcConverterStationAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractInjectionAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractTapChangerAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ComponentAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/HvdcLineAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LineAdderAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TerminalAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdapter.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdapter.java
No
Change static variable to static method
When not implemented exception is raised, it's not easy to localise
When not implemented exception is raised, the call trace contains the method MergingView::createNotImplementedException
**Does this PR …
> Merging view step : refactor not implemented exception

- .github/workflows/maven.yml
- computation/src/test/java/com/powsybl/computation/ThreadInterruptedCompletableFutureTest.java
N/A
Bug fix
The compilation fails randomly on windows in multi-thread mode (CI)
We revert both #1082 and #1213  …
> Revert commits that make the compilation to fail randomly

- action/action-util/src/main/java/com/powsybl/action/util/Scalable.java
- commons/src/main/java/com/powsybl/commons/datasource/Bzip2FileDataSource.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/tasks/ShuntCompensatorTripping.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/export/ExportOptionsTest.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportOptionsTest.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterExporterBaseExtensionsTest.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterLimitsTest.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/json/JsonLoadFlowParameters.java
- loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/KComputation.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/SecurityAnalysisExecutionBuilder.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/JsonSecurityAnalysisParameters.java
- sensitivity-api/src/main/java/com/powsybl/sensitivity/SensitivityComputationResults.java
- sensitivity-api/src/main/java/com/powsybl/sensitivity/SensitivityValue.java
This PR just includes fixes for formatting issues reported by checkstyle in some modules.
Multiple empty lines have been replaced by a single empty line.
> remove multiple empty lines to avoid checkstyle errors

- sensitivity-api/src/main/java/com/powsybl/sensitivity/SensitivityComputationResults.java
fix for checkstyle
too many empty lines between methods 
only one empty line between method definition
> remove empty line to avoid checkstyle error

- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisImpl.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisResultBuilder.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisResultBuilderTest.java
N/A
Revert the PR #1207 
This PR introduce a regression that make it hard to customize the creation of custom results (with extensions).
We reintroduce the old design to have time to rethink the design quietly. …
> Revert "Change the design of the SecurityAnalysisResultBuilder (#1207)"

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/CgmesDcConversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/LossFactor.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/HvdcConversionTest.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
> Lossfactor is a percentage

- pom.xml
N/A
Dependency update
Current version of powsybl-math-native is 1.0.1
Current version of powsybl-math-native is 1.0.2
(if any of the questions/checkboxes don't apply, please …
> Update powsybl-math-native to v1.0.2

- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/TestImporter.java
No
Bug fix
Currently, ImporterWrapper does not implement correct version of importData() method.
ImporterWrapper implement the correct method of the API.
Fixes the integration tests of powsybl-network-store-server when using post-proicessors localy
> Fix ImporterWrapper implementation

- action/action-dsl/pom.xml
- action/action-simulator/pom.xml
- cgmes/cgmes-conversion/pom.xml
- cgmes/cgmes-model/pom.xml
- computation-local/pom.xml
- computation/pom.xml
- contingency/contingency-api/pom.xml
- dynamic-simulation/dynamic-simulation-api/pom.xml
- entsoe-util/pom.xml
- iidm/iidm-api/pom.xml
- iidm/iidm-converter-api/pom.xml
- iidm/iidm-impl/pom.xml
- iidm/iidm-mergingview/pom.xml
- iidm/iidm-scripting/pom.xml
- iidm/iidm-tck/pom.xml
- iidm/iidm-xml-converter/pom.xml
- loadflow/loadflow-api/pom.xml
- loadflow/loadflow-results-completion/pom.xml
- loadflow/loadflow-scripting/pom.xml
- loadflow/loadflow-validation/pom.xml
- math/pom.xml
- pom.xml
- scripting/pom.xml
- security-analysis/security-analysis-api/pom.xml
- sensitivity-api/pom.xml
- time-series/time-series-api/pom.xml
- tools/pom.xml
Dependency update.
mockito-all packages an outdated version of mockito. Newer releases are published as mockito-core.
Some features of this outdated version do not work well, for example the delegation of calls to methods with variable number of arguments.
Using an up-to-date version of mockito-core, supporting more features.
> Update mockito version to 3.3.3.

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesConversionContextExtension.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesConversionContextExtensionAdder.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesConversionContextExtensionAdderImpl.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesConversionContextExtensionAdderImplProvider.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesConversionContextExtensionImpl.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
Signed-off-by: Jérémy LABOUS <jlabous@silicom.fr>
Part of #1206
> implement new extension API on CgmesConversionContextExtension

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesConversionContextExtensionAdder.java
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/TestGridModelResources.java
fix logging in tests
The names contained in a data source are logged with log level `ERROR`
Changed to log level `INFO`
Fixed style in non-related file (two blank lines in file header)
> fix log in CGMES tests: logging names in the data source is not an error

- iidm/iidm-extensions/src/test/resources/voltagePerReactivePowerControl.xml
- matpower/matpower-converter/src/test/resources/ieee118mat.xiidm
- matpower/matpower-converter/src/test/resources/ieee14mat.xiidm
- matpower/matpower-converter/src/test/resources/ieee300mat.xiidm
- matpower/matpower-converter/src/test/resources/ieee30mat.xiidm
- matpower/matpower-converter/src/test/resources/ieee57mat.xiidm
- matpower/matpower-converter/src/test/resources/ieee9mat.xiidm
- psse/psse-converter/src/main/resources/IEEE_14_bus.xiidm
Update XIIDM version in tests for new tests
> Adapt tests of voltagePerReactivePowerControl, matpower converter and psse converter to XIIDM 1.3

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
- ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteElement.java
- ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteNode.java
Signed-off-by: benrejebmoh <mohamed.ben-rejeb@rte-france.com>
logs level adjustment after Coreso's feedback …
> Logs level adjustments in UCTE importer and network merge

- pom.xml
N/A
Update
Current version of guava is 20.0, but this version contains a [vulnerability](https://github.com/powsybl/powsybl-core/network/alert/pom.xml/com.google.guava:guava/open)
We use the latest version of guava.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
> Fix guava vulnerability

- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetail.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailAdder.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailAdderImpl.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailAdderImplProvider.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailImpl.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailXmlSerializer.java
- iidm/iidm-extensions/src/main/resources/xsd/loadDetail.xsd
- iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/LoadDetailTest.java
- iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/LoadDetailXmlTest.java
- iidm/iidm-extensions/src/test/resources/loadDetailOldRef.xml
- iidm/iidm-extensions/src/test/resources/loadDetailRef.xml
No.
Feature
A load is only described by active and reactive power, without specifying if it is fixed or variable.
An extension now exists to express if the active and reactive power are fixed or variable
No.
> Implementation of LoadDetail extension (handle fixed and variable part of active and reactive power)

- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_conform_non_conform_loads/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_conform_non_conform_loads/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java
- cgmes/cgmes-model/src/main/resources/CIM14.sparql
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/cim14/Cim14SmallCasesTest.java
> Import details about scaling participation for energy consumer in CGMES (conform or not conform loads)

- psse/psse-converter/src/main/java/com/powsybl/psse/converter/PsseImporter.java
Fix duplicated lines to connect a generator that was declared in-service in PSS/E
> PSSE: remove duplicated connect in conversion of generator

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TapChanger.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
Signed-off-by: Jérémy LABOUS <jlabous@silicom.fr>
fix #663
> add method to get all tapChanger steps

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractMultiVariantConnectableExtension.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevels.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/GeneratorXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ShuntXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/StaticVarCompensatorXml.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TerminalMockXmlSerializer.java
Signed-off-by: Jérémy LABOUS <jlabous@silicom.fr>
part of #678: use network accessor from connectable when it's possible
> use network accessor from connectable when it is possible

- math/src/main/java/com/powsybl/math/matrix/DenseLUDecomposition.java
- math/src/main/java/com/powsybl/math/matrix/LUDecomposition.java
- math/src/main/java/com/powsybl/math/matrix/SparseLUDecomposition.java
- math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java
- pom.xml
No
feature
We can now solve At * x = b in addition to A * x = b
> LU solve transposed

- distribution-core/pom.xml
N/A
Bug fix
The XSD of XIIDM v1.2 and v1.3 are not installed by itools-packager
The XSD are now installed …
> Deploy XIIDM xsd files

- config-classic/pom.xml
N/A
Dependency fix
There is no SLF4J implementation for unit test in powsybl-config-classic
We use `slf4j-simple` as usual
(if any of the questions/checkboxes don't apply, please …
> Fix powsybl-config-classic dependencies

- action/action-dsl/src/main/java/com/powsybl/action/dsl/ActionDb.java
Signed-off-by: Etienne Lesot <etienne.lesot@rte-france.com>
no
it adds a getter on all actions in ActionDB
There is no getter …
> adding a getter on actions in Action_DB

- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/ImportConfig.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/ImportPostProcessor.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java
Documentation.
Missing documentation on importer API. It's difficult to know what is the role of each parameter (see computation manager), what are the actually required parameters, and when platform config is used in the background.
Javadoc on importer API methods.
> Add some javadoc to import API.

- commons/src/main/java/com/powsybl/commons/util/WeakListenerList.java
Bug fix
If there is a lot of listeners, the temporary copy of listeners create a hard reference to them and break the WeakHashMap system. The GC may not have the time to clear the listeners. At some point the WeakHashMap may accumulate listeners if proper conditions are set (periodic call to notify and a very large amount of listeners).
This is due to changes in #1376. 
The copy of listeners list that will handle the …
> Use weakreference in listener cache

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java
- iidm/iidm-util/src/main/java/com/powsybl/iidm/network/util/ContainersMapping.java
- pom.xml
- ucte/ucte-network/src/main/java/com/powsybl/ucte/network/ext/UcteNetworkExt.java
Updated jgrapht to latest java 8 version.
UndirectedGraph is deprecated in favor of graph.
ConnectivityInspector is in connectivity package.
No
Library update
(if any of the …
> Update jgrapht version

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/StaticVarCompensator.java
Just removed a blank line to avoid checkstyle complain.
> IIDM SVC : remove blank line to fix checkstyle complain

- pom.xml
NO
Dependency update
junit 4.12
junit 4.13
NO
Junit 4.13 has the useful …
> Upgrade junit 4.12 -> 4.13

- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java
Feature
The regulating control is discarded if `targetV` is <= 0
The regulating control is kept as disabled and a warning is emitted if `targetV` is <= 0  …
> Regulating control adjustments to export SSH

- ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java
- ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplSubset.java
- ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplUtil.java
- ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
- ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplUtilTest.java
- ampl-converter/src/test/java/com/powsybl/ampl/converter/FooNetworkExtension.java
- ampl-converter/src/test/java/com/powsybl/ampl/converter/FooNetworkExtensionWriter.java
- ampl-converter/src/test/resources/inputs/foo-network-extension.txt
fix https://github.com/powsybl/powsybl-core/issues/1513
> consider network's extensions during AMPL export

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
- iidm/iidm-tck/src/test/resources/fictitious-switch-c.dot
Include names of nodes and edges in the node-breaker voltage level export to GraphViz.
> Add names to node-breaker voltage level export

- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysis.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisTest.java
Signed-off-by: Jérémy LABOUS <jlabous@silicom.fr>
fix #1528
> add possibility to run sensitivity analysis whithout contengencies

- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysis.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisProvider.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisTool.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisTest.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/mocks/SensitivityAnalysisProviderMock.java
No
Feature
sensivity-analysis runner use ContingenciesProvider
sensivity-analysis runner use list of Contingency
(if any of the …
> sensitivity-analysis-api - Use List<Contingency> instead of ContingenciesProvider

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsOwner.java
No
Small modification after changing limits: the `OperationalLimitsOwner` is now a public interface (useful for extensions)
No
> Make OperationalLimitsOwner public

- security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysis2.java
- security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisImpl.java
- security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisImplProvider.java
- security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisProvider.java
- security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysis2Test.java
- security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisTest.java
No
Refactoring of security-analysis-api
Factory mechanism is used to create implementation of SecurityAnalysis
Service Loader is used to create implementation of SecurityAnalysis …
> Use ServiceLoader to create SecurityAnalysis

- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/JsonSensitivityFactorsProvider.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFactorsProvider.java
Signed-off-by: Sebastien Murgey <sebastien.murgey@rte-france.com>
No
Feature
Update Sensitivity factors provider API to make it clearer
> Update sensitivity factors provider API

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSshMetadataAdderImpl.java
- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSshMetadataImpl.java
- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSshMetadataXmlSerializer.java
- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSvMetadataAdderImpl.java
- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSvMetadataImpl.java
- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesSvMetadataXmlSerializer.java
- cgmes/cgmes-extensions/src/main/resources/xsd/cgmesSshMetadata.xsd
- cgmes/cgmes-extensions/src/main/resources/xsd/cgmesSvMetadata.xsd
- cgmes/cgmes-model/src/main/resources/CIM16.sparql
For CGMES FullModel objects, the attribute description is required.
CGMES FullModel attribute description is optional.
Observed in private test cases.
> Make optional the description attribute of CGMES model objects

- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusAdapter.java
No
Implement methods `BusAdapter.getConnectedTerminals` and `BusAdapter.getConnectedTerminalStream` (used to throw exceptions)
> Implement BusAdapter.getConnectedTerminals and BusAdapter.getConnectedTerminalStream

- commons/src/main/java/com/powsybl/commons/reporter/AbstractReporter.java
- commons/src/main/java/com/powsybl/commons/reporter/Report.java
- commons/src/main/java/com/powsybl/commons/reporter/ReportBuilder.java
- commons/src/main/java/com/powsybl/commons/reporter/Reporter.java
- commons/src/main/java/com/powsybl/commons/reporter/ReporterModel.java
- commons/src/main/java/com/powsybl/commons/reporter/TypedValue.java
No
Javadoc for the Reporter API (#1666)
> Reporter javadoc

- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesControlAreaAdder.java
> Bug fix: completing the creation of a control area should NOT return the implementation

- README.md
No
Add Slack badge and link in README
> Add Slack badge and link in README

- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesControlAreasAdderImplProvider.java
No
Bug: renaming correctly provider of `CgmesControlAreasAdderImpl`
> Rename correctly CgmesControlAreasAdderImplProvider

- README.md
> Add CII badge in README file

- triple-store/triple-store-test/src/test/resources/cgmes-rtcs/cgmes-rtcs.sparql
- triple-store/triple-store-test/src/test/resources/foaf/abc-lastNames.ttl
- triple-store/triple-store-test/src/test/resources/foaf/abc-nicks.ttl
- triple-store/triple-store-test/src/test/resources/foaf/foaf-graphs-copy.sparql
- triple-store/triple-store-test/src/test/resources/foaf/foaf-graphs.sparql
- triple-store/triple-store-test/src/test/resources/foaf/foaf-optionals.sparql
- triple-store/triple-store-test/src/test/resources/foaf/foaf.sparql
N/A
License
LFE license scanner reports invalid license header
This PR fixes the invalid headers
> Fix license header

- action/action-dsl/src/main/java/com/powsybl/action/dsl/RuleType.java
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
- computation/src/test/java/com/powsybl/computation/CompletableFutureTaskTest.java
- entsoe-util/src/test/java/com/powsybl/entsoe/util/EntsoeAreaXmlSerializerTest.java
- entsoe-util/src/test/java/com/powsybl/entsoe/util/MergedXnodeXmlSerializerTest.java
- entsoe-util/src/test/java/com/powsybl/entsoe/util/XnodeXmlSerializerTest.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TapChangerAttributeTest.java
- loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/json/JsonLoadFlowParametersTest.java
- math/src/test/java/com/powsybl/math/graph/GraphUtilTest.java
- time-series/time-series-api/src/test/java/com/powsybl/timeseries/ReadOnlyTimeSeriesStoreAggregatorTest.java
- triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/QueryCatalogTest.java
Yes, after LFE licence scanning: https://lfscanning.org/reports/lfenergy/powsybl-2021-04-20-ed46eeb7-b4a3-4f66-8266-e757e3fb0c46.xlsx
**Other …
> Fix: add licence mentions

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBranch.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStation.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusbarSectionAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusbarSectionImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LccConverterStationAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LccConverterStationImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationImpl.java
> Caching the network ref in AbstractConnectable

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NodeBreakerConnectTest.java
> Fix connect bug

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
Feature
This option has been deleted
> CGMES conversion: delete iidm.import.cgmes.merge-boundaries-using-tie-lines parameter

- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingImpl.java
No
Not really a bug fix, but a modification is necessary for 50Hertz and NGESO import.
Throws an exception when a TN is mapped to two IIDM buses.
Logs a warning when a TN is mapped to two IIDM buses. Second mapping is ignored. …
> When CGMES TN already mapped to another IIDM bus, no exception, only warning

- README.md
> Update required JDK version in README

- cgmes/cgmes-conversion/pom.xml
- commons/src/main/java/com/powsybl/commons/config/XmlModuleConfigRepository.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
No
Fix vulnerabilities
[CWE-611](http://cwe.mitre.org/data/definitions/611.html)
[CWE-827](http://cwe.mitre.org/data/definitions/827.html)
> Fix vulnerability: disable access to external entities in XML parsing [CWE-611][CWE-827]

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimits.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimitsAdder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ActivePowerLimitsImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ApparentPowerLimitsImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CurrentLimitsImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsHolderImpl.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractConnectableXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/DanglingLineXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LineXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TwoWindingsTransformerXml.java
N/A
Refactoring
Some design choices are weird. The code could be written in a different (simpe) way  
The code has been refactored …
> Small fixes in operational limits implementation

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
No
Clean some code by deleting useless method
> Clean code: control areas are now imported, method addCgmesSshControlAreas can be deleted

- ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplExporter.java
- ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/export/Exporter.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLExporterTest.java
- ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
- ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteExporterTest.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
#1785
> Expose exporter parameters

- math/src/main/java/com/powsybl/math/matrix/SparseLUDecomposition.java
- math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java
- math/src/main/java/com/powsybl/math/matrix/SparseMatrixFactory.java
No
Feature
The rgrowth threshold used by KLU to decide how matrix could be factorized is hard coded.
We can now configure the rgrowth threshold.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
> Rgrowth threshold configuration

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Line.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineImpl.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/LineAdapterTest.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
No
New feature: a line's ends can be moved (to another node or another bus)
No
> Allows to move line ends

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerInternalConnectionsTest.java
- math/src/main/java/com/powsybl/math/graph/TraverseResult.java
- math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
- math/src/test/java/com/powsybl/math/graph/UndirectedGraphImplTest.java
No
Refactor
TraverseResult is not very easy to use, as the difference between `BREAK` and `TERMINATE` is not intuitive (although it is well documented!)
`TERMINATE_PATH` replaces `TERMINATE`
`TERMINATE_TRAVERSER` replaces `BREAK`
No, as this enum was not exposed in previous core version
> Clarify TraverseResult enum

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TwoWindingsTransformerConversion.java
No
Bug fix for faulty CGMES files
No
> If b undefined for transformer in CGMES, don't crash

- entsoe-util/src/main/java/com/powsybl/entsoe/util/MergedXnodeXmlSerializer.java
- entsoe-util/src/main/resources/xsd/mergedXnode_V1_1.xsd
- entsoe-util/src/test/resources/mergedXnodeRef.xml
No
Bug fix: namespace of mergedxnode was the voltage regulation extension namespace
> Bug fix: namespace of mergedxnode

- entsoe-util/src/main/java/com/powsybl/entsoe/util/MergedXnodeXmlSerializer.java
No
Bug fix: correct typo on serializer versions
> Bug fix: available versions of serialization are 1.0 and 1.1 for XIIDM 1.6

- cgmes/cgmes-measurements/pom.xml
> Fix SLF4J logs in test

- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/VoltageLevelAdapterTest.java
> Fix issue with java.util.Random mocking with JDK17

- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/GeneratorShortCircuitXmlSerializer.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/IdentifiableShortCircuitXmlSerializer.java
- iidm/iidm-xml-converter/src/main/resources/xsd/generatorShortCircuit.xsd
- iidm/iidm-xml-converter/src/main/resources/xsd/identifiableShortCircuit.xsd
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/GeneratorShortCircuitXmlSerializerTest.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/IdentifiableShortCircuitXmlSerializerTest.java
- iidm/iidm-xml-converter/src/test/resources/shortcircuits/generatorShortCircuitRef.xml
- iidm/iidm-xml-converter/src/test/resources/shortcircuits/voltageLevelShortCircuitRef.xml
Signed-off-by: Coline Piloquet <coline.piloquet@rte-france.com>
No
The XML serializers for GeneratorShortCircuit and IdentifiableShortCircuit are added.
> Add shortcircuits extensions xml serializer 

- commons/src/main/java/com/powsybl/commons/reporter/AbstractReporter.java
- commons/src/main/java/com/powsybl/commons/reporter/Report.java
- commons/src/main/java/com/powsybl/commons/reporter/ReportBuilder.java
- commons/src/main/java/com/powsybl/commons/reporter/Reporter.java
- commons/src/main/java/com/powsybl/commons/reporter/ReporterModel.java
- commons/src/main/java/com/powsybl/commons/reporter/ReporterModelDeserializer.java
- commons/src/main/java/com/powsybl/commons/reporter/ReporterModelJsonModule.java
- commons/src/main/java/com/powsybl/commons/reporter/ReporterModelSerializer.java
- commons/src/main/java/com/powsybl/commons/reporter/TypedValue.java
- commons/src/main/java/com/powsybl/commons/reporter/package-info.java
No
Docs update
`Reporter` and classes associated are marked as beta in the javadoc
The beta warning is removed
No
> Removing reporter beta warnings

- math/src/main/java/com/powsybl/math/matrix/AbstractMatrix.java
- math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
- math/src/main/java/com/powsybl/math/matrix/Matrix.java
- math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java
- math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java
- math/src/test/java/com/powsybl/math/matrix/SparseMatrixTest.java
- pom.xml
No
feature
We can add 2 matrices with the same dimension.
A new release (1.1.0) of math native is needed.
> Matrix addition

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/TerminalMapping.java
No
Performance issue
Very slow at finding a terminal from a given cgmesTerminal, hence very slow at importing a CGMES file
Faster at finding a terminal from a given cgmesTerminal, hence very slow at importing a CGMES file
No
> Construct Mapping from CgmesTerminal id to topological node id

- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
- cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Feature
dcTerminalsTP query has been deleted as it is not used and is not defined properly.
(if any of the …
> Delete unused code. dcTerminalsTP query

- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
- commons/src/main/java/com/powsybl/commons/config/BaseVoltagesConfig.java
- commons/src/test/java/com/powsybl/commons/config/BaseVoltagesConfigTest.java
No
Regression
We don't have anymore the jar resource fallback when config is not overloaded by user in its $HOME/.itools. …
> Fix base voltage config loading

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
No
Bug fix
Depending on the order of creation of line containers, nominal voltage can be badly set.
Obtain a nominal voltage reference to create fictitious voltage levers for line containers.
> During CGMES import, obtain a nominal voltage reference to create fictitious voltage levels for line containers

- matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java
- matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerModel.java
- matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
No
Bug fix
On large network, import is slow because of missing index for generators by bus number.
Matpower import is 50% faster. …
> Fix Matpower importer performance issue

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/components/AbstractComponentsManager.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
- loadflow/loadflow-api/src/test/resources/LoadFlowParameters.json
- loadflow/loadflow-api/src/test/resources/LoadFlowParametersWithExtension.json
- security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisParameters.json
- security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisParametersWithExtension.json
- sensitivity-analysis-api/src/test/resources/SensitivityAnalysisParameters.json
- sensitivity-analysis-api/src/test/resources/SensitivityAnalysisParametersWithExtension.json
No
feature
Load flow read slack bus is false by defaut
Load flow read slack bus is true by defaut
(if any …
> Load flow read slack bus by default

- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_rtc_ptc_tabular/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/CgmesConversionContextExtensionTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/CgmesImportPostProcessorTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ImportExportPerformanceTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesNetworkCatalog.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportersTest.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/tools/ImporterMock.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SimpleAnonymizerTest.java
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterTest.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/NetworkImporterMock.java
- ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/NamingStrategyTest.java
- ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
Fixes
- in CGMES tabular tap changers tests, do not use asymmetrical ptc
- use importData(DataSource, NetworkFactory, Properties) instead of deprecated importData(DataSource, Properties)
> Corrections in tests (miscellaneous)

- math/src/main/java/com/powsybl/math/graph/GraphUtil.java
- math/src/test/java/com/powsybl/math/graph/GraphUtilTest.java
No
Bug fix
StackOverflow for very large networks due to recursive method
No StackOverflow by changing the recursive method into a stacking one.
No
> Fix StackOverflow on very large networks

- commons/src/main/java/com/powsybl/commons/reporter/TypedValue.java
No
Feature
No typed value constant for active and reactive power
Typed value constants for active and reactive power
No
> Add active and reactive typed value constants for reporter

- iidm/iidm-scripting/pom.xml
No
Build warning fix
There is a duplicated dependency in iidm scripting pom.xml
Duplicated dependency has been fixed
**Other …
> Fix duplicate dependencies

- shortcircuit-api/src/test/resources/com/powsybl/config/test/config.yml
- shortcircuit-api/src/test/resources/com/powsybl/config/test/filelist.txt
No
Fix
Can fail depending on the locale of the OS
Does not depend of the local configuration, has a configuration for tests
No
**Other …
> Fix formatter config for CSV shortcircuits test

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractVoltageLevel.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TestAbstractVoltageLevel.java
- math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
- math/src/test/java/com/powsybl/math/graph/UndirectedGraphImplTest.java
> add vertex validation to UndirectedGraphImpl

- cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_Assembled_v2_three_lines_at_boundary/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_Assembled_v2_three_lines_at_boundary/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
- cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_Assembled_v2_three_lines_at_boundary/MicroGridTestConfiguration_BC_BE_TP_V2.xml
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/BoundaryEquipment.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
Feature
More than two lines at boundary is not supported.
Three lines at the boundary, one of them disconnected, is supported. A TieLine is created with the connected two lines. …
> Fix multiple lines at boundaries by discarding the disconnected one

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerAdderImpl.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerInternalConnectionsTest.java
> Fix transformers substation check

- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetail.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailAdder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LoadDetailAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LoadDetailImpl.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/LoadDetailXmlSerializer.java
Signed-off-by: Ruptam <ruptam25@outlook.com>
Fix #1968 
> conveted from floats to double

- contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java
- contingency/contingency-api/src/test/resources/contingency.json
No
Bug fix
We can serialize to json a load contingency element but not deserialize it.
We can deserialize a load contingency element. …
> Fix Load contingency deserialization

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
- cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingImpl.java
Log potentially missing information when building mapping data between CGMES and IIDM.
> CGMES-IIDM mapping: move the check for null TP nodes to the mapping

- matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java
- matpower/matpower-converter/src/test/resources/ieee118.xiidm
- matpower/matpower-converter/src/test/resources/ieee14-phase-shifter.xiidm
- matpower/matpower-converter/src/test/resources/ieee14.xiidm
- matpower/matpower-converter/src/test/resources/ieee30.xiidm
- matpower/matpower-converter/src/test/resources/ieee300.xiidm
- matpower/matpower-converter/src/test/resources/ieee57.xiidm
- matpower/matpower-converter/src/test/resources/ieee9.xiidm
- matpower/matpower-converter/src/test/resources/ieee9_limits.xiidm
> Import Matpower voltage limits

- pom.xml
No
Library update
threeten-extra 1.0
jackson 2.10.5
threeten-extra 1.5.0 used and required in powsybl-entsoe
jackson 2.11.2  used and required in powsybl-entsoe
No
> Update threeten and jackson libs

- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
No
Fix for slow builds (VM, ...)
> Ignore created time during CGMES files comparison

- math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
- math/src/test/java/com/powsybl/math/graph/UndirectedGraphImplTest.java
No
Bug fix
Value not checked
Value checked
No
> Vertex limit check

- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisResult.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFactor.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityValueKey.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisTest.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisToolTest.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityFactorTest.java
- sensitivity-analysis-api/src/test/resources/factorRef.json
No
Add new sensitivity function types to handle both sides of branches when relevant.
Sensitivty function type only handle side one of branches.
Both sides can be referenced now. …
> New sensitivity function types

- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/LoadConverter.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java
Same behavior as the current version. Load converter has been standardized. …
> Powerfactory: Load converter

- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/GeneratorXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/StaticVarCompensatorXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java
Signed-off-by: lazycoderextreme <ruptam25@gmail.com>
#1116
> Replacing Objects.equal with ==

- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerTest.java
- math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
> Fix NPE when removing a container (voltage level, substation...) after removing one switch

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Bus.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CalculatedBusImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConfiguredBusImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/MergedBus.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusAdapter.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractBusBreakerTest.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java
- iidm/iidm-xml-converter/src/main/resources/xsd/iidm_V1_8.xsd
- iidm/iidm-xml-converter/src/main/resources/xsd/iidm_equipment_V1_8.xsd
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/FictitiousInjectionsXmlTest.java
- iidm/iidm-xml-converter/src/test/resources/V1_8/eurostag-fict-inj.xml
- iidm/iidm-xml-converter/src/test/resources/V1_8/fictitiousSwitchRef-fict-inj.xml
> Add fictitious injections

- action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/ParallelLoadFlowActionSimulatorTest.java
- iidm/iidm-api/src/test/java/com/powsybl/iidm/network/BusRefTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/BusbarSectionAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/LineAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdapterTest.java
- iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdapterTest.java
- loadflow/loadflow-results-completion/src/test/java/com/powsybl/loadflow/resultscompletion/AbstractLoadFlowResultsCompletionTest.java
- pom.xml
- time-series/time-series-api/src/test/java/com/powsybl/timeseries/BigDoubleBufferTest.java
- time-series/time-series-api/src/test/java/com/powsybl/timeseries/BigStringBufferTest.java
No
Library update
Mockito 3.3.3
Mockito 4.4.0 (latest is 4.5.1 but was released yesterday)
Artifact mockito-inline added in dependency management
No
mockito-inline artifact allows to mock static methods since 3.4.0 version.
> Bump mockito to 4.4.0

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ModelDescriptionEq.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
While work is completed in #2034, this introduces a simple way to produce EQ, SSH, TP, SV files that contain the proper dependencies between them:
SV depends on SSH, TP.
SSH depends on EQ.
TP depends on EQ. …
> Update dependencies between model descriptions at export

- cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
- cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_Assembled_v2_gu_description_entsoe_category/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
- cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_Assembled_v2_gu_description_entsoe_category/MicroGridTestConfiguration_BC_NL_EQ_V2.xml
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/EntsoeCategoryPostProcessor.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
- cgmes/cgmes-model/src/main/resources/CIM16.sparql
> Fill ENTSOE category extension from CGMES generating unit description

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AttachVoltageLevelOnLine.java
- iidm/iidm-modification/src/test/resources/eurostag-line-split-nb-vl.xml
No
Fix: connectivity should be symmetrical when attaching a voltage level on a line.
> Fix: connectivity is symmetrical when attaching a voltage level on a line

- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysis.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisProvider.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/SecurityAnalysisExecutionImpl.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/execution/SecurityAnalysisExecutionBuilderTest.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/execution/SecurityAnalysisExecutionImplTest.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/tools/SecurityAnalysisToolTest.java
- security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysis.java
- security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysisProvider.java
- security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisProviderTest.java
- security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisTest.java
No
Feature
We cannot get functional logs (Reporter API) from a security analysis
Yes we can!
(if any of …
> Add functional logs to security analysis

- ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplExporter.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java
No
Following @geofjamg PR, use the new feature to specify possible fixed values.
No
> Add possible values for import/export parameters when possible

- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisProvider.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisProvider.java
feature
allow to implement the update of specific parameters for sensitivity and security
> allow to update specific parameters for sensitivity and security

- entsoe-util/src/main/java/com/powsybl/entsoe/util/MergedXnodeXmlSerializer.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/GeneratorStartup.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/GeneratorStartupAdder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorStartupAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorStartupAdderImplProvider.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorStartupImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/GeneratorStartupTest.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractGeneratorStartupTest.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/GeneratorStartupXmlSerializer.java
- iidm/iidm-xml-converter/src/main/resources/xsd/generatorStartup.xsd
- iidm/iidm-xml-converter/src/main/resources/xsd/generatorStartup_V1_0.xsd
- iidm/iidm-xml-converter/src/main/resources/xsd/generatorStartup_V1_1.xsd
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/GeneratorStartupXmlTest.java
- iidm/iidm-xml-converter/src/test/resources/V1_8/generatorStartupRef.xml
No
Moving code
`GeneratorStartup` is in [powsybl/powsybl-network-hypothesis](https://github.com/powsybl/powsybl-network-hypothesis)
`GeneratorStartup` is in core
**Does this PR introduce a breaking change or deprecate an API?** *If …
> Move GeneratorStartup extension to powsybl-core

- action/action-dsl/src/test/resources/scalable.groovy
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractCompoundScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractInjectionScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalableAdapter.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/StackScalable.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/UpDownScalable.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/DanglingLineScalableTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/GeneratorScalableTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/LoadScalableTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalableTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalableTestNetwork.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/UpDownScalableTest.java
No
Move scalables in iidm-modifications (issues with GraaVM and groovy dependencies in action-util)
> Move scalables in iidm-modification

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
No
Write dangling lines' terminals' power flows at network side
No
> Write dangling lines' terminals' power flows at network side

- .github/workflows/maven.yml
> Workflow trigger updated

- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/AbstractConverter.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/NodeConverter.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/SwitchConverter.java
- powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
- powerfactory/powerfactory-converter/src/test/resources/Switches.dgs
- powerfactory/powerfactory-converter/src/test/resources/Switches.xiidm
Feature
Behaviour has not been changed. Code has been reviewed and standardized.
(if any of the questions/checkboxes don't …
> Powerfactory: Review conversion of nodes and switches.

- pom.xml
- triple-store/triple-store-impl-rdf4j/pom.xml
- triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreRDF4J.java
- triple-store/triple-store-impl-rdf4j/src/test/java/com/powsybl/triplestore/impl/rdf4j/test/PowsyblWriterSequenceFixTest.java
Update RDF4J library to the latest published version (4.0.2)
> Triplestore: upgrade rdf4j to 4.0.2

- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/CommonImpedanceConverter.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java
- powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
- powerfactory/powerfactory-converter/src/test/resources/CommonImpedance.dgs
- powerfactory/powerfactory-converter/src/test/resources/CommonImpedance.xiidm
- powerfactory/powerfactory-converter/src/test/resources/CommonImpedanceOnlyImpedance12.dgs
- powerfactory/powerfactory-converter/src/test/resources/CommonImpedanceOnlyImpedance12.xiidm
Feature
Common Impedance lines  are not supported.
Common Impedance lines are now supported.
(if any of the …
> Powerfactory: Common Impedance (ElmZpu)

- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ShuntConverter.java
- powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
- powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAndShuntC.dgs
- powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAndShuntC.xiidm
- powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAndShuntRL.dgs
- powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAndShuntRL.xiidm
- powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAndShuntRLrxrea.dgs
- powerfactory/powerfactory-converter/src/test/resources/TwoBusesGeneratorAndShuntRLrxrea.xiidm
Feature. Shunt converter code has been reorganized. …
> Powerfactory: Shunt converter

- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ContainersMappingHelper.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/LineConverter.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java
- powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
- powerfactory/powerfactory-converter/src/test/resources/Tower.dgs
- powerfactory/powerfactory-converter/src/test/resources/Tower.xiidm
> Parallel lines defined using Tower (ElmTow).

- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/anonymizer/SimpleAnonymizer.java
No
Inheritance has been replaced by composition.
> Refactor simple anonymizer

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AttachNewLineOnLine.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AttachVoltageLevelOnLine.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/AttachNewLineOnLineTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/AttachVoltageLevelOnLineTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/TopologyTestUtils.java
- iidm/iidm-modification/src/test/resources/eurostag-line-split-nb-vl.xml
- iidm/iidm-modification/src/test/resources/fictitious-line-split-l.xml
- iidm/iidm-modification/src/test/resources/fictitious-line-split-vl.xml
Fix AttachNewLineOnLine
- Remove existing line before creating new lines
Fix AttachVoltageLevelOnLine
- Remove existing line before creating new lines
- Fix topology of voltage level
No
Bug fixes
Fix AttachNewLineOnLine
- Remove existing line before creating new lines
Fix AttachVoltageLevelOnLine
- Remove …
> Fixes AttachVoltageLevelOnLine and AttachNewLineOnLine

- action/action-simulator/src/main/java/com/powsybl/action/simulator/tools/ActionSimulatorTool.java
- action/action-simulator/src/test/java/com/powsybl/action/simulator/tools/ActionSimulatorToolTest.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/export/Exporter.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/export/Exporters.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/ImportConfig.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importer.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java
- iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/tools/ConversionTool.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/export/ExportersTest.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportersTest.java
- iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/PostProcessorReporterTest.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/tools/RunLoadFlowTool.java
No
Refactoring
Some of the static methods of Importers and Exporters could be directly moved to Importer and Exporter. …
> Importer and exporter refactoring

- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
No
Bug fix
Extension namespaces are written in random order
Extension namespaces are in deterministic order
No
> Fix extensions namespaces

- cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/Cgmes3ModifiedCatalog.java
- cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
- cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/singleFile/20210209T1930Z_1D_BE_9.xml
- cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_single_file/MicroGridTestConfiguration_BC_BE_V2.xml
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/Cgmes3ModifiedConversionTest.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
- cgmes/cgmes-model/src/main/resources/CIM100.sparql
- cgmes/cgmes-model/src/main/resources/CIM16.sparql
> Allow boundaries to be assembled with other network data in the same instance file

- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/LineAction.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/LineConnectionAction.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ActionDeserializer.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ActionSerializer.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
- security-analysis/security-analysis-api/src/test/resources/ActionFileTest.json
No, but I need it :-) 
I have followed the choices done for switch action. A dedicated action is needed if we work on bus/breaker network.
**Other …
> Line connection action

- pom.xml
Upgrade of RDF4J triplestore library.
No breaking change. 
Unit tests for CGMES import/export and conversion should run without problems.
> Upgrade rdf4j to latest version (4.1.0) for performance improvements

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AttachNewLineOnLineBuilder.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLine.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineBuilder.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLine.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLineBuilder.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateLineOnLineTest.java
- iidm/iidm-modification/src/test/resources/fictitious-line-split-l-complete.xml
- iidm/iidm-modification/src/test/resources/fictitious-line-split-vl-complete.xml
No
Improvement
A constructor (sometimes not really user-friendly) is used to create a network modification.
We can add a builder for each modification as proposed. If the design is agreed upon, it can be implemented for other network …
> Proposition for network modification builder

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
> Some fixes on network modification

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
No
Adds a method to get a map of orders by connectable
> [Network modifications] Add method to get orders by connectable 

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/PowerTransformerEq.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SynchronousMachineEq.java
> Add PowerTransformerEnd.ratedS and SynchronousMachine.EquipmentContainer info during CGMES export

- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ConnectablePosition.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
- iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line-order-used.xml
No
Bug fix
If the feeder position of the added line is already taken, the line is "half-added": either connected on one side only, or not connected on any sides.
We should either remove the line, or connect it without adding the feeder position extension.
No
> [Network modifications] Fix half-added line

- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/test/MetrixTutorialSixBusesFactory.java
- iidm/iidm-xml-converter/src/main/resources/metrix-tutorial-6-buses-network.xiidm
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/test/MetrixTutorialSixBusesFactoryTest.java
No
Feature
A new test network has been added: the 6 buses Metrix network
> Add Metrix tuto 6 buses test network

- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/BranchObservability.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/BranchObservabilityAdder.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/InjectionObservability.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/InjectionObservabilityAdder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BranchObservabilityAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BranchObservabilityImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/InjectionObservabilityAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/InjectionObservabilityImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/InjectionObservabilityTest.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractBranchObservabilityTest.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractInjectionObservabilityTest.java
the adder of Observability extension have not been updated
initially redundancy are set to false in the adder
initially redundancy are set to null in the adder
> fix observability adder

- pom.xml
No
Fix vulnerability CVE-2022-38752 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-38752
> Bump snakeyaml to 1.32 (fix vulnerability [CVE-2022-38752])

- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/GeneratorShortCircuit.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/IdentifiableShortCircuit.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/IdentifiableShortCircuitAdderImplProvider.java
This reverts commit a68b5c54d3861fd3d2db3298487a2a470a162b8c.
> Revert "Fix IdentifiableShortCircuit so that it only applies to voltage levels, buses and busbar sections. (#2285)"

- cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
- cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_station_supply/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
- cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_station_supply/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
- cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_station_supply/MicroGridTestConfiguration_BC_BE_TP_V2.xml
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
- cgmes/cgmes-model/src/main/resources/CIM16.sparql
> CGMES: consider station supply objects in import

- pom.xml
- tools/pom.xml
> Upgrade string template version

- iidm/iidm-comparator/src/main/java/com/powsybl/iidm/comparator/NetworkStateComparator.java
> ShuntCompensator active power comparison in NetworkStateComparator

- pom.xml
No
Vulnerabilities fix: [CVE-2022-42003] [CVE-2022-42004]
> Bump jackson to 2.13.4 and jackson-databind to 2.13.4.2 [CVE-2022-42003] [CVE-2022-42004]

- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/GeneratorActionBuilder.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/LoadAction.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/LoadActionBuilder.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisJsonModule.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/LoadActionDeserializer.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/LoadActionSerializer.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
- security-analysis/security-analysis-api/src/test/resources/ActionFileTest.json
> Load action

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
No
Quality: reducing technical debt
> Small clean in CgmesExportContext (renaming and small refactoring)

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLine.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLine.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RevertCreateLineOnLine.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RevertCreateLineOnLineBuilder.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RevertCreateLineOnLineTest.java
No
Refactor
Duplicate code for getting tee point from 3 lines
Duplicate code factorized in `TopologyModificationUtils`
No
> [Network modification] Factorize get tee point from lines

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesReports.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportProfilesConsistencyTest.java
- cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-invalid-voltage-bus.txt
- cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-target-deadband.txt
- cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE.txt
- cgmes/cgmes-conversion/src/test/resources/functional-logs/miniGridNodeBreaker.txt
> Refactoring CGMES logs

- cgmes/cgmes-measurements/src/main/java/com/powsybl/cgmes/measurements/CgmesMeasurementsModel.java
- cgmes/cgmes-shortcircuit/src/main/java/com/powsybl/cgmes/shorcircuit/CgmesShortCircuitModel.java
- triple-store/triple-store-api/pom.xml
- triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStoreUtils.java
- triple-store/triple-store-api/src/test/java/com/powsybl/triplestore/api/test/TripleStoreUtilsTest.java
No
Refactoring: avoid code duplication to query triplestore catalog
> Refactoring: create TripleStoreUtils with method to query catalog (used in post processors)

- commons/src/main/java/com/powsybl/commons/config/ModuleConfigUtil.java
- commons/src/main/java/com/powsybl/commons/parameters/Parameter.java
- commons/src/main/java/com/powsybl/commons/parameters/ParameterDefaultValueConfig.java
- commons/src/main/java/com/powsybl/commons/parameters/ParameterType.java
- commons/src/test/java/com/powsybl/commons/parameters/ParameterDefaultValueConfigTest.java
- commons/src/test/java/com/powsybl/commons/parameters/ParameterTest.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
- loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderMock.java
- loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowTest.java
No
Feature
We can only get the name of loadflow specific parameters.
We can get a full description of loadflow specific parameters.
Also added support to INTEGER parameters. …
> Full description of loadflow specific parameters

- dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/EventModel.java
- dynamic-simulation/dynamic-simulation-dsl/src/test/groovy/com/powsybl/dynamicsimulation/groovy/DummyEventModelGroovyExtension.groovy
- dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/DummyEventModel.java
- dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/GroovyEventModelSupplierTest.java
- dynamic-simulation/dynamic-simulation-dsl/src/test/resources/eventModels.groovy
No
feature
`EventModel` interface has no methods
`EventModel::getStartTime` added
**Does this PR introduce a breaking change or deprecate an API?** yes
> [dynamic-simulation] Add EventModel startTime

- powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsHandler.java
- powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsParser.java
- powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsReader.java
- powerfactory/powerfactory-dgs/src/test/java/com/powsybl/powerfactory/dgs/DgsDataTest.java
- powerfactory/powerfactory-dgs/src/test/resources/ascii_v6.dgs
- powerfactory/powerfactory-dgs/src/test/resources/ascii_v7.dgs
#2428 
Feature
We only support DGS ASCII 5 and we are not able to detect an unsupported version of DGS
We throw an exception when DGS version is 6 or 7. `DgsHandler` has been refactored to prepare 6 and 7 support so that ID read …
> PowerFactory: prepare for DGS 6 and 7 support

- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControlAdder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlAdderImplProvider.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/SecondaryVoltageControlTest.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractSecondaryVoltageControlTest.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
- iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/SecondaryVoltageControlXmlSerializer.java
- iidm/iidm-xml-converter/src/main/resources/xsd/secondaryVoltageControl_V1_0.xsd
- iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/SecondaryVoltageControlXmlTest.java
- iidm/iidm-xml-converter/src/test/resources/V1_8/secondaryVoltageControlRoundTripRef.xml
> Add secondary voltage control IIDM extension

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevel.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevelBuilder.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevelTest.java
- iidm/iidm-modification/src/test/resources/eurostag-remove-voltage-level-bb.xml
- iidm/iidm-modification/src/test/resources/eurostag-remove-voltage-level-nb.xml
Feature: this PR implements the 'remove voltage level' modification. When the modification is applied, the voltage level, its equipments and the branches it is connected to are removed.
> Remove voltage level and its equipments

- commons/src/main/java/com/powsybl/commons/config/BaseVoltagesConfig.java
- pom.xml
No
Fix vulnerability [CVE-2022-1471](https://www.cve.org/CVERecord?id=CVE-2022-1471)
> Bump snakeyaml to 2.0. Fix [CVE-2022-1471]

- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
No
Feature
LoadFlowParameters.toMap is protected.
LoadFlowParameters.toMap is public.
> LoadFlowParameters.toMap public

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java
No
Fix the javadoc in scalable class.
> Fix javadoc scalable.

- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
This PR complements the change made in #2501.
We create fictitious substations when we export IIDM networks that contain fictitious voltage levels corresponding to CGMES `Line` containers that were not located at the boundaries.
Just a unit test for the change made in #2501
> CGMES. Test creation of fictitious substations 

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalingParameters.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/JsonScalingParameters.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/ScalingParametersDeserializer.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/ScalingParametersJsonModule.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/ScalingParametersSerializer.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalingParametersTest.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/json/JsonScalingParametersTest.java
- iidm/iidm-modification/src/test/resources/json/ScalingParameters.json
- iidm/iidm-modification/src/test/resources/json/ScalingParametersError.json
No
To make entso-e processes work (balance computation and GLSK), we need serialization and loading
No
> Add loading from platform config and serialization for ScalingParameters

- contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/AbstractEquipmentCriterionContingencyList.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/HvdcLineCriterionContingencyList.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/InjectionCriterionContingencyList.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/LineCriterionContingencyList.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/ThreeWindingsTransformerCriterionContingencyList.java
- contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/TwoWindingsTransformerCriterionContingencyList.java
No
Fix code smell
Duplicate code
Code factorized
No
> Remove duplicate code

- contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyElement.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/BusContingencyTest.java
> Fix: support of BusContingency in ContingencyElement

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/GraphvizConnectivity.java
No
Bug fix
Tie lines are not exported anymore in graphviz export
Tie lines exported again
No
> Export tie lines in graphviz export

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
No
Fix - SUV related for CGMES export: all terminals are associated to a SvPowerFlow
> CGMES: Export all SvPowerflow for switches

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java
- iidm/iidm-api/src/test/java/com/powsybl/iidm/network/util/SVTest.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java
Feature
Not all the otherSide methods support the Dc approximation.
Dc approximation has been added to all the otherSide methods
> SV: fix DC approximation

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TwoWindingsTransformerConversion.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLine.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
- iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
- ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
No
Docs update
Javadoc refers to half lines
Javadoc up-to-date
No
> Update javadoc following halfLine replacement

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
No.
When a tie line is removed, the underlying dangling lines `P0` and `Q0` can be updated or not. 
> Tie line: improve remove method

- .github/workflows/maven.yml
- .gitignore
- .mvn/wrapper/maven-wrapper.properties
- README.md
- install.sh
- mvnw
- mvnw.cmd
No
Feature
powsybl-core needs an installed Maven distribution to be compiled.
powsybl-core can be compiled using Maven Wrapper.
No
> Add Maven Wrapper

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NodeMapping.java
> CGMES import: fix ensure unicity for switches

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
No
Small fix
We saw in the logs that one space is missing, now it's fixed
> [Network modifications] Add space in log and report

- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/StaticVarCompensatorAction.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/StaticVarCompensatorActionBuilder.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisJsonModule.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/StaticVarCompensatorActionDeserializer.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/StaticVarCompensatorActionSerializer.java
- security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
- security-analysis/security-analysis-api/src/test/resources/ActionFileTest.json
- security-analysis/security-analysis-api/src/test/resources/ActionFileTestV1.0.json
feature
it adds an action for static var compensator
> Support of static var compensator action

- pom.xml
No
Lib update to fix groovy-groovydoc
powsybl-parent 14 and mvn verify fails
powsybl-parent 15
No
> Bump poswybl-parent to 15

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
> Add a getSide() from Three Windings Transformer Leg

- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitConstants.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitParameters.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/ShortCircuitParametersDeserializer.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/ShortCircuitParametersSerializer.java
- shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitParametersTest.java
- shortcircuit-api/src/test/resources/ShortCircuitParameters.json
- shortcircuit-api/src/test/resources/ShortCircuitParametersVersion12.json
- shortcircuit-api/src/test/resources/ShortCircuitParametersVersion13.json
- shortcircuit-api/src/test/resources/config.yml
No
Feature
No parameter
Adds a parameters indicating if the functional logs (from reporter) should be detailed or aggregated
> [Shortcircuit API] Add detailedReport in parameters

- iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducer.java
- iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/DefaultNetworkReducerTest.java
Bug fix
Hvdc lines with VSC converter and `voltageRegulatorOn`  `false` were not removed.
They are changed by a Load and removed.
> IIDM Network reducer: Fix hvdc remove

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTerminal.java
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractBusBreakerTest.java
No
Feature
We are notified when a terminal is connected of disconnected.
> Add a listener on terminal connection

- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerTest.java
No
Bugfix
The error message in the tests are fixed while some implementation can throw a different error message.
The error message in the tests uses a regex in order to be more generic.
> Modification on connect/disconnect tests

- iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_11.xsd
No
Bug fix
iidm v1.11 equipment xsd refers to 1.10 namespace
iidm v1.11 equipment xsd refers to 1.11 namespace
> Fix iidm v1.11 equipment xsd

- pom.xml
No
Vulnerability fix
ch.qos.logback logback-core and logback-classic are in version 1.4.13.
ch.qos.logback logback-core and logback-classic are in version **1.4.14**.
It provides a "more complete fix" for [CVE-2023-6378](https://nvd.nist.gov/vuln/detail/CVE-2023-6378) ([source](https://logback.qos.ch/news.html#1.3.14)).
> Bump ch.qos.logback logback-core and logback-classic to 1.4.14

- ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModelRunner.java
> Add async run for ampl

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MergeTest.java
> Add case date handling when merging networks

- cgmes/cgmes-shortcircuit/src/main/java/com/powsybl/cgmes/shorcircuit/PerUnit.java
- powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/TransformerConverter.java
- security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolations.java
- shortcircuit-api/pom.xml
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/AbstractFault.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/BranchFault.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/BusFault.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/Fault.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FaultResult.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FeederResult.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitParameters.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/VoltageRange.java
- ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteNode.java
No
Docs update
It is unclear when shortcircuit, short circuit and short-circuit is used.
I tried to make the English as correct as possible in the javadoc. ONLY modifications to the javadoc should be done.
> [ShortCircuit] Corrections in javadoc

- iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/GeneratorShortCircuit.java
- shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitParameters.java
No
Docs update
"Subtransient" written instead of sub-transient in the javadoc.
Corrects the javadoc.
> [ShortCircuit] Fix javadoc for sub-transient

- action-api/src/test/java/com/powsybl/action/json/JsonActionTest.java
- pom.xml
no
dependencies upgrade
upgrade jackson to v2.17
- [Jackson 2.16 changes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.16#changes-behavior)
- [Jackson 2.17 changes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.17#changes-behavior)
> Upgrade jackson to v2.17

- cim-anonymiser/src/test/java/com/powsybl/cim/CimAnonymizerToolTest.java
- dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationToolTest.java
- dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/ListDynamicSimulationModelsToolTest.java
- iidm/iidm-api/src/test/java/com/powsybl/iidm/network/tools/ConversionToolTest.java
- scripting/src/test/java/com/powsybl/scripting/RunScriptToolTest.java
- sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisToolTest.java
- shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisToolTest.java
- tools-test/src/main/java/com/powsybl/tools/test/AbstractToolTest.java
- tools-test/src/test/java/com/powsybl/tools/test/CommandLineToolsTest.java
- tools-test/src/test/java/com/powsybl/tools/test/PluginsInfoToolTest.java
- tools-test/src/test/java/com/powsybl/tools/test/VersionToolTest.java
No
Refactor
When using _assertCommand_ in _ToolTest_, out and err stream are tested against expected out and err but values don't have to be strictly equals : expected values has to be found in the related stream.
This function is useful for err stream when you want to match the type of error in a stack, but for output a strict comparison could be more useful.
Separate strict and match comparison
> Refactor assert command

- contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
- contingency/contingency-api/src/test/java/com/powsybl/contingency/BatteryContingencyTest.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
no 
add missing feature
validate battery contingencies
> Add missing battery contingency validation

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevel.java
report removed injections when removing voltage levels
> Report removed injections when removing voltage levels

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
- cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
> Add slack bus mismatch: slack terminal can be disconnected

- docs/grid_model/additional.md
- docs/grid_model/img/currentLimitsExample1.svg
- docs/grid_model/img/currentLimitsExample2.svg
- docs/grid_model/network_subnetwork.md
Documentation update
This PR adds documentation (mostly code examples) on additional network models (limits, tap changers, reactive limits). The documentation is taken from the website powsybl.org. 
- [] Yes
> Add examples for additional network models

- docs/grid_exchange_formats/index.md
No
Fix
Some information from the website has been lost (order and short description in index)
- ordered exchange formats
- short description added through a table
- import/export support added inside the table
- adding PowerFactory exchange format entry in the table
> Doc: reordering exchange formats and add table

- docs/grid_features/extraction.md
Additional information on network reducer (missing from previous PR): details on replacement by loads and by dangling lines
> Additional info on network reducer

- iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/ActivePowerControlSerDe.java
- iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
- iidm/iidm-serde/src/test/resources/V1_12/activePowerControlWithLimitRoundTripRef.xml
- iidm/iidm-serde/src/test/resources/V1_12/eurostag-tutorial1-lf-extensions.json
No
Feature
- ActivePowerControl extension v1.2 is supported since IIDM 1.12;
- When serialized in IIDM 1.12, the default version for this extension is v1.2.
- ActivePowerControl extension v1.2 is supported since IIDM 1.13;
- When serialized in IIDM 1.12, the default version for this extension is v1.1 (as previously).
This is possible do to this change because #3054 is not yet in a release.
There is no need to support this version in IIDM 1.12 and it is best not to change the default serialization version of the extension for IIDM …
> Support ActivePowerControl extension v1.2 only since IIDM v1.13

- pom.xml
No
Feature
We use math native 1.3.1
We use math native 1.4.0
> Upgrade math native to 1.4.0

- docs/simulation/security/index.md
- docs/simulation/security/limit-reductions.md
No
Documentation
Add documentation about limit reductions
> Documentation about limit reductions

- docs/grid_model/network_subnetwork.md
No
Small documentation improvements.
> Add Overload Management System documentation

- README.md
- docs/conf.py
- docs/grid_exchange_formats/cgmes/import.md
- docs/grid_model/extensions.md
- docs/grid_model/network_subnetwork.md
- docs/index.md
- docs/simulation/dynamic/configuration.md
- docs/simulation/dynamic/index.md
- docs/simulation/dynamic_security/configuration.md
- docs/simulation/loadflow/configuration.md
- docs/simulation/loadflow/index.md
- docs/user/itools/index.md
No
Docs update
Some links are broken in the documentation, they were not yet updated after the creation of the repositories.
Fixes the dead links.
> [Documentation] Fix broken links

- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
No
Feature
When reading a network from a data source we now have access to all parameters.
> Add all parameters network read method from a data source

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/RemoteReactivePowerControlImpl.java
No
Checkstyle
CI fails
CI succeeds
> Fix checkstyle

- docs/grid_exchange_formats/iidm/index.md
No
Fix doc
The link to https://www.itesla-project.eu/ is dead (domain for sale)
The link has been removed, name "itesla-project" has been kept for history.  
> Remove link to https://www.itesla-project.eu/

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveFeederBay.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevel.java
- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
- iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevelTest.java
No
Bug fix
Remove voltage level network modification fails for some voltage levels which:
- contain loops
- are connected via a tie line.
It doesn't fail
> Fix remove voltage level

- iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
no
Bug fix
fix a log that has a wrong variable 
> Fix `positionOrderTooHigh` reports log

- docs/grid_features/index.md
- docs/grid_features/network_modifications.md
Add documentation page for NetworkModifications other than topology, scalable or tripping modifications
Add documentation about the available NetworkModification.
> Add documentation page for NetworkModifications

- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/NamespaceReader.java
> Cgmes load zipped profiles mutualize stream

- math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
No
Remove dead code
dead code in `removeIsolatedVertices(int v, TIntArrayList[] adjacencyList, boolean notify)`
dead code removed
> Remove dead code in UndirectedGraphImpl::removeIsolatedVertices

- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/GeneratingUnitEq.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/LoadingLimitEq.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/OperationalLimitTypeEq.java
- cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/TapChangerEq.java
- cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
No.
Refactoring.
Some methods had been created in the `CgmesNamespace` interface to make the distinction between the CIM14/CIM16/CIM100 schemas. This is not the right place to make that and it's not necessary since it is as simple to request the cim version number to distinguish what needs to be exported.
Cim version number is used in export classes to make the distinction between cim schemas. …
> Refactor `CgmesNamespace` interface

- docs/user/functional_logs/import.md
- docs/user/functional_logs/index.md
Fix documentation about ReportNode (i18n)
> Fix documentation about ReportNode

- dynamic-security-analysis/src/main/java/com/powsybl/security/dynamic/tools/DynamicSecurityAnalysisTool.java
- dynamic-security-analysis/src/test/java/com/powsybl/security/dynamic/tools/DynamicSecurityAnalysisToolTest.java
No
Bug fix
`DynamicSecurityAnalysisTool` does not load the dynamic model file properly, thus the simulation cannot be launched.
Handle dynamic model file in DynamicSecurityAnalysisTool
> Dynamic security analysis tool models load

- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
No
Code refactoring
A big test contains a lot of assertions + some `assertThrows` assertions are done on multiple methods so the following issues are raised by Sonar: `Refactor the code of the lambda to have only one invocation possibly throwing a runtime exception`
The big test is now divided in multiple smaller tests. The `assertThrows` assertions have been rewritten in order to test a single method.
Note: a few `assertThrows` assertions with multiple methods remain since changing them would create a breaking change. It will be …
> Refactor AbstractThreeWindingsTransformerTest

- psse/psse-model/src/main/java/com/powsybl/psse/model/io/LegacyTextReader.java
- psse/psse-model/src/test/java/com/powsybl/psse/model/io/LegacyTextReaderTest.java
No
Bux fix / security
Potential backtracking on PSS/E import.
The regex used is no more vulnerable to backtracking.
> Prevent potential backtracking on PSS/E import

- docs/grid_model/additional.md
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/OperationalLimitsGroup.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/PropertiesHolder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractPropertiesHolder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PropertiesContainer.java
- iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ConnectableSerDeUtil.java
- iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/PropertiesSerDe.java
- iidm/iidm-serde/src/main/resources/xsd/iidm_V1_14.xsd
- iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_14.xsd
- iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/LoadingLimitsXmlTest.java
- iidm/iidm-serde/src/test/resources/V1_12/operational-limits-groups-with-properties.xml
- iidm/iidm-serde/src/test/resources/V1_13/operational-limits-groups-with-properties.xml
- iidm/iidm-serde/src/test/resources/V1_14/operational-limits-groups-with-properties.xml
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractOperationalLimitsGroupsTest.java
Fixes #3420 
Custom IIDM implementations' maintainers should implement the following methods in their `OperationalLimitsGroup` implementations:
- `public boolean hasProperty()`
- `public boolean hasProperty(String key)`
- `public String getProperty(String key)`
- `public String getProperty(String key, String defaultValue)`
- `public String setProperty(String key, String value)`
- `public boolean removeProperty(String key)`
- `public Set<String> …
> Support properties on OperationalLimitsGroup

- docs/grid_model/additional.md
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TapChanger.java
- iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TapChangerAdder.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChangerAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerAdderImpl.java
- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java
- iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java
- iidm/iidm-serde/src/main/resources/xsd/iidm_V1_14.xsd
- iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_14.xsd
- iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/RatioTapChangerSerDeTest.java
- iidm/iidm-serde/src/test/resources/V1_14/ratioTapChangerReactivePowerControlRefWithSolvedTapPosition.xml
- iidm/iidm-serde/src/test/resources/V1_14/twoWindingsTransformerPhaseAndRatioTapWithExtensions.xml
- iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTwoWindingsTransformerTest.java
Fixes (partially) #3418 
Custom IIDM implementation maintainers should implement the following methods:
- in their `TapChanger`'s implementations:
- `Integer getSolvedTapPosition()`
- `C setSolvedTapPosition(int solvedTapPosition)`
- `C unsetSolvedTapPosition()`
- `S getSolvedCurrentStep();`
- in their `TapChangerAdder`'s implementations:
- `S setSolvedTapPosition(Integer solvedTapPosition)`
> iIDM v1.14: Solved values - Add solved tap position

- pom.xml
No
Bug fix
Groovy doc generation fails due to an incompatibility between groovy and GMavenPlus (see https://github.com/groovy/GMavenPlus/issues/335).
```text
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:3.0.0:groovydoc-jar (groovydoc-jar) on project powsybl-action-api: Execution groovydoc-jar of goal org.codehaus.gmavenplus:gmavenplus-plugin:3.0.0:groovydoc-jar failed: Unable to find constructor org.codehaus.groovy.tools.groovydoc.GroovyDocTool(interface org.codehaus.groovy.tools.groovydoc.ResourceManager, [Ljava.lang.String;, [Ljava.lang.String;, …
```
> Downgrade Groovy version due to incompatibility with the GMavenPlus plugin

- iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/VoltageRegulationImpl.java
- iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/VoltageRegulationTest.java
> Support the regulating terminal's removal in VoltageRegulation extension

- docs/simulation/shortcircuit/index.md
no
doc update
Short-Circuit documentation links to incubator for short circuit implementation, but this implementation was moved to powsybl-open-sc meanwhile
link to powsybl-open-sc
> Doc: short-circuit implementation is now in powsybl-open-sc

- docs/grid_model/network_subnetwork.md
#3487 
Docs update, #3520 forgot to update documentation...
outdated doc
added documentation of DC topology processing
> Add DC topology processing documentation

- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java
- loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysis.java
- sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisProvider.java
No
Documentation fix
Newly deprecated methods reference the `6.9.0` version which does not exist (it is in fact the `7.0.0` version).
Newly deprecated methods reference the **`7.0.0`** version.
> Fix version number in deprecated annotations (6.9.0 -> 7.0.0)
